// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/AvatarGroup.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.AvatarGroup JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/AvatarGroup.mjs): shape.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("AvatarTypes.Sm")
      | "md" => Some("AvatarTypes.Md")
      | "lg" => Some("AvatarTypes.Lg")
      | "xl" => Some("AvatarTypes.Xl")
      | _ => None
      }
    )

  "<AvatarGroup" ++ CodeConnectUtils.attr("size", size) ++ " />"
}
