// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/AvatarGroup.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.AvatarGroup's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.AvatarGroup for the same reason -- pass
// ~tagName (e.g. "Blend.AvatarGroup") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/AvatarGroup.mjs): shape.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("JuspayRescriptBlend.AvatarTypes.Sm")
      | "md" => Some("JuspayRescriptBlend.AvatarTypes.Md")
      | "lg" => Some("JuspayRescriptBlend.AvatarTypes.Lg")
      | "xl" => Some("JuspayRescriptBlend.AvatarTypes.Xl")
      | _ => None
      }
    )

  [CodeConnectUtils.propEntry("size", size)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.AvatarGroup",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
