// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Button.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Button's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Button for the same reason -- pass
// ~tagName (e.g. "Blend.Button") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Button.mjs): loading, showSkeleton, skeletonVariant, buttonGroupPosition, fullWidth, justifyContent, state.
// Not covered (unfilled figmaProp/values, instanceSwap, or otherwise not statically derivable): leadingIcon, trailingIcon. Splice these in at the call site if needed.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let text = props->CodeConnectUtils.getStringProp("text")
  let buttonType =
    props
    ->CodeConnectUtils.getStringProp("buttonType")
    ->Option.flatMap(v =>
      switch v {
      | "primary" => Some("JuspayRescriptBlend.ButtonTypes.Primary")
      | "secondary" => Some("JuspayRescriptBlend.ButtonTypes.Secondary")
      | "danger" => Some("JuspayRescriptBlend.ButtonTypes.Danger")
      | "success" => Some("JuspayRescriptBlend.ButtonTypes.Success")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("JuspayRescriptBlend.ButtonTypes.Sm")
      | "md" => Some("JuspayRescriptBlend.ButtonTypes.Md")
      | "lg" => Some("JuspayRescriptBlend.ButtonTypes.Lg")
      | _ => None
      }
    )
  let subType =
    props
    ->CodeConnectUtils.getStringProp("subType")
    ->Option.flatMap(v =>
      switch v {
      | "default" => Some("JuspayRescriptBlend.ButtonTypes.Default")
      | "iconOnly" => Some("JuspayRescriptBlend.ButtonTypes.IconOnly")
      | "inline" => Some("JuspayRescriptBlend.ButtonTypes.Inline")
      | _ => None
      }
    )
  let disabled =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "disabled" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | _ => None
      }
    )

  [
    CodeConnectUtils.strPropEntry("text", text),
    CodeConnectUtils.propEntry("buttonType", buttonType),
    CodeConnectUtils.propEntry("size", size),
    CodeConnectUtils.propEntry("subType", subType),
    CodeConnectUtils.propEntry("disabled", disabled),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Button",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
