// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Button.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Button JSX text from a Figma
// component-properties array.
// Not covered (unfilled figmaProp/values, instanceSwap, or otherwise not statically derivable): skeletonVariant, fullWidth, justifyContent, leadingIcon, trailingIcon. Splice these in at the call site if needed.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let text = props->CodeConnectUtils.getStringProp("Text")
  let buttonType =
    props
    ->CodeConnectUtils.getStringProp("Button Type")
    ->Option.flatMap(v =>
      switch v {
      | "PRIMARY" => Some("ButtonTypes.Primary")
      | "SECONDARY" => Some("ButtonTypes.Secondary")
      | "DANGER" => Some("ButtonTypes.Danger")
      | "SUCCESS" => Some("ButtonTypes.Success")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("Size")
    ->Option.flatMap(v =>
      switch v {
      | "SMALL" => Some("ButtonTypes.Sm")
      | "MEDIUM" => Some("ButtonTypes.Md")
      | "LARGE" => Some("ButtonTypes.Lg")
      | _ => None
      }
    )
  let subType =
    props
    ->CodeConnectUtils.getStringProp("Sub Type")
    ->Option.flatMap(v =>
      switch v {
      | "DEFAULT" => Some("ButtonTypes.Default")
      | "ICON_ONLY" => Some("ButtonTypes.IconOnly")
      | "INLINE" => Some("ButtonTypes.Inline")
      | _ => None
      }
    )
  let disabled = props->CodeConnectUtils.getBoolProp("Disabled")
  let buttonGroupPosition =
    props
    ->CodeConnectUtils.getStringProp("Group Position")
    ->Option.flatMap(v =>
      switch v {
      | "LEFT" => Some("ButtonTypes.Left")
      | "CENTER" => Some("ButtonTypes.Center")
      | "RIGHT" => Some("ButtonTypes.Right")
      | _ => None
      }
    )
  let state =
    props
    ->CodeConnectUtils.getStringProp("State")
    ->Option.flatMap(v =>
      switch v {
      | "DEFAULT" => Some("ButtonTypes.Default")
      | "HOVER" => Some("ButtonTypes.Hover")
      | "ACTIVE" => Some("ButtonTypes.Active")
      | "DISABLED" => Some("ButtonTypes.Disabled")
      | _ => None
      }
    )
  let loading = props->CodeConnectUtils.getBoolProp("Loading")
  let showSkeleton = props->CodeConnectUtils.getBoolProp("Show Skeleton")

  "<Button" ++
  CodeConnectUtils.strAttr("text", text) ++
  CodeConnectUtils.attr("buttonType", buttonType) ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.attr("subType", subType) ++
  CodeConnectUtils.boolAttr("disabled", disabled) ++
  CodeConnectUtils.attr("buttonGroupPosition", buttonGroupPosition) ++
  CodeConnectUtils.attr("state", state) ++
  CodeConnectUtils.boolAttr("loading", loading) ++
  CodeConnectUtils.boolAttr("showSkeleton", showSkeleton) ++
  " />"
}
