// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Button.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Button JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Button.mjs): loading, showSkeleton, skeletonVariant, buttonGroupPosition, fullWidth, justifyContent, state.
// Not covered (unfilled figmaProp/values, instanceSwap, or otherwise not statically derivable): leadingIcon, trailingIcon. Splice these in at the call site if needed.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let text = props->CodeConnectUtils.getStringProp("text")
  let buttonType =
    props
    ->CodeConnectUtils.getStringProp("buttonType")
    ->Option.flatMap(v =>
      switch v {
      | "primary" => Some("ButtonTypes.Primary")
      | "secondary" => Some("ButtonTypes.Secondary")
      | "danger" => Some("ButtonTypes.Danger")
      | "success" => Some("ButtonTypes.Success")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("ButtonTypes.Sm")
      | "md" => Some("ButtonTypes.Md")
      | "lg" => Some("ButtonTypes.Lg")
      | _ => None
      }
    )
  let subType =
    props
    ->CodeConnectUtils.getStringProp("subType")
    ->Option.flatMap(v =>
      switch v {
      | "default" => Some("ButtonTypes.Default")
      | "iconOnly" => Some("ButtonTypes.IconOnly")
      | "inline" => Some("ButtonTypes.Inline")
      | _ => None
      }
    )
  let disabled =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "disabled" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | _ => None
      }
    )

  "<Button" ++
  CodeConnectUtils.strAttr("text", text) ++
  CodeConnectUtils.attr("buttonType", buttonType) ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.attr("subType", subType) ++
  CodeConnectUtils.attr("disabled", disabled) ++ " />"
}
