// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/ButtonGroup.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.ButtonGroup JSX text from a Figma
// component-properties array.
let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let stacked = props->CodeConnectUtils.getBoolProp("stack")

  "<ButtonGroup" ++ CodeConnectUtils.boolAttr("stacked", stacked) ++ " />"
}
