// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/ButtonGroup.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.ButtonGroup's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.ButtonGroup for the same reason -- pass
// ~tagName (e.g. "Blend.ButtonGroup") to render any other tag/prefix.
let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let stacked = props->CodeConnectUtils.getBoolProp("stack")

  [CodeConnectUtils.boolPropEntry("stacked", stacked)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.ButtonGroup",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
