// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Charts.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Charts JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Charts.mjs): legendPosition, stackedLegends, showHeader, showCollapseIcon, isExpanded, chartName.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let chartType =
    props
    ->CodeConnectUtils.getStringProp("type")
    ->Option.flatMap(v =>
      switch v {
      | "line" => Some("HighchartsSharedTypes.Line")
      | "bar" => Some("HighchartsSharedTypes.Bar")
      | "pie" => Some("HighchartsSharedTypes.Pie")
      | _ => None
      }
    )

  "<Charts" ++ CodeConnectUtils.attr("chartType", chartType) ++ " />"
}
