// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Charts.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Charts's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Charts for the same reason -- pass
// ~tagName (e.g. "Blend.Charts") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Charts.mjs): legendPosition, stackedLegends, showHeader, showCollapseIcon, isExpanded, chartName.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let chartType =
    props
    ->CodeConnectUtils.getStringProp("type")
    ->Option.flatMap(v =>
      switch v {
      | "line" => Some("JuspayRescriptBlend.HighchartsSharedTypes.Line")
      | "bar" => Some("JuspayRescriptBlend.HighchartsSharedTypes.Bar")
      | "pie" => Some("JuspayRescriptBlend.HighchartsSharedTypes.Pie")
      | _ => None
      }
    )

  [CodeConnectUtils.propEntry("chartType", chartType)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Charts",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
