// GENERATED by scripts/generate-figma-code-connect.mjs. Do not edit by hand.
//
// Dispatches by figmaComponentName so a consumer doesn't hand-maintain its
// own Figma-component-name -> module switch (the same duplication toProps
// already removes for property mappings, one level up for components).
//
// IMPORTANT: figmaComponentName is whatever identifier blend-design-system's
// own *.figma.tsx uses in its figma.connect(<ComponentName>, ...) call --
// NOT necessarily the literal name shown in Figma's layers/Inspect panel.
// Where the two are known to differ (e.g. Button's real Figma component set
// is named "Buttons", plural), figma/figmaComponentAliases.mjs supplies the
// extra name(s) below, so the caller can still pass the raw Figma name
// straight through with no normalization of its own.
//
// Returns Some((props, codeComponent)) for anything synced/verified, None
// otherwise -- the caller supplies its own tag prefix/wrapper (e.g.
// "Blend." ++ codeComponent) and any composition
// (FigmaUtils.convertPropsNodeStateVariable-style).
let resolve = (figmaComponentName: string, props: CodeConnectUtils.figmaProps): option<(
  array<option<(string, string)>>,
  string,
)> =>
  switch figmaComponentName {
  | "AvatarGroup" => Some((AvatarGroupCodeConnect.toProps(props), "AvatarGroup"))
  | "Button" | "Buttons" => Some((ButtonCodeConnect.toProps(props), "Button"))
  | "ButtonGroup" => Some((ButtonGroupCodeConnect.toProps(props), "ButtonGroup"))
  | "Charts" => Some((ChartsCodeConnect.toProps(props), "Charts"))
  | "DropdownInput" => Some((DropdownInputCodeConnect.toProps(props), "DropdownInput"))
  | "MultiValueInput" => Some((MultiValueInputCodeConnect.toProps(props), "MultiValueInput"))
  | "NumberInput" => Some((NumberInputCodeConnect.toProps(props), "NumberInput"))
  | "OTPInput" => Some((OTPInputCodeConnect.toProps(props), "OTPInput"))
  | "Popover" => Some((PopoverCodeConnect.toProps(props), "Popover"))
  | "Radio" => Some((RadioCodeConnect.toProps(props), "Radio"))
  | "SearchInput" => Some((SearchInputCodeConnect.toProps(props), "SearchInput"))
  | "SplitTag" => Some((SplitTagCodeConnect.toProps(props), "SplitTag"))
  | "StatCard" => Some((StatCardCodeConnect.toProps(props), "StatCard"))
  | "Tag" => Some((TagCodeConnect.toProps(props), "Tag"))
  | "TextArea" => Some((TextAreaCodeConnect.toProps(props), "TextArea"))
  | "TextInput" => Some((TextInputCodeConnect.toProps(props), "TextInput"))
  | "Tooltip" => Some((TooltipCodeConnect.toProps(props), "Tooltip"))
  | "UnitInput" => Some((UnitInputCodeConnect.toProps(props), "UnitInput"))
  | _ => None
  }
