// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/MultiValueInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.MultiValueInput's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.MultiValueInput for the same reason -- pass
// ~tagName (e.g. "Blend.MultiValueInput") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/MultiValueInput.mjs): value, helpIconHintText, errorMessage.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "md" => Some("JuspayRescriptBlend.InputsTypes.Md")
      | "lg" => Some("JuspayRescriptBlend.InputsTypes.Lg")
      | _ => None
      }
    )
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )
  let disabled =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "disabled" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "error" => Some("false")
      | _ => None
      }
    )

  [
    CodeConnectUtils.propEntry("size", size),
    CodeConnectUtils.strPropEntry("label", label),
    CodeConnectUtils.strPropEntry("sublabel", sublabel),
    CodeConnectUtils.strPropEntry("hintText", hintText),
    CodeConnectUtils.propEntry("error", error),
    CodeConnectUtils.propEntry("disabled", disabled),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.MultiValueInput",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
