// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/NumberInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.NumberInput JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/NumberInput.mjs): errorMessage, helpIconHintText, preventNegative.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "md" => Some("InputsTypes.Md")
      | "lg" => Some("InputsTypes.Lg")
      | _ => None
      }
    )
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )

  "<NumberInput" ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.strAttr("label", label) ++
  CodeConnectUtils.strAttr("sublabel", sublabel) ++
  CodeConnectUtils.strAttr("hintText", hintText) ++
  CodeConnectUtils.attr("error", error) ++ " />"
}
