// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/OTPInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.OTPInput JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/OTPInput.mjs): helpIconHintText, errorMessage, value, autoFocus, form, placeholder.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )

  "<OTPInput" ++
  CodeConnectUtils.strAttr("label", label) ++
  CodeConnectUtils.strAttr("sublabel", sublabel) ++
  CodeConnectUtils.strAttr("hintText", hintText) ++
  CodeConnectUtils.attr("error", error) ++ " />"
}
