// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Popover.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Popover JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Popover.mjs): heading, description, asModal, side, align, size, shadow, useDrawerOnMobile, avoidCollisions.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let showCloseButton = props->CodeConnectUtils.getBoolProp("close")

  "<Popover" ++ CodeConnectUtils.boolAttr("showCloseButton", showCloseButton) ++ " />"
}
