// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Popover.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Popover's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Popover for the same reason -- pass
// ~tagName (e.g. "Blend.Popover") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Popover.mjs): heading, description, asModal, side, align, size, shadow, useDrawerOnMobile, avoidCollisions.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let showCloseButton = props->CodeConnectUtils.getBoolProp("close")

  [CodeConnectUtils.boolPropEntry("showCloseButton", showCloseButton)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Popover",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
