// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Radio.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Radio JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Radio.mjs): id, value, defaultChecked, required, error, name.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("RadioTypes.Sm")
      | "md" => Some("RadioTypes.Md")
      | _ => None
      }
    )
  let checked = props->CodeConnectUtils.getBoolProp("enable")
  let disabled = props->CodeConnectUtils.getBoolProp("disabled")
  let subtext = props->CodeConnectUtils.getStringProp("subtext")

  "<Radio" ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.boolAttr("checked", checked) ++
  CodeConnectUtils.boolAttr("disabled", disabled) ++
  CodeConnectUtils.strAttr("subtext", subtext) ++ " />"
}
