// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Radio.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Radio's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Radio for the same reason -- pass
// ~tagName (e.g. "Blend.Radio") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Radio.mjs): id, value, defaultChecked, required, error, name.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("JuspayRescriptBlend.RadioTypes.Sm")
      | "md" => Some("JuspayRescriptBlend.RadioTypes.Md")
      | _ => None
      }
    )
  let checked = props->CodeConnectUtils.getBoolProp("enable")
  let disabled = props->CodeConnectUtils.getBoolProp("disabled")
  let subtext = props->CodeConnectUtils.getStringProp("subtext")

  [
    CodeConnectUtils.propEntry("size", size),
    CodeConnectUtils.boolPropEntry("checked", checked),
    CodeConnectUtils.boolPropEntry("disabled", disabled),
    CodeConnectUtils.strPropEntry("subtext", subtext),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Radio",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
