// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/SearchInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.SearchInput's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.SearchInput for the same reason -- pass
// ~tagName (e.g. "Blend.SearchInput") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/SearchInput.mjs): allowClear, clearIcon.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let value = props->CodeConnectUtils.getStringProp("placeholder")
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )

  [CodeConnectUtils.strPropEntry("value", value), CodeConnectUtils.propEntry("error", error)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.SearchInput",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
