// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/SearchInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.SearchInput JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/SearchInput.mjs): allowClear, clearIcon.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let value = props->CodeConnectUtils.getStringProp("placeholder")
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )

  "<SearchInput" ++
  CodeConnectUtils.strAttr("value", value) ++
  CodeConnectUtils.attr("error", error) ++ " />"
}
