// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/SplitTag.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.SplitTag JSX text from a Figma
// component-properties array.
let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let shape =
    props
    ->CodeConnectUtils.getStringProp("shape")
    ->Option.flatMap(v =>
      switch v {
      | "rounded" => Some("TagsTypes.Rounded")
      | "squarical" => Some("TagsTypes.Squarical")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "xs" => Some("TagsTypes.Xs")
      | "sm" => Some("TagsTypes.Sm")
      | "md" => Some("TagsTypes.Md")
      | "lg" => Some("TagsTypes.Lg")
      | _ => None
      }
    )

  "<SplitTag" ++
  CodeConnectUtils.attr("shape", shape) ++
  CodeConnectUtils.attr("size", size) ++ " />"
}
