// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/SplitTag.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.SplitTag's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.SplitTag for the same reason -- pass
// ~tagName (e.g. "Blend.SplitTag") to render any other tag/prefix.
let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let shape =
    props
    ->CodeConnectUtils.getStringProp("shape")
    ->Option.flatMap(v =>
      switch v {
      | "rounded" => Some("JuspayRescriptBlend.TagsTypes.Rounded")
      | "squarical" => Some("JuspayRescriptBlend.TagsTypes.Squarical")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "xs" => Some("JuspayRescriptBlend.TagsTypes.Xs")
      | "sm" => Some("JuspayRescriptBlend.TagsTypes.Sm")
      | "md" => Some("JuspayRescriptBlend.TagsTypes.Md")
      | "lg" => Some("JuspayRescriptBlend.TagsTypes.Lg")
      | _ => None
      }
    )

  [CodeConnectUtils.propEntry("shape", shape), CodeConnectUtils.propEntry("size", size)]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.SplitTag",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
