// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/StatCard.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.StatCard's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.StatCard for the same reason -- pass
// ~tagName (e.g. "Blend.StatCard") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/StatCard.mjs): actionIcon, helpIconText, maxWidth, minWidth, valueFormatter, height, direction, dataDisplay, showBorder.
// Not covered (unfilled figmaProp/values, instanceSwap, or otherwise not statically derivable): titleIcon. Splice these in at the call site if needed.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let variant =
    props
    ->CodeConnectUtils.getStringProp("type")
    ->Option.flatMap(v =>
      switch v {
      | "line" => Some("JuspayRescriptBlend.StatCardTypes.Line")
      | "progress" => Some("JuspayRescriptBlend.StatCardTypes.Progress")
      | "bar" => Some("JuspayRescriptBlend.StatCardTypes.Bar")
      | "number" => Some("JuspayRescriptBlend.StatCardTypes.Number")
      | _ => None
      }
    )
  let title = props->CodeConnectUtils.getStringProp("title")
  let subtitle = props->CodeConnectUtils.getStringProp("date")

  [
    CodeConnectUtils.propEntry("variant", variant),
    CodeConnectUtils.strPropEntry("title", title),
    CodeConnectUtils.strPropEntry("subtitle", subtitle),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.StatCard",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
