// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/StatCard.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.StatCard JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/StatCard.mjs): actionIcon, helpIconText, maxWidth, minWidth, valueFormatter, height, direction, dataDisplay, showBorder.
// Not covered (unfilled figmaProp/values, instanceSwap, or otherwise not statically derivable): titleIcon. Splice these in at the call site if needed.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let variant =
    props
    ->CodeConnectUtils.getStringProp("type")
    ->Option.flatMap(v =>
      switch v {
      | "line" => Some("StatCardTypes.Line")
      | "progress" => Some("StatCardTypes.Progress")
      | "bar" => Some("StatCardTypes.Bar")
      | "number" => Some("StatCardTypes.Number")
      | _ => None
      }
    )
  let title = props->CodeConnectUtils.getStringProp("title")
  let subtitle = props->CodeConnectUtils.getStringProp("date")

  "<StatCard" ++
  CodeConnectUtils.attr("variant", variant) ++
  CodeConnectUtils.strAttr("title", title) ++
  CodeConnectUtils.strAttr("subtitle", subtitle) ++ " />"
}
