// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Tag.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Tag's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Tag for the same reason -- pass
// ~tagName (e.g. "Blend.Tag") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Tag.mjs): boxShadow, width, borderRadius, letterSpacing, fontSize, lineHeight, display, fontWeight, opacity, height, gap, zIndex, minWidth, maxWidth, backgroundColor, border, inset, borderBottom, outline, transition, top, left, outlineOffset, maxHeight, bottom, right, flexDirection, position, justifyContent, alignItems, overflowX, overflowY, flexShrink, minHeight, transform, textAlign, cursor, userSelect, textTransform, borderTop, borderTopLeftRadius, borderTopRightRadius, borderBottomLeftRadius, borderBottomRightRadius, borderLeft, borderRight, backgroundSize, backgroundImage, overflow, pointerEvents, textOverflow, whiteSpace, flexWrap, flexGrow, flexBasis, rowGap, columnGap, alignContent, alignSelf, justifySelf, outlineColor, outlineWidth, outlineStyle, contentCentered, willChange, transformOrigin, backfaceVisibility, transitionDuration, transitionTimingFunction, transitionDelay, splitTagPosition, showSkeleton, skeletonVariant.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let text = props->CodeConnectUtils.getStringProp("text")
  let variant =
    props
    ->CodeConnectUtils.getStringProp("variant")
    ->Option.flatMap(v =>
      switch v {
      | "noFill" => Some("JuspayRescriptBlend.TagsTypes.NoFill")
      | "attentive" => Some("JuspayRescriptBlend.TagsTypes.Attentive")
      | "subtle" => Some("JuspayRescriptBlend.TagsTypes.Subtle")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "xs" => Some("JuspayRescriptBlend.TagsTypes.Xs")
      | "sm" => Some("JuspayRescriptBlend.TagsTypes.Sm")
      | "md" => Some("JuspayRescriptBlend.TagsTypes.Md")
      | "lg" => Some("JuspayRescriptBlend.TagsTypes.Lg")
      | _ => None
      }
    )
  let color =
    props
    ->CodeConnectUtils.getStringProp("color")
    ->Option.flatMap(v =>
      switch v {
      | "neutral" => Some("JuspayRescriptBlend.SplitTagTypes.Neutral")
      | "primary" => Some("JuspayRescriptBlend.SplitTagTypes.Primary")
      | "success" => Some("JuspayRescriptBlend.SplitTagTypes.Success")
      | "error" => Some("JuspayRescriptBlend.SplitTagTypes.Error")
      | "warning" => Some("JuspayRescriptBlend.SplitTagTypes.Warning")
      | "purple" => Some("JuspayRescriptBlend.SplitTagTypes.Purple")
      | _ => None
      }
    )
  let shape =
    props
    ->CodeConnectUtils.getStringProp("shape")
    ->Option.flatMap(v =>
      switch v {
      | "rounded" => Some("JuspayRescriptBlend.TagsTypes.Rounded")
      | "squarical" => Some("JuspayRescriptBlend.TagsTypes.Squarical")
      | _ => None
      }
    )

  [
    CodeConnectUtils.strPropEntry("text", text),
    CodeConnectUtils.propEntry("variant", variant),
    CodeConnectUtils.propEntry("size", size),
    CodeConnectUtils.propEntry("color", color),
    CodeConnectUtils.propEntry("shape", shape),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Tag",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
