// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Tag.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Tag JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Tag.mjs): boxShadow, width, borderRadius, letterSpacing, fontSize, lineHeight, display, fontWeight, opacity, height, gap, zIndex, minWidth, maxWidth, backgroundColor, border, inset, borderBottom, outline, transition, top, left, outlineOffset, maxHeight, bottom, right, flexDirection, position, justifyContent, alignItems, overflowX, overflowY, flexShrink, minHeight, transform, textAlign, cursor, userSelect, textTransform, borderTop, borderTopLeftRadius, borderTopRightRadius, borderBottomLeftRadius, borderBottomRightRadius, borderLeft, borderRight, backgroundSize, backgroundImage, overflow, pointerEvents, textOverflow, whiteSpace, flexWrap, flexGrow, flexBasis, rowGap, columnGap, alignContent, alignSelf, justifySelf, outlineColor, outlineWidth, outlineStyle, contentCentered, willChange, transformOrigin, backfaceVisibility, transitionDuration, transitionTimingFunction, transitionDelay, splitTagPosition, showSkeleton, skeletonVariant.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let text = props->CodeConnectUtils.getStringProp("text")
  let variant =
    props
    ->CodeConnectUtils.getStringProp("variant")
    ->Option.flatMap(v =>
      switch v {
      | "noFill" => Some("TagsTypes.NoFill")
      | "attentive" => Some("TagsTypes.Attentive")
      | "subtle" => Some("TagsTypes.Subtle")
      | _ => None
      }
    )
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "xs" => Some("TagsTypes.Xs")
      | "sm" => Some("TagsTypes.Sm")
      | "md" => Some("TagsTypes.Md")
      | "lg" => Some("TagsTypes.Lg")
      | _ => None
      }
    )
  let color =
    props
    ->CodeConnectUtils.getStringProp("color")
    ->Option.flatMap(v =>
      switch v {
      | "neutral" => Some("SplitTagTypes.Neutral")
      | "primary" => Some("SplitTagTypes.Primary")
      | "success" => Some("SplitTagTypes.Success")
      | "error" => Some("SplitTagTypes.Error")
      | "warning" => Some("SplitTagTypes.Warning")
      | "purple" => Some("SplitTagTypes.Purple")
      | _ => None
      }
    )
  let shape =
    props
    ->CodeConnectUtils.getStringProp("shape")
    ->Option.flatMap(v =>
      switch v {
      | "rounded" => Some("TagsTypes.Rounded")
      | "squarical" => Some("TagsTypes.Squarical")
      | _ => None
      }
    )

  "<Tag" ++
  CodeConnectUtils.strAttr("text", text) ++
  CodeConnectUtils.attr("variant", variant) ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.attr("color", color) ++
  CodeConnectUtils.attr("shape", shape) ++ " />"
}
