// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/TextArea.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.TextArea JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/TextArea.mjs): value, autoFocus, helpIconHintText, helpIconText, errorMessage, resize, wrap.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let placeholder = props->CodeConnectUtils.getStringProp("placeholder")
  let disabled =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "disabled" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "error" => Some("false")
      | _ => None
      }
    )
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )
  let required = props->CodeConnectUtils.getBoolProp("mandatory")

  "<TextArea" ++
  CodeConnectUtils.strAttr("label", label) ++
  CodeConnectUtils.strAttr("sublabel", sublabel) ++
  CodeConnectUtils.strAttr("hintText", hintText) ++
  CodeConnectUtils.strAttr("placeholder", placeholder) ++
  CodeConnectUtils.attr("disabled", disabled) ++
  CodeConnectUtils.attr("error", error) ++
  CodeConnectUtils.boolAttr("required", required) ++ " />"
}
