// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/TextArea.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.TextArea's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.TextArea for the same reason -- pass
// ~tagName (e.g. "Blend.TextArea") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/TextArea.mjs): value, autoFocus, helpIconHintText, helpIconText, errorMessage, resize, wrap.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let placeholder = props->CodeConnectUtils.getStringProp("placeholder")
  let disabled =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "disabled" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "error" => Some("false")
      | _ => None
      }
    )
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )
  let required = props->CodeConnectUtils.getBoolProp("mandatory")

  [
    CodeConnectUtils.strPropEntry("label", label),
    CodeConnectUtils.strPropEntry("sublabel", sublabel),
    CodeConnectUtils.strPropEntry("hintText", hintText),
    CodeConnectUtils.strPropEntry("placeholder", placeholder),
    CodeConnectUtils.propEntry("disabled", disabled),
    CodeConnectUtils.propEntry("error", error),
    CodeConnectUtils.boolPropEntry("required", required),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.TextArea",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
