// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Tooltip.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.Tooltip JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/Tooltip.mjs): side, align, showArrow, maxWidth, fullWidth, disableInteractive.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("TooltipTypes.Sm")
      | _ => None
      }
    )
  let slotDirection =
    props
    ->CodeConnectUtils.getStringProp("slotDirection")
    ->Option.flatMap(v =>
      switch v {
      | "left" => Some("TooltipTypes.Left")
      | "right" => Some("TooltipTypes.Right")
      | _ => None
      }
    )

  "<Tooltip" ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.attr("slotDirection", slotDirection) ++ " />"
}
