// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/Tooltip.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// toProps derives JuspayRescriptBlend.Tooltip's props from a Figma
// component-properties array, as array<option<(propName, propValueText)>> --
// own your own tag name/wrapper/state composition with it (e.g.
// FigmaUtils.convertPropsNodeStateVariable-style). Enum values are fully
// qualified (JuspayRescriptBlend.<Module>.<Constructor>), so they compile
// regardless of what's `open` in the caller's file -- no import assumed.
// fromFigmaProps is a thin wrapper over toProps for callers that just want
// a finished snippet; defaults the tag to the fully-qualified
// JuspayRescriptBlend.Tooltip for the same reason -- pass
// ~tagName (e.g. "Blend.Tooltip") to render any other tag/prefix.
// Deliberately not mapped (see figma/componentMaps/Tooltip.mjs): side, align, showArrow, maxWidth, fullWidth, disableInteractive.

let toProps = (props: CodeConnectUtils.figmaProps): array<option<(string, string)>> => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "sm" => Some("JuspayRescriptBlend.TooltipTypes.Sm")
      | _ => None
      }
    )
  let slotDirection =
    props
    ->CodeConnectUtils.getStringProp("slotDirection")
    ->Option.flatMap(v =>
      switch v {
      | "left" => Some("JuspayRescriptBlend.TooltipTypes.Left")
      | "right" => Some("JuspayRescriptBlend.TooltipTypes.Right")
      | _ => None
      }
    )

  [
    CodeConnectUtils.propEntry("size", size),
    CodeConnectUtils.propEntry("slotDirection", slotDirection),
  ]
}

let fromFigmaProps = (
  props: CodeConnectUtils.figmaProps,
  ~tagName: string="JuspayRescriptBlend.Tooltip",
): string => CodeConnectUtils.joinTag(tagName, toProps(props))
