// GENERATED by scripts/generate-figma-code-connect.mjs from figma/componentMaps/UnitInput.mjs.
// Do not edit by hand -- edit the source map and re-run `npm run figma:generate`.
//
// Renders RescriptBlend.UnitInput JSX text from a Figma
// component-properties array.
// Deliberately not mapped (see figma/componentMaps/UnitInput.mjs): errorMessage, helpIconHintText.

let fromFigmaProps = (props: CodeConnectUtils.figmaProps): string => {
  let size =
    props
    ->CodeConnectUtils.getStringProp("size")
    ->Option.flatMap(v =>
      switch v {
      | "md" => Some("InputsTypes.Md")
      | "lg" => Some("InputsTypes.Lg")
      | _ => None
      }
    )
  let label = props->CodeConnectUtils.getStringProp("label")
  let sublabel = props->CodeConnectUtils.getStringProp("sublabel")
  let hintText = props->CodeConnectUtils.getStringProp("hintText")
  let unit = props->CodeConnectUtils.getStringProp("unitText")
  let unitPosition =
    props
    ->CodeConnectUtils.getStringProp("unitPosition")
    ->Option.flatMap(v =>
      switch v {
      | "left" => Some("InputsTypes.Left")
      | "right" => Some("InputsTypes.Right")
      | _ => None
      }
    )
  let error =
    props
    ->CodeConnectUtils.getStringProp("state")
    ->Option.flatMap(v =>
      switch v {
      | "error" => Some("true")
      | "default" => Some("false")
      | "hover" => Some("false")
      | "active" => Some("false")
      | "focussed" => Some("false")
      | "disabled" => Some("false")
      | _ => None
      }
    )
  let required = props->CodeConnectUtils.getBoolProp("mandatory")

  "<UnitInput" ++
  CodeConnectUtils.attr("size", size) ++
  CodeConnectUtils.strAttr("label", label) ++
  CodeConnectUtils.strAttr("sublabel", sublabel) ++
  CodeConnectUtils.strAttr("hintText", hintText) ++
  CodeConnectUtils.strAttr("unit", unit) ++
  CodeConnectUtils.attr("unitPosition", unitPosition) ++
  CodeConnectUtils.attr("error", error) ++
  CodeConnectUtils.boolAttr("required", required) ++ " />"
}
