// Generated by ReScript, PLEASE EDIT WITH CARE


function makeAvatarData(id, src, alt, fallback, size, shape, online, leadingSlot, trailingSlot, param) {
  return {
    id: id,
    src: src,
    alt: alt,
    fallback: fallback,
    size: size,
    shape: shape,
    online: online,
    leadingSlot: leadingSlot,
    trailingSlot: trailingSlot
  };
}

export {
  makeAvatarData,
}
/* No side effect */
