// Generated by ReScript, PLEASE EDIT WITH CARE


function makeItem(label, href, leftSlot, rightSlot, onClick, isActive, param) {
  return {
    label: label,
    href: href,
    leftSlot: leftSlot,
    rightSlot: rightSlot,
    onClick: onClick,
    isActive: isActive
  };
}

export {
  makeItem,
}
/* No side effect */
