// Generated by ReScript, PLEASE EDIT WITH CARE


let ChartLegends = {};

let CustomTooltip = {};

let ChartHeader = {};

export {
  ChartLegends,
  CustomTooltip,
  ChartHeader,
}
/* No side effect */
