// Generated by ReScript, PLEASE EDIT WITH CARE


function makeDiffLine(content, type_) {
  return {
    content: content,
    type: type_
  };
}

let CodeBlockVariant = {
  $$default: "default",
  noGutter: "no-gutter",
  diff: "diff"
};

let DiffLineType = {
  added: "added",
  removed: "removed",
  unchanged: "unchanged"
};

export {
  makeDiffLine,
  CodeBlockVariant,
  DiffLineType,
}
/* No side effect */
