// Generated by ReScript, PLEASE EDIT WITH CARE


let ColumnType = {};

function toString(direction) {
  switch (direction) {
    case "asc" :
      return "asc";
    case "desc" :
      return "desc";
    case "none" :
      return "none";
  }
}

let SortDirection = {
  toString: toString
};

let FilterType = {};

function makeColumnDefinition(field, header, type_, headerSubtext, width, minWidth, maxWidth, isSortable, isVisible, canHide, frozen, isEditable, isFilterable, filterType, filterOptions, className, renderCell, renderEditCell, sliderConfig, param) {
  return {
    field: field,
    header: header,
    headerSubtext: headerSubtext,
    type: type_,
    width: width,
    minWidth: minWidth,
    maxWidth: maxWidth,
    isSortable: isSortable,
    isVisible: isVisible,
    canHide: canHide,
    frozen: frozen,
    isEditable: isEditable,
    isFilterable: isFilterable,
    filterType: filterType,
    filterOptions: filterOptions,
    sliderConfig: sliderConfig,
    className: className,
    renderCell: renderCell,
    renderEditCell: renderEditCell
  };
}

function makeFilterOption(id, label, value, options, param) {
  return {
    id: id,
    label: label,
    value: value,
    options: options
  };
}

function makePaginationConfig(currentPage, pageSize, totalRows, pageSizeOptions, onPageChange, onPageSizeChange, param) {
  return {
    currentPage: currentPage,
    pageSize: pageSize,
    totalRows: totalRows,
    pageSizeOptions: pageSizeOptions,
    onPageChange: onPageChange,
    onPageSizeChange: onPageSizeChange
  };
}

function makeSortConfig(field, direction) {
  return {
    field: field,
    direction: direction
  };
}

function makeSearchConfig(query, searchFields, caseSensitive, param) {
  return {
    query: query,
    searchFields: searchFields,
    caseSensitive: caseSensitive
  };
}

function makeAvatarData(label, sublabel, imageUrl, param) {
  return {
    label: label,
    sublabel: sublabel,
    imageUrl: imageUrl
  };
}

function makeTagData(text, color, variant) {
  return {
    text: text,
    color: color,
    variant: variant
  };
}

function makeBulkActionItem(id, label, variant, onClick) {
  return {
    id: id,
    label: label,
    variant: variant,
    onClick: onClick
  };
}

function makeBulkActionsConfig(showSelectAll, showDeselectAll, onSelectAll, onDeselectAll, customActions, showExport, param) {
  return {
    showSelectAll: showSelectAll,
    showDeselectAll: showDeselectAll,
    onSelectAll: onSelectAll,
    onDeselectAll: onDeselectAll,
    customActions: customActions,
    showExport: showExport
  };
}

export {
  ColumnType,
  SortDirection,
  FilterType,
  makeColumnDefinition,
  makeFilterOption,
  makePaginationConfig,
  makeSortConfig,
  makeSearchConfig,
  makeAvatarData,
  makeTagData,
  makeBulkActionItem,
  makeBulkActionsConfig,
}
/* No side effect */
