// #190: compatibility re-exports — these identities moved to another module when a
// dependency cycle merged this home. Old `DirectoryTypes.<name>` annotations keep resolving.
type responsiveDirectoryTokens = HighchartsSharedSharedTypes.responsiveDirectoryTokens
type directoryTokenType = HighchartsSharedSharedTypes.directoryTokenType
type directoryDirectoryTokenTypeSectionConfig = HighchartsSharedSharedTypes.directoryDirectoryTokenTypeSectionConfig
type directoryDirectoryTokenTypeSectionHeaderConfig = HighchartsSharedSharedTypes.directoryDirectoryTokenTypeSectionHeaderConfig
type directoryDirectoryTokenTypeSectionItemListConfig = HighchartsSharedSharedTypes.directoryDirectoryTokenTypeSectionItemListConfig
type directoryData = HighchartsSharedSharedTypes.directoryData
type navbarItem = HighchartsSharedSharedTypes.navbarItem
module DirectoryExpandedItems = HighchartsSharedSharedTypes.DirectoryExpandedItems
type directoryVirtualizationConfig = HighchartsSharedSharedTypes.directoryVirtualizationConfig
