// Generated by ReScript, PLEASE EDIT WITH CARE


let Trigger = {};

let Portal = {};

let Overlay = {};

let Content = {};

let Body = {};

let Header = {};

let Title = {};

let Description = {};

let Footer = {};

let Close = {};

let StatusDrawer = {};

let SingleSelectDrawer = {};

function makeSelectDrawerItem(value, label, subLabel, slot1, disabled, param) {
  return {
    value: value,
    label: label,
    subLabel: subLabel,
    slot1: slot1,
    disabled: disabled
  };
}

function makeSelectDrawerGroup(groupLabel, items, showSeparator, param) {
  return {
    groupLabel: groupLabel,
    items: items,
    showSeparator: showSeparator
  };
}

function makeButtonV2Props(buttonType, size, text, onClick, isDisabled, disabled, state, param) {
  return {
    buttonType: buttonType,
    size: size,
    text: text,
    onClick: onClick,
    isDisabled: isDisabled,
    disabled: disabled,
    state: state
  };
}

function makeMobileOffset(top, bottom, left, right, param) {
  return {
    top: top,
    bottom: bottom,
    left: left,
    right: right
  };
}

export {
  Trigger,
  Portal,
  Overlay,
  Content,
  Body,
  Header,
  Title,
  Description,
  Footer,
  Close,
  StatusDrawer,
  SingleSelectDrawer,
  makeSelectDrawerItem,
  makeSelectDrawerGroup,
  makeButtonV2Props,
  makeMobileOffset,
}
/* No side effect */
