// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kriya from "@juspay/kriya";

function createEngine(headlessOpt, defaultTimeoutOpt, screenshotOnErrorOpt, param) {
  let headless = headlessOpt !== undefined ? headlessOpt : false;
  let defaultTimeout = defaultTimeoutOpt !== undefined ? defaultTimeoutOpt : 30000;
  let screenshotOnError = screenshotOnErrorOpt !== undefined ? screenshotOnErrorOpt : true;
  return Kriya.createAutomationEngine({
    headless: headless,
    defaultTimeout: defaultTimeout,
    viewport: {
      width: 1280,
      height: 720
    },
    screenshotOnError: screenshotOnError
  });
}

function executeAction(engine, action) {
  return engine.execute(action);
}

function executeActions(engine, actions) {
  return engine.executeBatch(actions);
}

function destroyEngine(engine) {
  return engine.destroy();
}

export {
  createEngine,
  executeAction,
  executeActions,
  destroyEngine,
}
/* @juspay/kriya Not a pure module */
