// Generated by ReScript, PLEASE EDIT WITH CARE


let Check = {};

let Home = {};

let Folder = {};

let File = {};

let ChevronRight = {};

let Package = {};

let Settings = {};

let User = {};

let Users = {};

let Dashboard = {};

export {
  Check,
  Home,
  Folder,
  File,
  ChevronRight,
  Package,
  Settings,
  User,
  Users,
  Dashboard,
}
/* No side effect */
