type props = {
  drawerOpen: bool,
  setDrawerOpen: bool => unit,
  renderTrigger: unit => React.element,
  showPresets: bool,
  availablePresets: array<EditorSharedTypes.dateRangePreset>,
  activePreset: EditorSharedTypes.dateRangePreset,
  selectedRange?: EditorSharedTypes.dateRange,
  startTime?: string,
  endTime?: string,
  dateFormat: string,
  handlePresetSelect: EditorSharedTypes.dateRangePreset => unit,
  handleStartTimeChange: string => unit,
  handleEndTimeChange: string => unit,
  setSelectedRange: EditorSharedTypes.dateRange => unit,
  setStartDate: string => unit,
  setEndDate: string => unit,
  handleCancel: unit => unit,
  handleApply: unit => unit,
  showCustomDropdownOnly?: bool,
  isDisabled?: bool,
  isApplyDisabled?: bool,
  applyDisabledMessage?: string,
  disableFutureDates?: bool,
  disablePastDates?: bool,
  maxYearOffset?: float,
}

@module("@juspay/blend-design-system")
external make: React.component<props> = "MobileDrawerPresets"
