type props = {
  ...HtmlAttrs.buttonHTMLAttributesOmitClassNameOnSelectSlotStyle,
  label?: string,
  subLabel?: string,
  hintText?: string,
  required?: bool,
  helpIconText?: string,
  placeholder: string,
  size?: SelectV2Types.selectV2Size,
  variant?: SelectV2Types.selectV2Variant,
  items: array<SingleSelectV2Types.singleSelectV2GroupType>,
  selected: string,
  onSelect: string => unit,
  search?: SingleSelectV2Types.selectV2SearchConfig,
  slot?: React.element,
  customTrigger?: React.element,
  @as("open") open_?: bool,
  onOpenChange?: bool => unit,
  usePanelOnMobile?: bool,
  menuPosition?: SingleSelectV2Types.selectV2MenuPosition,
  menuDimensions?: SingleSelectV2Types.selectV2MenuDimensions,
  triggerDimensions?: SingleSelectV2Types.selectV2TriggerDimensions,
  inline?: bool,
  error?: SingleSelectV2Types.selectV2ErrorState,
  enableVirtualization?: bool,
  virtualListItemHeight?: float,
  virtualListOverscan?: float,
  onEndReached?: unit => unit,
  endReachedThreshold?: float,
  hasMore?: bool,
  loadingComponent?: React.element,
  skeleton?: SelectV2Types.selectV2SkeletonProps,
  allowCustomValue?: bool,
  customValueLabel?: string,
  singleSelectGroupPosition?: ButtonV2Types.buttonGroupPosition,
}

@module("@juspay/blend-design-system")
external make: React.component<props> = "MobileSingleSelectV2"
