type props = {
  ...HtmlAttrs.buttonHTMLAttributesOmitClassNameOnChangeSlotStyle,
  selectedValues: array<string>,
  onChange: CommonTypes.stringOrStringArray => unit,
  items?: array<MultiSelectV2Types.multiSelectV2GroupType>,
  label: string,
  subLabel?: string,
  helpIconText?: string,
  required?: bool,
  variant?: SelectV2Types.selectV2Variant,
  selectionTagType?: MultiSelectV2Types.multiSelectV2SelectionTagType,
  slot?: React.element,
  hintText?: string,
  placeholder: string,
  size?: SelectV2Types.selectV2Size,
  search?: SingleSelectV2Types.selectV2SearchConfig,
  enableSelectAll?: bool,
  selectAllText?: string,
  maxSelections?: float,
  customTrigger?: React.element,
  usePanelOnMobile?: bool,
  triggerDimensions?: SingleSelectV2Types.selectV2TriggerDimensions,
  menuDimensions?: SingleSelectV2Types.selectV2MenuDimensions,
  menuPosition?: SingleSelectV2Types.selectV2MenuPosition,
  inline?: bool,
  onOpenChange?: bool => unit,
  error?: SingleSelectV2Types.selectV2ErrorState,
  showActionButtons?: bool,
  primaryAction?: MultiSelectV2Types.multiSelectV2PrimaryActionConfig,
  secondaryAction?: MultiSelectV2Types.multiSelectV2SecondaryActionConfig,
  showItemDividers?: bool,
  showHeaderBorder?: bool,
  enableVirtualization?: bool,
  virtualListItemHeight?: float,
  virtualListOverscan?: float,
  itemsToRender?: float,
  onEndReached?: unit => unit,
  endReachedThreshold?: float,
  hasMore?: bool,
  loadingComponent?: React.element,
  skeleton?: SelectV2Types.selectV2SkeletonProps,
  allowCustomValue?: bool,
  customValueLabel?: string,
  showClearButton?: bool,
  onClearAllClick?: unit => unit,
  multiSelectGroupPosition?: ButtonV2Types.buttonGroupPosition,
}

@module("@juspay/blend-design-system")
external make: React.component<props> = "MobileMultiSelectV2"
