// Generated by ReScript, PLEASE EDIT WITH CARE


function makeButtonAction(text, onClick, isDisabled, buttonType, size, subType, leadingIcon, trailingIcon, loading, disabled, state, fullWidth, className, param) {
  return {
    buttonType: buttonType,
    size: size,
    subType: subType,
    text: text,
    leadingIcon: leadingIcon,
    trailingIcon: trailingIcon,
    isDisabled: isDisabled,
    disabled: disabled,
    state: state,
    onClick: onClick,
    loading: loading,
    fullWidth: fullWidth,
    className: className
  };
}

export {
  makeButtonAction,
}
/* No side effect */
