@module("@juspay/blend-design-system") @react.component
external make: (
  ~items: array<MultiSelectV2Types.multiSelectV2GroupType>,
  ~selected: array<string>,
  ~onSelect: string => unit,
  ~trigger: React.element,
  ~menuDimensions: SingleSelectV2Types.selectV2MenuDimensions=?,
  ~disabled: bool=?,
  ~search: SingleSelectV2Types.selectV2SearchConfig=?,
  ~enableSelectAll: bool=?,
  ~selectAllText: string=?,
  ~onSelectAll: (bool, array<MultiSelectV2Types.multiSelectV2GroupType>) => unit=?,
  ~maxSelections: float=?,
  ~menuPosition: SingleSelectV2Types.selectV2MenuPosition=?,
  ~collisionBoundary: SingleSelectV2Types.CollisionBoundary.t=?, // ⓘ was `Element | Element[]` — opaque; build with CollisionBoundary.fromElement / CollisionBoundary.fromElements
  @as("open") ~open_: bool=?,
  ~onOpenChange: bool => unit=?,
  ~showActionButtons: bool=?,
  ~primaryAction: MultiSelectV2Types.multiSelectV2PrimaryActionConfig=?,
  ~secondaryAction: MultiSelectV2Types.multiSelectV2SecondaryActionConfig=?,
  ~enableVirtualization: bool=?,
  ~virtualListItemHeight: float=?,
  ~virtualListOverscan: float=?,
  ~onEndReached: unit => unit=?,
  ~endReachedThreshold: float=?,
  ~hasMore: bool=?,
  ~loadingComponent: React.element=?,
  ~skeleton: SelectV2Types.selectV2SkeletonProps=?,
  ~size: SelectV2Types.selectV2Size=?,
  ~variant: SelectV2Types.selectV2Variant=?,
  ~allowCustomValue: bool=?,
  ~customValueLabel: string=?,
  ~menuId: string=?,
) => React.element = "MultiSelectV2Menu"
