type props = {
  items: array<MultiSelectV2Types.multiSelectV2GroupType2>,
  selected: array<string>,
  onSelect: string => unit,
  trigger: React.element,
  menuDimensions?: HighchartsSharedSharedTypes.selectV2MenuDimensions,
  disabled?: bool,
  search?: HighchartsSharedSharedTypes.selectV2SearchConfig,
  enableSelectAll?: bool,
  selectAllText?: string,
  onSelectAll?: (bool, array<MultiSelectV2Types.multiSelectV2GroupType2>) => unit,
  maxSelections?: float,
  menuPosition?: HighchartsSharedSharedTypes.selectV2MenuPosition,
  collisionBoundary?: ChatInputTypes.ChatInputOverflowMenuPropsCollisonBoundaryRef.t, // ⓘ was `Element | Element[]` — opaque; build with ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElement / ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElements
  @as("open") open_?: bool,
  onOpenChange?: bool => unit,
  showActionButtons?: bool,
  primaryAction?: HighchartsSharedSharedTypes.multiSelectV2PrimaryActionConfig,
  secondaryAction?: HighchartsSharedSharedTypes.multiSelectV2SecondaryActionConfig,
  enableVirtualization?: bool,
  virtualListItemHeight?: float,
  virtualListOverscan?: float,
  onEndReached?: unit => unit,
  endReachedThreshold?: float,
  hasMore?: bool,
  loadingComponent?: React.element,
  skeleton?: SelectV2Types.selectV2SkeletonProps,
  size?: SelectV2Types.selectV2Size2,
  variant?: SelectV2Types.selectV2Variant2,
  allowCustomValue?: bool,
  customValueLabel?: string,
  menuId?: string,
  menuFooter?: React.element,
}

@module("@juspay/blend-design-system")
external make: React.component<props> = "MultiSelectV2Menu"
