type multiSelectV2SelectionTagType2 =
  | @as("count") Count
  | @as("text") Text
type rec multiSelectV2ItemType2 = {
  label: string,
  value: string,
  checked?: bool,
  subLabel?: string,
  slot1?: React.element,
  slot2?: React.element,
  slot3?: React.element,
  slot4?: React.element,
  disabled?: bool,
  onClick?: unit => unit,
  tooltip?: React.element,
  tooltipProps?: SelectV2Types.selectV2TooltipProps,
  disableTruncation?: bool,
  alwaysSelected?: bool,
  subMenu?: array<multiSelectV2ItemType2>,
}
type multiSelectV2GroupType2 = {
  groupLabel?: string,
  items: array<multiSelectV2ItemType2>,
  showSeparator?: bool,
}
type multiSelectBaseProps = {
  selectedValues: array<string>,
  onSelectionChange?: array<string> => unit,
  items?: array<multiSelectV2GroupType2>,
  label: string,
  subLabel?: string,
  helpIconText?: string,
  required?: bool,
  variant?: SelectV2Types.selectV2Variant2,
  selectionTagType?: multiSelectV2SelectionTagType2,
  hintText?: string,
  placeholder: string,
  size?: SelectV2Types.selectV2Size2,
  enableSelectAll?: bool,
  selectAllText?: string,
  maxSelections?: float,
  inline?: bool,
  onOpenChange?: bool => unit,
  error?: SelectV2Types.selectV2ErrorState2,
  showActionButtons?: bool,
  primaryAction?: HighchartsSharedSharedTypes.multiSelectV2PrimaryActionConfig,
  secondaryAction?: HighchartsSharedSharedTypes.multiSelectV2SecondaryActionConfig,
  showItemDividers?: bool,
  showHeaderBorder?: bool,
  onEndReached?: unit => unit,
  endReachedThreshold?: float,
  hasMore?: bool,
  allowCustomValue?: bool,
  customValueLabel?: string,
  showClearButton?: bool,
  onClearAllClick?: unit => unit,
}
type flattenedMultiSelectV2Item2 = {
  id: string,
  @as("type") type_: HighchartsSharedSharedTypes.multiSelectV2FlattenedMultiSelectV2ItemType,
  item?: multiSelectV2ItemType2,
  label?: string,
  groupId?: float,
}
