@module("@juspay/blend-design-system") @react.component
external make: (
  @as("open") ~open_: bool=?,
  ~rightSlot: React.element=?,
  ~heading: string,
  ~className: string=?,
  ~style: JsxDOM.style=?,
  ~items: array<DrawerTypes.selectDrawerGroup>,
  ~enableSearch: bool=?,
  ~searchPlaceholder: string=?,
  ~onOpenChange: bool => unit=?,
  ~description: string=?,
  ~selectedValues: array<string>=?,
  ~onSelectionChange: array<string> => unit=?,
  ~cancelText: string=?,
  ~confirmText: string=?,
  ~onCancel: unit => unit=?,
  ~onConfirm: unit => unit=?,
  ~showCancelButton: bool=?,
  ~direction: DrawerTypes.drawerDirection=?,
  ~modal: bool=?,
  ~dismissible: bool=?,
  ~mobileOffset: DrawerTypes.drawerMobileOffsetConfig=?,
) => React.element = "MultiSelectDrawer"
