type reactPrimaryActionButtonPropsConfig = {
  ...JsxDOM.domProps,
}
module ElementType = {
  type t
  external fromTag: [
    | #symbol
    | #object
    | #text
    | #small
    | #slot
    | #center
    | #ruby
    | #table
    | #search
    | #big
    | #link
    | #sub
    | #sup
    | #progress
    | #textarea
    | #map
    | #filter
    | #body
    | #base
    | #code
    | #style
    | #title
    | #article
    | #button
    | #dialog
    | #figure
    | #form
    | #img
    | #main
    | #menu
    | #menuitem
    | #option
    | #"switch"
    | #time
    | #image
    | #animate
    | #html
    | #select
    | #data
    | #label
    | #a
    | #div
    | #h2
    | #h3
    | #input
    | #li
    | #nav
    | #ol
    | #p
    | #span
    | #svg
    | #ul
    | #abbr
    | #address
    | #area
    | #aside
    | #audio
    | #b
    | #bdi
    | #bdo
    | #blockquote
    | #br
    | #canvas
    | #caption
    | #cite
    | #col
    | #colgroup
    | #datalist
    | #dd
    | #del
    | #details
    | #dfn
    | #dl
    | #dt
    | #em
    | #embed
    | #fieldset
    | #figcaption
    | #footer
    | #h1
    | #h4
    | #h5
    | #h6
    | #head
    | #header
    | #hgroup
    | #hr
    | #i
    | #iframe
    | #ins
    | #kbd
    | #keygen
    | #legend
    | #mark
    | #meta
    | #meter
    | #noindex
    | #noscript
    | #optgroup
    | #output
    | #param
    | #picture
    | #pre
    | #q
    | #rp
    | #rt
    | #s
    | #samp
    | #script
    | #section
    | #source
    | #strong
    | #summary
    | #template
    | #tbody
    | #td
    | #tfoot
    | #th
    | #thead
    | #tr
    | #track
    | #u
    | #var
    | #video
    | #wbr
    | #webview
    | #animateMotion
    | #animateTransform
    | #circle
    | #clipPath
    | #defs
    | #desc
    | #ellipse
    | #feBlend
    | #feColorMatrix
    | #feComponentTransfer
    | #feComposite
    | #feConvolveMatrix
    | #feDiffuseLighting
    | #feDisplacementMap
    | #feDistantLight
    | #feDropShadow
    | #feFlood
    | #feFuncA
    | #feFuncB
    | #feFuncG
    | #feFuncR
    | #feGaussianBlur
    | #feImage
    | #feMerge
    | #feMergeNode
    | #feMorphology
    | #feOffset
    | #fePointLight
    | #feSpecularLighting
    | #feSpotLight
    | #feTile
    | #feTurbulence
    | #foreignObject
    | #g
    | #line
    | #linearGradient
    | #marker
    | #mask
    | #metadata
    | #mpath
    | #path
    | #pattern
    | #polygon
    | #polyline
    | #radialGradient
    | #rect
    | #set
    | #stop
    | #textPath
    | #tspan
    | #use
    | #view
  ] => t = "%identity"
  external fromComponentClass: React.component<'a> => t = "%identity"
  external fromFunctionComponent: React.component<'a> => t = "%identity"
}
