type props<'a> = {
  ref?: React.ref<Nullable.t<Dom.element>>,
  showLeftPanel?: bool,
  children: React.element,
  data: array<EditorSharedTypes.directoryData>,
  leftPanel?: SharedTypes.leftPanelInfo,
  topbar: React.element,
  footer?: React.element,
  sidebarTopSlot?: React.element,
  sidebarCollapseKey?: string,
  merchantInfo?: SharedTypes.merchantInfo,
  rightActions?: React.element,
  enableTopbarAutoHide?: bool,
  isTopbarVisible?: bool,
  onTopbarVisibilityChange?: bool => unit,
  defaultIsTopbarVisible?: bool,
  isExpanded?: bool,
  onExpandedChange?: bool => unit,
  onSidebarStateChange?: EditorSharedTypes.sidebarStateChangeType => unit,
  defaultIsExpanded?: bool,
  panelOnlyMode?: bool,
  disableIntermediateState?: bool,
  iconOnlyMode?: bool,
  hideOnIconOnlyToggle?: bool,
  showPrimaryActionButton?: bool,
  primaryActionButtonProps?: ReactTypes.reactSidebarPropsPrimaryActionButtonPropsConfig,
  activeItem?: string,
  onActiveItemChange?: Nullable.t<string> => unit,
  defaultActiveItem?: string,
  onHoveringChange?: bool => unit,
  showHierarchyLines?: bool,
  hierarchyLineBorderRadius?: string,
  expandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  defaultExpandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  onExpandedItemsChange?: array<string> => unit,
  onItemExpand?: (EditorSharedTypes.navbarItem, string) => 'a,
  enableVirtualization?: bool,
  virtualization?: EditorSharedTypes.directoryVirtualizationConfig,
}

@module("@juspay/blend-design-system")
external make: React.component<props<'a>> = "Sidebar"
