// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function makeTenantInfo(label, icon, id) {
  return {
    label: label,
    icon: icon,
    id: Belt_Option.getWithDefault(id, "")
  };
}

function makeMerchantInfo(label, icon, id) {
  return {
    label: label,
    icon: icon,
    id: Belt_Option.getWithDefault(id, "")
  };
}

function makeSidebarNavItem(label, leftSlot, rightSlot, onClick) {
  return {
    label: label,
    leftSlot: Belt_Option.getWithDefault(leftSlot, null),
    rightSlot: Belt_Option.getWithDefault(rightSlot, null),
    onClick: Belt_Option.getWithDefault(onClick, () => {})
  };
}

function makeDirectoryData(label, items, isCollapsible, defaultOpen) {
  return {
    label: Belt_Option.getWithDefault(label, ""),
    items: Belt_Option.getWithDefault(items, []),
    isCollapsible: Belt_Option.getWithDefault(isCollapsible, false),
    defaultOpen: Belt_Option.getWithDefault(defaultOpen, false)
  };
}

function tenantInfoToLeftPanelItem(tenant) {
  return {
    label: tenant.label,
    icon: tenant.icon,
    value: Belt_Option.getWithDefault(tenant.id, tenant.label)
  };
}

function makeLeftPanelFromTenants(tenants, selected, onSelect) {
  return {
    items: tenants.map(tenantInfoToLeftPanelItem),
    selected: selected,
    onSelect: onSelect
  };
}

export {
  makeTenantInfo,
  makeMerchantInfo,
  makeSidebarNavItem,
  makeDirectoryData,
  tenantInfoToLeftPanelItem,
  makeLeftPanelFromTenants,
}
/* No side effect */
