type props<'a> = {
  sidebarTopSlot?: React.element,
  merchantInfo?: EditorSharedTypes.sidebarV2MerchantInfoConfig,
  isExpanded: bool,
  isScrolled: bool,
  sidebarCollapseKey: string,
  onToggle: unit => unit,
  sidebarNavId?: string,
  data: Nullable.t<array<EditorSharedTypes.directoryData>>,
  idPrefix: string,
  activeItem?: Nullable.t<string>,
  onActiveItemChange?: Nullable.t<string> => unit,
  defaultActiveItem?: Nullable.t<string>,
  iconOnlyMode?: bool,
  hideToggleButton?: bool,
  footer?: React.element,
  setIsHovering?: bool => unit,
  sidebarState?: EditorSharedTypes.sidebarV2SidebarV2PropsOnSidebarStateChange,
  tokens: EditorSharedTypes.sidebarV2TokensType,
  showHierarchyLines?: bool,
  hierarchyLineBorderRadius?: string,
  expandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  defaultExpandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  onExpandedItemsChange?: array<string> => unit,
  onItemExpand?: (EditorSharedTypes.navbarItem, string) => 'a,
  enableVirtualization?: bool,
  virtualization?: EditorSharedTypes.directoryVirtualizationConfig,
}

@module("@juspay/blend-design-system")
external make: React.component<props<'a>> = "SidebarV2Panel"
