type props<'a> = {
  ref?: React.ref<Nullable.t<Dom.element>>,
  height?: string,
  children?: React.element,
  data?: array<EditorSharedTypes.directoryData>,
  secondarySidebar?: EditorSharedTypes.secondarySidebarInfo,
  topbar?: React.element,
  footer?: React.element,
  sidebarTopSlot?: React.element,
  sidebarCollapseKey?: string,
  merchantInfo?: SharedTypes.merchantInfo,
  rightActions?: React.element,
  enableTopbarAutoHide?: bool,
  isTopbarVisible?: bool,
  onTopbarVisibilityChange?: bool => unit,
  defaultIsTopbarVisible?: bool,
  isExpanded?: bool,
  onExpandedChange?: bool => unit,
  onSidebarStateChange?: EditorSharedTypes.sidebarV2SidebarV2PropsOnSidebarStateChange => unit,
  defaultIsExpanded?: bool,
  showMobilePrimaryActionButton?: bool,
  mobilePrimaryActionButtonProps?: ReactTypes.reactSidebarPropsPrimaryActionButtonPropsConfig,
  activeItem?: string,
  onActiveItemChange?: Nullable.t<string> => unit,
  defaultActiveItem?: string,
  showHierarchyLines?: bool,
  hierarchyLineBorderRadius?: string,
  expandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  defaultExpandedItems?: EditorSharedTypes.DirectoryExpandedItems.t,
  onExpandedItemsChange?: array<string> => unit,
  onItemExpand?: (EditorSharedTypes.navbarItem, string) => 'a,
  enableVirtualization?: bool,
  virtualization?: EditorSharedTypes.directoryVirtualizationConfig,
}

@module("@juspay/blend-design-system")
external make: React.component<props<'a>> = "SidebarV2"
