@module("@juspay/blend-design-system") @react.component
external make: (
  ~height: string=?,
  ~children: React.element=?,
  ~data: Nullable.t<array<DirectoryTypes.directoryData>>=?,
  ~secondarySidebar: SidebarV2Types.secondarySidebarInfo=?,
  ~topbar: React.element=?,
  ~footer: React.element=?,
  ~sidebarTopSlot: React.element=?,
  ~sidebarCollapseKey: string=?,
  ~merchantInfo: SharedTypes.merchantInfo=?,
  ~rightActions: React.element=?,
  ~enableTopbarAutoHide: bool=?,
  ~isTopbarVisible: bool=?,
  ~onTopbarVisibilityChange: bool => unit=?,
  ~defaultIsTopbarVisible: bool=?,
  ~isExpanded: bool=?,
  ~onExpandedChange: bool => unit=?,
  ~onSidebarStateChange: SidebarV2Types.onSidebarStateChange => unit=?,
  ~defaultIsExpanded: bool=?,
  ~showMobilePrimaryActionButton: bool=?,
  ~mobilePrimaryActionButtonProps: ReactTypes.reactPrimaryActionButtonPropsConfig=?,
  ~activeItem: Nullable.t<string>=?,
  ~onActiveItemChange: Nullable.t<string> => unit=?,
  ~defaultActiveItem: Nullable.t<string>=?,
) => React.element = "SidebarV2"
