type singleDatePickerProps = {
  value?: Date.t,
  onChange?: option<Date.t> => unit,
  minDate?: Date.t,
  maxDate?: Date.t,
  granularity?: SharedTypes.pickerGranularity,
  disableDates?: Date.t => bool,
  showTime?: bool,
  timeFormat?: HighchartsSharedSharedTypes.dateRangePickerDateFormatConfigTimeFormat,
  showSeconds?: bool,
  timezone?: string,
  dateFormat?: string,
  formatConfig?: HighchartsSharedSharedTypes.dateFormatConfig,
  placeholder?: string,
  disabled?: bool,
  error?: bool,
  errorMessage?: string,
  allowClear?: bool,
  size?: HighchartsSharedSharedTypes.dateRangePickerSize,
  triggerConfig?: HighchartsSharedSharedTypes.triggerConfig,
  popoverConfig?: HighchartsSharedSharedTypes.dateRangePickerPopoverConfig,
}
