@module("@juspay/blend-design-system") @react.component
external make: (
  ~style: JsxDOM.style=?,
  ~className: string=?,
  @as("open") ~open_: bool=?,
  ~description: string=?,
  ~heading: string,
  ~items: array<DrawerTypes.selectDrawerGroup>,
  ~onOpenChange: bool => unit=?,
  ~dismissible: bool=?,
  ~modal: bool=?,
  ~direction: DrawerTypes.drawerDirection=?,
  ~onValueChange: string => unit=?,
  ~rightSlot: React.element=?,
  ~enableSearch: bool=?,
  ~searchPlaceholder: string=?,
  ~selectedValue: string=?,
  ~cancelText: string=?,
  ~confirmText: string=?,
  ~onCancel: unit => unit=?,
  ~onConfirm: unit => unit=?,
  ~showCancelButton: bool=?,
  ~mobileOffset: DrawerTypes.drawerMobileOffsetConfig=?,
) => React.element = "SingleSelectDrawer"
