@module("@juspay/blend-design-system") @react.component
external make: (
  ~items: array<SingleSelectV2Types.singleSelectV2GroupType>,
  ~selected: string,
  ~onSelect: string => unit,
  ~trigger: React.element,
  ~menuDimensions: SingleSelectV2Types.selectV2MenuDimensions=?,
  ~search: SingleSelectV2Types.selectV2SearchConfig=?,
  ~disabled: bool=?,
  ~menuPosition: SingleSelectV2Types.selectV2MenuPosition=?,
  ~collisionBoundary: SingleSelectV2Types.CollisionBoundary.t=?, // ⓘ was `Element | Element[]` — opaque; build with CollisionBoundary.fromElement / CollisionBoundary.fromElements
  @as("open") ~open_: bool,
  ~onOpenChange: bool => unit,
  ~size: SelectV2Types.selectV2Size=?,
  ~variant: SelectV2Types.selectV2Variant=?,
  ~enableVirtualization: bool=?,
  ~virtualListItemHeight: float=?,
  ~virtualListOverscan: float=?,
  ~onEndReached: unit => unit=?,
  ~endReachedThreshold: float=?,
  ~hasMore: bool=?,
  ~loadingComponent: React.element=?,
  ~skeleton: SelectV2Types.selectV2SkeletonProps=?,
  ~allowCustomValue: bool=?,
  ~customValueLabel: string=?,
  ~menuId: string=?,
) => React.element = "SingleSelectV2Menu"
