type singleDatePickerProps = {
  value?: Date.t,
  onChange?: option<Date.t> => unit,
  minDate?: Date.t,
  maxDate?: Date.t,
  granularity?: SharedTypes.pickerGranularity,
  disableDates?: Date.t => bool,
  showTime?: bool,
  timeFormat?: EditorSharedTypes.dateRangePickerDateFormatConfigTimeFormat,
  showSeconds?: bool,
  timezone?: string,
  dateFormat?: string,
  formatConfig?: EditorSharedTypes.dateFormatConfig,
  placeholder?: string,
  disabled?: bool,
  error?: bool,
  errorMessage?: string,
  allowClear?: bool,
  size?: EditorSharedTypes.dateRangePickerSize,
  triggerConfig?: EditorSharedTypes.triggerConfig,
  popoverConfig?: EditorSharedTypes.dateRangePickerPopoverConfig,
}
