// Generated by ReScript, PLEASE EDIT WITH CARE


function makeValueFormatConfig(type_, decimalPlaces, prefix, suffix, showLabels, formatter, param) {
  return {
    type: type_,
    decimalPlaces: decimalPlaces,
    prefix: prefix,
    suffix: suffix,
    showLabels: showLabels,
    formatter: formatter
  };
}

let SliderVariant = {
  primary: "primary",
  secondary: "secondary"
};

let SliderSize = {
  small: "sm",
  medium: "md",
  large: "lg"
};

let SliderValueType = {
  number: "number",
  percentage: "percentage",
  decimal: "decimal"
};

let SliderLabelPosition = {
  top: "top",
  bottom: "bottom",
  inline: "inline"
};

export {
  makeValueFormatConfig,
  SliderVariant,
  SliderSize,
  SliderValueType,
  SliderLabelPosition,
}
/* No side effect */
