// Generated by ReScript, PLEASE EDIT WITH CARE


let Step = {};

function makeStep(id, title, status, disabled, description, icon, substeps, isExpandable, isExpanded, param) {
  return {
    id: id,
    title: title,
    status: status,
    disabled: disabled,
    description: description,
    icon: icon,
    substeps: substeps,
    isExpandable: isExpandable,
    isExpanded: isExpanded
  };
}

function makeSubStep(id, title, status, disabled, param) {
  return {
    id: id,
    title: title,
    status: status,
    disabled: disabled
  };
}

function makeStepperProps(steps, onStepClick, onSubstepClick, clickable, stepperType, param) {
  return {
    steps: steps,
    onStepClick: onStepClick,
    onSubstepClick: onSubstepClick,
    clickable: clickable,
    stepperType: stepperType
  };
}

export {
  Step,
  makeStep,
  makeSubStep,
  makeStepperProps,
}
/* No side effect */
