@module("@juspay/blend-design-system") @react.component
external make: (
  ~hidden: bool=?,
  ~required: bool=?,
  ~disabled: bool=?,
  ~size: SelectorV2Types.selectorV2Size,
  ~checked: HighchartsSharedTypes.boolOrIndeterminate=?,
  ~children: React.element=?,
  ~defaultChecked: HighchartsSharedTypes.boolOrIndeterminate=?,
  ~defaultValue: HighchartsSharedTypes.stringOrNumberOrStringArray=?,
  ~autoFocus: bool=?,
  ~className: string=?,
  ~id: string=?,
  ~tabIndex: int=?,
  ~title: string=?,
  ~role: string=?,
  ~rel: string=?,
  @as("aria-checked") ~ariaChecked: [#"true" | #"false" | #mixed]=?,
  @as("aria-controls") ~ariaControls: string=?,
  @as("aria-current")
  ~ariaCurrent: [#page | #step | #location | #date | #time | #"true" | #"false"]=?,
  @as("aria-describedby") ~ariaDescribedby: string=?,
  @as("aria-disabled") ~ariaDisabled: bool=?,
  @as("aria-expanded") ~ariaExpanded: bool=?,
  @as("aria-haspopup")
  ~ariaHaspopup: [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"]=?,
  @as("aria-hidden") ~ariaHidden: bool=?,
  @as("aria-invalid") ~ariaInvalid: [#grammar | #"false" | #spelling | #"true"]=?,
  @as("aria-label") ~ariaLabel: string=?,
  @as("aria-labelledby") ~ariaLabelledby: string=?,
  @as("aria-live") ~ariaLive: [#off | #polite | #assertive | #rude]=?,
  @as("aria-pressed") ~ariaPressed: [#"true" | #"false" | #mixed]=?,
  @as("aria-required") ~ariaRequired: bool=?,
  @as("aria-selected") ~ariaSelected: bool=?,
  ~onCopy: ReactEvent.Clipboard.t => unit=?,
  ~onCut: ReactEvent.Clipboard.t => unit=?,
  ~onPaste: ReactEvent.Clipboard.t => unit=?,
  ~onFocus: ReactEvent.Focus.t => unit=?,
  ~onBlur: ReactEvent.Focus.t => unit=?,
  ~onChange: ReactEvent.Form.t => unit=?,
  ~onInput: ReactEvent.Form.t => unit=?,
  ~onSubmit: ReactEvent.Form.t => unit=?,
  ~onKeyDown: ReactEvent.Keyboard.t => unit=?,
  ~onKeyPress: ReactEvent.Keyboard.t => unit=?,
  ~onKeyUp: ReactEvent.Keyboard.t => unit=?,
  ~onClick: ReactEvent.Mouse.t => unit=?,
  ~onContextMenu: ReactEvent.Mouse.t => unit=?,
  ~onDoubleClick: ReactEvent.Mouse.t => unit=?,
  ~onDrag: ReactEvent.Mouse.t => unit=?,
  ~onDrop: ReactEvent.Mouse.t => unit=?,
  ~onMouseDown: ReactEvent.Mouse.t => unit=?,
  ~onMouseEnter: ReactEvent.Mouse.t => unit=?,
  ~onMouseLeave: ReactEvent.Mouse.t => unit=?,
  ~onMouseMove: ReactEvent.Mouse.t => unit=?,
  ~onMouseOut: ReactEvent.Mouse.t => unit=?,
  ~onMouseOver: ReactEvent.Mouse.t => unit=?,
  ~onMouseUp: ReactEvent.Mouse.t => unit=?,
  ~onScroll: ReactEvent.UI.t => unit=?,
  ~onWheel: ReactEvent.Wheel.t => unit=?,
  ~form: string=?,
  ~formAction: HighchartsSharedTypes.selectorV2FormAction<'a>=?,
  ~formEncType: string=?,
  ~formMethod: string=?,
  ~formNoValidate: bool=?,
  ~formTarget: string=?,
  ~name: string=?,
  @as("type") ~type_: TabsTypes.tabsType=?,
  ~value: HighchartsSharedTypes.stringOrNumberOrStringArray=?,
  ~theme: JSON.t=?,
  ~asChild: bool=?,
  @as("as") ~as_: string=?, // ⚪ loose — was `void`
  @as("$isDisabled") ~_isDisabled: bool,
  @as("$checked") ~_checked: HighchartsSharedTypes.boolOrIndeterminate,
  @as("$error") ~_error: bool=?,
  ~forwardedAs: string=?, // ⚪ loose — was `void`
  ~onCheckedChange: HighchartsSharedTypes.boolOrIndeterminate => unit=?,
  ~style: DistTypes.SelectorV2Style.t=?, // ⓘ was `CSSProperties | CSSPropertiesWithVars` — opaque; build with SelectorV2Style.fromCSSProperties / SelectorV2Style.fromCSSPropertiesWithVars
  ~ref: React.ref<Nullable.t<Dom.element>>=?,
) => React.element = "StyledCheckboxRoot"
