type props<'a> = {
  width?: CommonTypes.stringOrNumber,
  size: SelectorV2Types.selectorV2Size,
  height?: CommonTypes.stringOrNumber,
  hidden?: bool,
  required?: bool,
  disabled?: bool,
  multiple?: bool,
  checked?: bool,
  children?: React.element,
  defaultChecked?: bool,
  defaultValue?: CommonTypes.stringOrNumberOrStringArray,
  autoFocus?: bool,
  className?: string,
  id?: string,
  tabIndex?: int,
  title?: string,
  role?: string,
  rel?: string,
  @as("aria-checked") ariaChecked?: [#"true" | #"false" | #mixed],
  @as("aria-controls") ariaControls?: string,
  @as("aria-current")
  ariaCurrent?: [#page | #step | #location | #date | #time | #"true" | #"false"],
  @as("aria-describedby") ariaDescribedby?: string,
  @as("aria-disabled") ariaDisabled?: bool,
  @as("aria-expanded") ariaExpanded?: bool,
  @as("aria-haspopup")
  ariaHaspopup?: [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"],
  @as("aria-hidden") ariaHidden?: bool,
  @as("aria-invalid") ariaInvalid?: [#grammar | #"false" | #spelling | #"true"],
  @as("aria-label") ariaLabel?: string,
  @as("aria-labelledby") ariaLabelledby?: string,
  @as("aria-live") ariaLive?: [#off | #polite | #assertive | #rude],
  @as("aria-pressed") ariaPressed?: [#"true" | #"false" | #mixed],
  @as("aria-required") ariaRequired?: bool,
  @as("aria-selected") ariaSelected?: bool,
  onCopy?: ReactEvent.Clipboard.t => unit,
  onCut?: ReactEvent.Clipboard.t => unit,
  onPaste?: ReactEvent.Clipboard.t => unit,
  onFocus?: ReactEvent.Focus.t => unit,
  onBlur?: ReactEvent.Focus.t => unit,
  onChange?: ReactEvent.Form.t => unit,
  onInput?: ReactEvent.Form.t => unit,
  onSubmit?: ReactEvent.Form.t => unit,
  onKeyDown?: ReactEvent.Keyboard.t => unit,
  onKeyPress?: ReactEvent.Keyboard.t => unit,
  onKeyUp?: ReactEvent.Keyboard.t => unit,
  onClick?: ReactEvent.Mouse.t => unit,
  onContextMenu?: ReactEvent.Mouse.t => unit,
  onDoubleClick?: ReactEvent.Mouse.t => unit,
  onDrag?: ReactEvent.Mouse.t => unit,
  onDrop?: ReactEvent.Mouse.t => unit,
  onMouseDown?: ReactEvent.Mouse.t => unit,
  onMouseEnter?: ReactEvent.Mouse.t => unit,
  onMouseLeave?: ReactEvent.Mouse.t => unit,
  onMouseMove?: ReactEvent.Mouse.t => unit,
  onMouseOut?: ReactEvent.Mouse.t => unit,
  onMouseOver?: ReactEvent.Mouse.t => unit,
  onMouseUp?: ReactEvent.Mouse.t => unit,
  onScroll?: ReactEvent.UI.t => unit,
  onWheel?: ReactEvent.Wheel.t => unit,
  src?: string,
  alt?: string,
  form?: string,
  step?: CommonTypes.stringOrNumber,
  formAction?: CommonTypes.selectorV2FormAction<'a>,
  formEncType?: string,
  formMethod?: string,
  formNoValidate?: bool,
  formTarget?: string,
  name?: string,
  @as("type") type_?: ReactTypes.htmlInputTypeAttribute,
  value?: CommonTypes.stringOrNumberOrStringArray,
  max?: CommonTypes.stringOrNumber,
  min?: CommonTypes.stringOrNumber,
  maxLength?: int,
  minLength?: int,
  theme?: JSON.t,
  placeholder?: string,
  readOnly?: bool,
  pattern?: string,
  accept?: string,
  @as("as") as_?: string, // ⚪ loose — was `void`
  @as("$isDisabled") _isDisabled: bool,
  @as("$error") _error?: bool,
  forwardedAs?: string, // ⚪ loose — was `void`
  @as("$isChecked") _isChecked: bool,
  @as("$tokens") _tokens: SelectorV2Types.radioV2TokensType,
  style?: DistTypes.SelectorV2Style.t, // ⓘ was `CSSProperties | CSSPropertiesWithVars` — opaque; build with SelectorV2Style.fromCSSProperties / SelectorV2Style.fromCSSPropertiesWithVars
  ref?: React.ref<Nullable.t<Dom.element>>,
}

@module("@juspay/blend-design-system")
external make: React.component<props<'a>> = "StyledRadioV2Root"
