@module("@juspay/blend-design-system") @react.component
external make: (
  ~minWidth: string=?,
  ~maxWidth: string=?,
  ~width: string=?,
  ~gap: string=?,
  ~backgroundColor: string=?,
  ~borderRadius: string=?,
  ~padding: CommonTypes.stringOrNumber=?,
  ~border: string=?,
  ~hidden: bool=?,
  ~inset: string=?,
  ~color: SplitTagTypes.color4=?,
  ~fontSize: string=?,
  ~fontWeight: string=?,
  ~borderBottom: string=?,
  ~outline: string=?,
  ~boxShadow: string=?,
  ~lineHeight: string=?,
  ~transition: string=?,
  ~height: string=?,
  ~top: string=?,
  ~left: string=?,
  ~outlineOffset: string=?,
  ~marginLeft: CommonTypes.stringOrNumber=?,
  ~paddingTop: CommonTypes.stringOrNumber=?,
  ~paddingRight: CommonTypes.stringOrNumber=?,
  ~paddingBottom: CommonTypes.stringOrNumber=?,
  ~paddingLeft: CommonTypes.stringOrNumber=?,
  ~maxHeight: string=?,
  ~bottom: string=?,
  ~right: string=?,
  ~zIndex: string=?,
  ~margin: CommonTypes.stringOrNumber=?,
  ~marginTop: CommonTypes.stringOrNumber=?,
  ~marginRight: CommonTypes.stringOrNumber=?,
  ~marginBottom: CommonTypes.stringOrNumber=?,
  ~display: string=?,
  ~flexDirection: string=?,
  ~position: string=?,
  ~justifyContent: string=?,
  ~alignItems: string=?,
  ~overflowX: string=?,
  ~overflowY: string=?,
  ~flexShrink: string=?,
  ~minHeight: string=?,
  ~transform: string=?,
  ~textAlign: string=?,
  ~cursor: string=?,
  ~userSelect: string=?,
  ~textTransform: string=?,
  ~borderTop: string=?,
  ~borderTopLeftRadius: string=?,
  ~borderTopRightRadius: string=?,
  ~borderBottomLeftRadius: string=?,
  ~borderBottomRightRadius: string=?,
  ~borderLeft: string=?,
  ~borderRight: string=?,
  ~backgroundSize: string=?,
  ~backgroundImage: string=?,
  ~letterSpacing: string=?,
  ~opacity: string=?,
  ~overflow: string=?,
  ~size: TagsTypes.size2=?,
  ~defaultChecked: bool=?,
  ~defaultValue: CommonTypes.stringOrNumberOrStringArray=?,
  ~autoFocus: bool=?,
  ~className: string=?,
  ~id: string=?,
  ~style: JsxDOM.style=?,
  ~tabIndex: int=?,
  ~title: string=?,
  ~role: string=?,
  ~rel: string=?,
  @as("aria-checked") ~ariaChecked: [#"true" | #"false" | #mixed]=?,
  @as("aria-controls") ~ariaControls: string=?,
  @as("aria-current")
  ~ariaCurrent: [#page | #step | #location | #date | #time | #"true" | #"false"]=?,
  @as("aria-describedby") ~ariaDescribedby: string=?,
  @as("aria-disabled") ~ariaDisabled: bool=?,
  @as("aria-expanded") ~ariaExpanded: bool=?,
  @as("aria-haspopup")
  ~ariaHaspopup: [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"]=?,
  @as("aria-hidden") ~ariaHidden: bool=?,
  @as("aria-invalid") ~ariaInvalid: [#grammar | #"false" | #spelling | #"true"]=?,
  @as("aria-label") ~ariaLabel: string=?,
  @as("aria-labelledby") ~ariaLabelledby: string=?,
  @as("aria-live") ~ariaLive: [#off | #polite | #assertive | #rude]=?,
  @as("aria-pressed") ~ariaPressed: [#"true" | #"false" | #mixed]=?,
  @as("aria-required") ~ariaRequired: bool=?,
  @as("aria-selected") ~ariaSelected: bool=?,
  ~onCopy: ReactEvent.Clipboard.t => unit=?,
  ~onCut: ReactEvent.Clipboard.t => unit=?,
  ~onPaste: ReactEvent.Clipboard.t => unit=?,
  ~onFocus: ReactEvent.Focus.t => unit=?,
  ~onBlur: ReactEvent.Focus.t => unit=?,
  ~onChange: ReactEvent.Form.t => unit=?,
  ~onInput: ReactEvent.Form.t => unit=?,
  ~onSubmit: ReactEvent.Form.t => unit=?,
  ~onKeyDown: ReactEvent.Keyboard.t => unit=?,
  ~onKeyPress: ReactEvent.Keyboard.t => unit=?,
  ~onKeyUp: ReactEvent.Keyboard.t => unit=?,
  ~onClick: ReactEvent.Mouse.t => unit=?,
  ~onContextMenu: ReactEvent.Mouse.t => unit=?,
  ~onDoubleClick: ReactEvent.Mouse.t => unit=?,
  ~onDrag: ReactEvent.Mouse.t => unit=?,
  ~onDrop: ReactEvent.Mouse.t => unit=?,
  ~onMouseDown: ReactEvent.Mouse.t => unit=?,
  ~onMouseEnter: ReactEvent.Mouse.t => unit=?,
  ~onMouseLeave: ReactEvent.Mouse.t => unit=?,
  ~onMouseMove: ReactEvent.Mouse.t => unit=?,
  ~onMouseOut: ReactEvent.Mouse.t => unit=?,
  ~onMouseOver: ReactEvent.Mouse.t => unit=?,
  ~onMouseUp: ReactEvent.Mouse.t => unit=?,
  ~onScroll: ReactEvent.UI.t => unit=?,
  ~onWheel: ReactEvent.Wheel.t => unit=?,
  ~whiteSpace: string=?,
  @as("as") ~as_: SkeletonTypes.as_=?,
  ~_hover: PrimitivesTypes.styledBlockProps=?,
  ~_focus: PrimitivesTypes.styledBlockProps=?,
  ~_active: PrimitivesTypes.styledBlockProps=?,
  ~_disabled: PrimitivesTypes.styledBlockProps=?,
  ~_visited: PrimitivesTypes.styledBlockProps=?,
  ~_focusVisible: PrimitivesTypes.styledBlockProps=?,
  ~pointerEvents: string=?,
  ~paddingX: CommonTypes.stringOrNumber=?,
  ~paddingY: CommonTypes.stringOrNumber=?,
  ~marginX: CommonTypes.stringOrNumber=?,
  ~marginY: CommonTypes.stringOrNumber=?,
  ~flexWrap: string=?,
  ~flexGrow: string=?,
  ~flexBasis: string=?,
  ~rowGap: string=?,
  ~columnGap: string=?,
  ~alignContent: string=?,
  ~alignSelf: string=?,
  ~justifySelf: string=?,
  ~outlineColor: string=?,
  ~outlineWidth: string=?,
  ~outlineStyle: string=?,
  ~contentCentered: bool=?,
  ~textOverflow: string=?,
  ~willChange: string=?,
  ~transformOrigin: string=?,
  ~backfaceVisibility: string=?,
  ~transitionDuration: string=?,
  ~transitionTimingFunction: string=?,
  ~transitionDelay: string=?,
  ~text: string,
  ~variant: TagsTypes.tagVariant=?,
  ~shape: TagsTypes.tagShape=?,
  ~leftSlot: React.element=?,
  ~rightSlot: React.element=?,
  ~splitTagPosition: TagsTypes.splitTagPosition=?,
  ~showSkeleton: bool=?,
  ~skeletonVariant: SkeletonTypes.skeletonVariant=?,
) => React.element = "Tag"
