// #190: compatibility re-exports — these identities moved to another module when a
// dependency cycle merged this home. Old `TopbarV2Types.<name>` annotations keep resolving.
type responsiveTopbarV2Tokens = HighchartsSharedSharedTypes.responsiveTopbarV2Tokens
type topbarV2TokenType = HighchartsSharedSharedTypes.topbarV2TokenType
type topbarV2TopbarV2TokenTypeSeparatorConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeSeparatorConfig
type topbarV2TopbarV2TokenTypeToggleButtonConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeToggleButtonConfig
type topbarV2TopbarV2TokenTypeToggleButtonBackgroundColorConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeToggleButtonBackgroundColorConfig
type topbarV2TopbarV2TokenTypeToggleButtonIconConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeToggleButtonIconConfig
type topbarV2TopbarV2TokenTypeActionButtonConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeActionButtonConfig
type topbarV2TopbarV2TokenTypeTenantIconButtonConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeTenantIconButtonConfig
type topbarV2TopbarV2TokenTypeMerchantSelectTriggerConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeMerchantSelectTriggerConfig
type topbarV2TopbarV2TokenTypeMerchantSelectTriggerTextConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeMerchantSelectTriggerTextConfig
type topbarV2TopbarV2TokenTypeLeftSectionConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeLeftSectionConfig
type topbarV2TopbarV2TokenTypeRightSectionConfig = HighchartsSharedSharedTypes.topbarV2TopbarV2TokenTypeRightSectionConfig
type topbarV2Props = HighchartsSharedSharedTypes.topbarV2Props
type merchantInfoV2 = HighchartsSharedSharedTypes.merchantInfoV2
type topbarV2MerchantInfoV2ItemsConfig = HighchartsSharedSharedTypes.topbarV2MerchantInfoV2ItemsConfig
