// Generated by ReScript, PLEASE EDIT WITH CARE


function makeFileError(code, message) {
  return {
    code: code,
    message: message
  };
}

function makeFileRejection(file, errors) {
  return {
    file: file,
    errors: errors
  };
}

function makeUploadFile(file, progress, status, id, error) {
  return {
    file: file,
    progress: progress,
    status: status,
    id: id,
    error: error
  };
}

function makeUploadedFileWithStatus(file, id, status, error) {
  return {
    file: file,
    id: id,
    status: status,
    error: error
  };
}

function makeUploadProps(multiple, accept, maxSize, maxFiles, disabled, required, label, subLabel, helpIconHintText, children, description, className, errorText, state, uploadingFiles, uploadedFiles, failedFiles, enforceFileTypeConsistency, onDrop, onDropAccepted, onDropRejected, onFileRemove, onReplaceFile, isDragActive, isDragAccept, isDragReject, validator, param) {
  return {
    multiple: multiple,
    accept: accept,
    maxSize: maxSize,
    maxFiles: maxFiles,
    disabled: disabled,
    required: required,
    label: label,
    subLabel: subLabel,
    helpIconHintText: helpIconHintText,
    children: children,
    description: description,
    className: className,
    errorText: errorText,
    state: state,
    uploadingFiles: uploadingFiles,
    uploadedFiles: uploadedFiles,
    failedFiles: failedFiles,
    enforceFileTypeConsistency: enforceFileTypeConsistency,
    onDrop: onDrop,
    onDropAccepted: onDropAccepted,
    onDropRejected: onDropRejected,
    onFileRemove: onFileRemove,
    onReplaceFile: onReplaceFile,
    isDragActive: isDragActive,
    isDragAccept: isDragAccept,
    isDragReject: isDragReject,
    validator: validator
  };
}

let image = ["image/*"];

let pdf = ["application/pdf"];

let document = [
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
];

let spreadsheet = [
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
];

let text = [
  "text/plain",
  "text/csv"
];

let json = ["application/json"];

let xml = [
  "application/xml",
  "text/xml"
];

let FileTypes = {
  image: image,
  pdf: pdf,
  document: document,
  spreadsheet: spreadsheet,
  text: text,
  json: json,
  xml: xml
};

export {
  makeFileError,
  makeFileRejection,
  makeUploadFile,
  makeUploadedFileWithStatus,
  makeUploadProps,
  FileTypes,
}
/* No side effect */
