// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Accordion.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Accordion',
  id: 'accordion',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    accordionType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AccordionTypes.Border', // ReScript: Border (bound value "border")
        // TODO_FIGMA_KEY: 'AccordionTypes.NoBorder', // ReScript: NoBorder (bound value "noBorder")
      },
    },
    // TODO (unsupported): defaultValue -- CommonTypes.stringOrStringArray -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): value -- CommonTypes.stringOrStringArray -- variant has payload(s) or is a record, not a simple enum
    isMultiple: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onValueChange -- CommonTypes.stringOrStringArray => unit -- event handler, code-only
  },
}
