// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/AccordionV2Chevron.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'AccordionV2Chevron',
  id: 'accordionV2Chevron',
  imports: ['open JuspayRescriptBlend'],
  props: {
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    isDisabled: { figmaProp: null /* TODO */, kind: 'bool' },
    position: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AccordionV2Types.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'AccordionV2Types.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): accordionTokens -- AccordionV2Types.accordionV2TokensType -- variant has payload(s) or is a record, not a simple enum
  },
}
