// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/AccordionV2Item.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'AccordionV2Item',
  id: 'accordionV2Item',
  imports: ['open JuspayRescriptBlend'],
  props: {
    value: { figmaProp: null /* TODO */, kind: 'string' },
    title: { figmaProp: null /* TODO */, kind: 'string' },
    subtext: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): subtextSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    isDisabled: { figmaProp: null /* TODO */, kind: 'bool' },
    chevronPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AccordionV2Types.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'AccordionV2Types.Right', // ReScript: Right (bound value "right")
      },
    },
    accordionType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AccordionV2Types.Border', // ReScript: Border (bound value "border")
        // TODO_FIGMA_KEY: 'AccordionV2Types.NoBorder', // ReScript: NoBorder (bound value "noBorder")
      },
    },
    isFirst: { figmaProp: null /* TODO */, kind: 'bool' },
    isLast: { figmaProp: null /* TODO */, kind: 'bool' },
    isIntermediate: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): currentValue -- CommonTypes.stringOrStringArray -- variant has payload(s) or is a record, not a simple enum
  },
}
