// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Alert.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Alert',
  id: 'alert',
  imports: ['open RescriptBlend'],
  props: {
    heading: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AlertTypes.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'AlertTypes.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'AlertTypes.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'AlertTypes.Error', // ReScript: Error (bound value "error")
        // TODO_FIGMA_KEY: 'AlertTypes.Purple', // ReScript: Purple (bound value "purple")
        // TODO_FIGMA_KEY: 'AlertTypes.Orange', // ReScript: Orange (bound value "orange")
        // TODO_FIGMA_KEY: 'AlertTypes.Neutral', // ReScript: Neutral (bound value "neutral")
      },
    },
    style: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AlertTypes.Subtle', // ReScript: Subtle (bound value "subtle")
        // TODO_FIGMA_KEY: 'AlertTypes.NoFill', // ReScript: NoFill (bound value "noFill")
      },
    },
    // TODO (unsupported): primaryAction -- AlertTypes.alertAction -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- AlertTypes.alertAction -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    icon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    actionPlacement: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AlertTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'AlertTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
    width: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
