// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/AlertV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'AlertV2',
  id: 'alertV2',
  imports: ['open RescriptBlend'],
  props: {
    subType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AlertV2Types.Subtle', // ReScript: Subtle (bound value "subtle")
        // TODO_FIGMA_KEY: 'AlertV2Types.NoFill', // ReScript: NoFill (bound value "noFill")
      },
    },
    // TODO (unsupported): slot -- AlertV2Types.alertV2SlotConfig -- variant has payload(s) or is a record, not a simple enum
    heading: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): actions -- AlertV2Types.alertV2Actions -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): closeButton -- AlertV2Types.alertV2CloseButtonConfig -- variant has payload(s) or is a record, not a simple enum
    width: { figmaProp: null /* TODO */, kind: 'string' },
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
