// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/AvatarGroup.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'AvatarGroup',
  id: 'avatarGroup',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): avatars -- array<AvatarGroupTypes.avatarData> -- not confidently classifiable
    // TODO (unsupported): maxCount -- float -- not confidently classifiable
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AvatarTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'AvatarTypes.Regular', // ReScript: Regular (bound value "regular")
        // TODO_FIGMA_KEY: 'AvatarTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'AvatarTypes.Lg', // ReScript: Lg (bound value "lg")
        // TODO_FIGMA_KEY: 'AvatarTypes.Xl', // ReScript: Xl (bound value "xl")
      },
    },
    shape: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AvatarTypes.Circular', // ReScript: Circular (bound value "circular")
        // TODO_FIGMA_KEY: 'AvatarTypes.Rounded', // ReScript: Rounded (bound value "rounded")
      },
    },
    // TODO (unsupported): selectedAvatarIds -- array<CommonTypes.stringOrNumber> -- not confidently classifiable
    // TODO (unsupported): onSelectionChange -- array<CommonTypes.stringOrNumber> => unit -- event handler, code-only
    // TODO (unsupported): skeleton -- AvatarGroupTypes.avatarGroupSkeletonConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
