// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/AvatarV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'AvatarV2',
  id: 'avatarV2',
  imports: ['open RescriptBlend'],
  props: {
    src: { figmaProp: null /* TODO */, kind: 'string' },
    alt: { figmaProp: null /* TODO */, kind: 'string' },
    fallbackText: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AvatarV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'AvatarV2Types.Regular', // ReScript: Regular (bound value "regular")
        // TODO_FIGMA_KEY: 'AvatarV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'AvatarV2Types.Lg', // ReScript: Lg (bound value "lg")
        // TODO_FIGMA_KEY: 'AvatarV2Types.Xl', // ReScript: Xl (bound value "xl")
      },
    },
    shape: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'AvatarV2Types.Circular', // ReScript: Circular (bound value "circular")
        // TODO_FIGMA_KEY: 'AvatarV2Types.Rounded', // ReScript: Rounded (bound value "rounded")
      },
    },
    // TODO (unsupported): status -- AvatarV2Types.avatarV2StatusConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): skeleton -- AvatarV2Types.avatarV2SkeletonConfig -- variant has payload(s) or is a record, not a simple enum
    backgroundColor: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onImageError -- JsError.t => unit -- event handler, code-only
    // TODO (unsupported): onImageLoad -- unit => unit -- event handler, code-only
    width: { figmaProp: null /* TODO */, kind: 'string' },
    height: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
