// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Badge.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Badge',
  id: 'badge',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): count -- int -- not confidently classifiable
    // TODO (unsupported): maxCount -- float -- not confidently classifiable
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'BadgeTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'BadgeTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'BadgeTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    color: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'BadgeTypes.Alert', // ReScript: Alert (bound value "alert")
        // TODO_FIGMA_KEY: 'BadgeTypes.Neutral', // ReScript: Neutral (bound value "neutral")
        // TODO_FIGMA_KEY: 'BadgeTypes.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'BadgeTypes.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'BadgeTypes.Success', // ReScript: Success (bound value "success")
      },
    },
    text: { figmaProp: null /* TODO */, kind: 'string' },
    showBadge: { figmaProp: null /* TODO */, kind: 'bool' },
    showZero: { figmaProp: null /* TODO */, kind: 'bool' },
    hidden: { figmaProp: null /* TODO */, kind: 'bool' },
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultValue -- CommonTypes.stringOrNumberOrStringArray -- variant has payload(s) or is a record, not a simple enum
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): tabIndex -- int -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    rel: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): ariaCurrent -- [#page | #step | #location | #date | #time | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): ariaHaspopup -- [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): onCopy -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onCut -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onPaste -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onInput -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSubmit -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyPress -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyUp -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onContextMenu -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDoubleClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrag -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrop -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseDown -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseEnter -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseMove -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOut -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOver -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseUp -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onScroll -- ReactEvent.UI.t => unit -- event handler, code-only
    // TODO (unsupported): onWheel -- ReactEvent.Wheel.t => unit -- event handler, code-only
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    position: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'BadgeTypes.TopRight', // ReScript: TopRight (bound value "top-right")
        // TODO_FIGMA_KEY: 'BadgeTypes.TopLeft', // ReScript: TopLeft (bound value "top-left")
        // TODO_FIGMA_KEY: 'BadgeTypes.BottomRight', // ReScript: BottomRight (bound value "bottom-right")
        // TODO_FIGMA_KEY: 'BadgeTypes.BottomLeft', // ReScript: BottomLeft (bound value "bottom-left")
      },
    },
    // TODO (unsupported): offset -- (float, float) -- not confidently classifiable
    isCircular: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
