// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/BreadcrumbV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'BreadcrumbV2',
  id: 'breadcrumbV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): items -- array<BreadcrumbV2Types.breadcrumbV2ItemType> -- not confidently classifiable
    // TODO (unsupported): maxItems -- float -- not confidently classifiable
  },
}
