// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/BreadcrumbV2List.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'BreadcrumbV2List',
  id: 'breadcrumbV2List',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): breadcrumbTokens -- BreadcrumbV2Types.breadcrumbV2TokensType -- variant has payload(s) or is a record, not a simple enum
    shouldShowMenu: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): base -- BreadcrumbV2Types.indexedBreadcrumbChild -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rest -- array<BreadcrumbV2Types.indexedBreadcrumbChild> -- not confidently classifiable
    // TODO (unsupported): menuItems -- array<BreadcrumbV2Types.indexedBreadcrumbChild> -- not confidently classifiable
    // TODO (unsupported): totalItems -- float -- not confidently classifiable
  },
}
