// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Card.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Card',
  id: 'card',
  imports: ['open RescriptBlend'],
  props: {
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    maxHeight: { figmaProp: null /* TODO */, kind: 'string' },
    minHeight: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): skeleton -- CardTypes.cardSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CardTypes.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'CardTypes.Aligned', // ReScript: Aligned (bound value "aligned")
        // TODO_FIGMA_KEY: 'CardTypes.Custom', // ReScript: Custom (bound value "custom")
      },
    },
    // TODO (unsupported): headerSlot1 -- React.element (slot/children) -- needs manual handling
    headerTitle: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): headerTag -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerSlot2 -- React.element (slot/children) -- needs manual handling
    subHeader: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): bodySlot1 -- React.element (slot/children) -- needs manual handling
    bodyTitle: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): content -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): bodySlot2 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): actionButton -- ButtonTypes.buttonProps -- variant has payload(s) or is a record, not a simple enum
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CardTypes.Vertical', // ReScript: Vertical (bound value "vertical")
        // TODO_FIGMA_KEY: 'CardTypes.Horizontal', // ReScript: Horizontal (bound value "horizontal")
      },
    },
    centerAlign: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): cardSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
  },
}
