// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartV2NoData.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartV2NoData',
  id: 'chartV2NoData',
  imports: ['open JuspayRescriptBlend'],
  props: {
    title: { figmaProp: null /* TODO */, kind: 'string' },
    subtitle: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): button -- ButtonTypes.buttonProps -- variant has payload(s) or is a record, not a simple enum
  },
}
