// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartLegends.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartLegends',
  id: 'chartLegends',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): keys -- array<string> -- not confidently classifiable
    // TODO (unsupported): colors -- array<ChartsTypes.chartsColorsConfig> -- not confidently classifiable
    // TODO (unsupported): handleLegendClick -- string => unit -- event handler, code-only
    // TODO (unsupported): handleLegendEnter -- string => unit -- event handler, code-only
    // TODO (unsupported): handleLegendLeave -- unit => unit -- event handler, code-only
    // TODO (unsupported): selectedKeys -- array<string> -- not confidently classifiable
    // TODO (unsupported): setSelectedKeys -- array<string> => unit -- event handler, code-only
    // TODO (unsupported): hoveredKey -- Nullable.t<string> -- not confidently classifiable
    // TODO (unsupported): activeKeys -- Nullable.t<array<string>> -- not confidently classifiable
    stacked: { figmaProp: null /* TODO */, kind: 'bool' },
    isSmallScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): stackedLegendsData -- array<ChartsTypes.stackedLegendsDataPoint> -- not confidently classifiable
    // TODO (unsupported): legends -- array<ChartsTypes.chartsLegendsConfig> -- not confidently classifiable
  },
}
