// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartV2',
  id: 'chartV2',
  imports: ['open RescriptBlend'],
  props: {
    allowChartUpdate: { figmaProp: null /* TODO */, kind: 'bool' },
    constructorType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ChartsTypes.Width', // ReScript: Width (bound value "width")
        // TODO_FIGMA_KEY: 'ChartsTypes.Height', // ReScript: Height (bound value "height")
        // TODO_FIGMA_KEY: 'ChartsTypes.Color', // ReScript: Color (bound value "color")
        // TODO_FIGMA_KEY: 'ChartsTypes.Error', // ReScript: Error (bound value "error")
        // TODO_FIGMA_KEY: 'ChartsTypes.Open', // ReScript: Open (bound value "open")
        // TODO_FIGMA_KEY: 'ChartsTypes.End', // ReScript: End (bound value "end")
        // TODO_FIGMA_KEY: 'ChartsTypes.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'ChartsTypes.Wrap', // ReScript: Wrap (bound value "wrap")
        // TODO_FIGMA_KEY: 'ChartsTypes.X', // ReScript: X (bound value "x")
        // TODO_FIGMA_KEY: 'ChartsTypes.Y', // ReScript: Y (bound value "y")
        // TODO_FIGMA_KEY: 'ChartsTypes.Circle', // ReScript: Circle (bound value "circle")
        // TODO_FIGMA_KEY: 'ChartsTypes.Triangle', // ReScript: Triangle (bound value "triangle")
        // TODO_FIGMA_KEY: 'ChartsTypes.Find', // ReScript: Find (bound value "find")
        // TODO_FIGMA_KEY: 'ChartsTypes.BackgroundSize', // ReScript: BackgroundSize (bound value "backgroundSize")
        // TODO_FIGMA_KEY: 'ChartsTypes.AddEvent', // ReScript: AddEvent (bound value "addEvent")
        // TODO_FIGMA_KEY: 'ChartsTypes.Animate', // ReScript: Animate (bound value "animate")
        // TODO_FIGMA_KEY: 'ChartsTypes.AnimObject', // ReScript: AnimObject (bound value "animObject")
        // TODO_FIGMA_KEY: 'ChartsTypes.ArrayMax', // ReScript: ArrayMax (bound value "arrayMax")
        // TODO_FIGMA_KEY: 'ChartsTypes.ArrayMin', // ReScript: ArrayMin (bound value "arrayMin")
        // TODO_FIGMA_KEY: 'ChartsTypes.Attr', // ReScript: Attr (bound value "attr")
        // TODO_FIGMA_KEY: 'ChartsTypes.Chart', // ReScript: Chart (bound value "chart")
        // TODO_FIGMA_KEY: 'ChartsTypes.CorrectFloat', // ReScript: CorrectFloat (bound value "correctFloat")
        // TODO_FIGMA_KEY: 'ChartsTypes.CreateElement', // ReScript: CreateElement (bound value "createElement")
        // TODO_FIGMA_KEY: 'ChartsTypes.Css', // ReScript: Css (bound value "css")
        // TODO_FIGMA_KEY: 'ChartsTypes.DateFormat', // ReScript: DateFormat (bound value "dateFormat")
        // TODO_FIGMA_KEY: 'ChartsTypes.Defined', // ReScript: Defined (bound value "defined")
        // TODO_FIGMA_KEY: 'ChartsTypes.DestroyObjectProperties', // ReScript: DestroyObjectProperties (bound value "destroyObjectProperties")
        // TODO_FIGMA_KEY: 'ChartsTypes.DiscardElement', // ReScript: DiscardElement (bound value "discardElement")
        // TODO_FIGMA_KEY: 'ChartsTypes.Erase', // ReScript: Erase (bound value "erase")
        // TODO_FIGMA_KEY: 'ChartsTypes.Extend', // ReScript: Extend (bound value "extend")
        // TODO_FIGMA_KEY: 'ChartsTypes.ExtendClass', // ReScript: ExtendClass (bound value "extendClass")
        // TODO_FIGMA_KEY: 'ChartsTypes.FireEvent', // ReScript: FireEvent (bound value "fireEvent")
        // TODO_FIGMA_KEY: 'ChartsTypes.Format', // ReScript: Format (bound value "format")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetDeferredAnimation', // ReScript: GetDeferredAnimation (bound value "getDeferredAnimation")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetMagnitude', // ReScript: GetMagnitude (bound value "getMagnitude")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetOptions', // ReScript: GetOptions (bound value "getOptions")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetStyle', // ReScript: GetStyle (bound value "getStyle")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsArray', // ReScript: IsArray (bound value "isArray")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsClass', // ReScript: IsClass (bound value "isClass")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsDOMElement', // ReScript: IsDOMElement (bound value "isDOMElement")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsFunction', // ReScript: IsFunction (bound value "isFunction")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsNumber', // ReScript: IsNumber (bound value "isNumber")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsObject', // ReScript: IsObject (bound value "isObject")
        // TODO_FIGMA_KEY: 'ChartsTypes.IsString', // ReScript: IsString (bound value "isString")
        // TODO_FIGMA_KEY: 'ChartsTypes.Merge', // ReScript: Merge (bound value "merge")
        // TODO_FIGMA_KEY: 'ChartsTypes.NormalizeTickInterval', // ReScript: NormalizeTickInterval (bound value "normalizeTickInterval")
        // TODO_FIGMA_KEY: 'ChartsTypes.NumberFormat', // ReScript: NumberFormat (bound value "numberFormat")
        // TODO_FIGMA_KEY: 'ChartsTypes.ObjectEach', // ReScript: ObjectEach (bound value "objectEach")
        // TODO_FIGMA_KEY: 'ChartsTypes.Offset', // ReScript: Offset (bound value "offset")
        // TODO_FIGMA_KEY: 'ChartsTypes.Pad', // ReScript: Pad (bound value "pad")
        // TODO_FIGMA_KEY: 'ChartsTypes.Pick', // ReScript: Pick (bound value "pick")
        // TODO_FIGMA_KEY: 'ChartsTypes.RelativeLength', // ReScript: RelativeLength (bound value "relativeLength")
        // TODO_FIGMA_KEY: 'ChartsTypes.RemoveEvent', // ReScript: RemoveEvent (bound value "removeEvent")
        // TODO_FIGMA_KEY: 'ChartsTypes.SeriesType', // ReScript: SeriesType (bound value "seriesType")
        // TODO_FIGMA_KEY: 'ChartsTypes.SetAnimation', // ReScript: SetAnimation (bound value "setAnimation")
        // TODO_FIGMA_KEY: 'ChartsTypes.SetOptions', // ReScript: SetOptions (bound value "setOptions")
        // TODO_FIGMA_KEY: 'ChartsTypes.Splat', // ReScript: Splat (bound value "splat")
        // TODO_FIGMA_KEY: 'ChartsTypes.StableSort', // ReScript: StableSort (bound value "stableSort")
        // TODO_FIGMA_KEY: 'ChartsTypes.Stop', // ReScript: Stop (bound value "stop")
        // TODO_FIGMA_KEY: 'ChartsTypes.SyncTimeout', // ReScript: SyncTimeout (bound value "syncTimeout")
        // TODO_FIGMA_KEY: 'ChartsTypes.UniqueKey', // ReScript: UniqueKey (bound value "uniqueKey")
        // TODO_FIGMA_KEY: 'ChartsTypes.UseSerialIds', // ReScript: UseSerialIds (bound value "useSerialIds")
        // TODO_FIGMA_KEY: 'ChartsTypes.Arc', // ReScript: Arc (bound value "arc")
        // TODO_FIGMA_KEY: 'ChartsTypes.Callout', // ReScript: Callout (bound value "callout")
        // TODO_FIGMA_KEY: 'ChartsTypes.CenterImage', // ReScript: CenterImage (bound value "centerImage")
        // TODO_FIGMA_KEY: 'ChartsTypes.DateTimeFormat', // ReScript: DateTimeFormat (bound value "dateTimeFormat")
        // TODO_FIGMA_KEY: 'ChartsTypes.DeleteRows', // ReScript: DeleteRows (bound value "deleteRows")
        // TODO_FIGMA_KEY: 'ChartsTypes.Diamond', // ReScript: Diamond (bound value "diamond")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetColumn', // ReScript: GetColumn (bound value "getColumn")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetColumns', // ReScript: GetColumns (bound value "getColumns")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetLogTickPositions', // ReScript: GetLogTickPositions (bound value "getLogTickPositions")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetModified', // ReScript: GetModified (bound value "getModified")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetRendererType', // ReScript: GetRendererType (bound value "getRendererType")
        // TODO_FIGMA_KEY: 'ChartsTypes.GetRow', // ReScript: GetRow (bound value "getRow")
        // TODO_FIGMA_KEY: 'ChartsTypes.ModifyTree', // ReScript: ModifyTree (bound value "modifyTree")
        // TODO_FIGMA_KEY: 'ChartsTypes.Rect', // ReScript: Rect (bound value "rect")
        // TODO_FIGMA_KEY: 'ChartsTypes.RegisterRendererType', // ReScript: RegisterRendererType (bound value "registerRendererType")
        // TODO_FIGMA_KEY: 'ChartsTypes.RegisterSeriesType', // ReScript: RegisterSeriesType (bound value "registerSeriesType")
        // TODO_FIGMA_KEY: 'ChartsTypes.RoundedRect', // ReScript: RoundedRect (bound value "roundedRect")
        // TODO_FIGMA_KEY: 'ChartsTypes.SetColumn', // ReScript: SetColumn (bound value "setColumn")
        // TODO_FIGMA_KEY: 'ChartsTypes.SetColumns', // ReScript: SetColumns (bound value "setColumns")
        // TODO_FIGMA_KEY: 'ChartsTypes.SetRow', // ReScript: SetRow (bound value "setRow")
        // TODO_FIGMA_KEY: 'ChartsTypes.Str2dtf', // ReScript: Str2dtf (bound value "str2dtf")
        // TODO_FIGMA_KEY: 'ChartsTypes.TriangleDown', // ReScript: TriangleDown (bound value "triangleDown")
        // TODO_FIGMA_KEY: 'ChartsTypes.UnescapeEntities', // ReScript: UnescapeEntities (bound value "unescapeEntities")
        // TODO_FIGMA_KEY: 'ChartsTypes.Annotation', // ReScript: Annotation (bound value "Annotation")
        // TODO_FIGMA_KEY: 'ChartsTypes.AnnotationControlPoint', // ReScript: AnnotationControlPoint (bound value "AnnotationControlPoint")
        // TODO_FIGMA_KEY: 'ChartsTypes.AST', // ReScript: AST (bound value "AST")
        // TODO_FIGMA_KEY: 'ChartsTypes.Axis', // ReScript: Axis (bound value "Axis")
        // TODO_FIGMA_KEY: 'ChartsTypes.Chart2', // ReScript: Chart2 (bound value "Chart")
        // TODO_FIGMA_KEY: 'ChartsTypes.Color2', // ReScript: Color2 (bound value "Color")
        // TODO_FIGMA_KEY: 'ChartsTypes.DataTable', // ReScript: DataTable (bound value "DataTable")
        // TODO_FIGMA_KEY: 'ChartsTypes.DataTableCore', // ReScript: DataTableCore (bound value "DataTableCore")
        // TODO_FIGMA_KEY: 'ChartsTypes.Legend', // ReScript: Legend (bound value "Legend")
        // TODO_FIGMA_KEY: 'ChartsTypes.PlotLineOrBand', // ReScript: PlotLineOrBand (bound value "PlotLineOrBand")
        // TODO_FIGMA_KEY: 'ChartsTypes.Point', // ReScript: Point (bound value "Point")
        // TODO_FIGMA_KEY: 'ChartsTypes.Pointer', // ReScript: Pointer (bound value "Pointer")
        // TODO_FIGMA_KEY: 'ChartsTypes.Series', // ReScript: Series (bound value "Series")
        // TODO_FIGMA_KEY: 'ChartsTypes.StackItem', // ReScript: StackItem (bound value "StackItem")
        // TODO_FIGMA_KEY: 'ChartsTypes.SVGElement', // ReScript: SVGElement (bound value "SVGElement")
        // TODO_FIGMA_KEY: 'ChartsTypes.SVGLabel', // ReScript: SVGLabel (bound value "SVGLabel")
        // TODO_FIGMA_KEY: 'ChartsTypes.SVGRenderer', // ReScript: SVGRenderer (bound value "SVGRenderer")
        // TODO_FIGMA_KEY: 'ChartsTypes.Tick', // ReScript: Tick (bound value "Tick")
        // TODO_FIGMA_KEY: 'ChartsTypes.Time', // ReScript: Time (bound value "Time")
        // TODO_FIGMA_KEY: 'ChartsTypes.Tooltip', // ReScript: Tooltip (bound value "Tooltip")
        // TODO_FIGMA_KEY: 'ChartsTypes.Charts', // ReScript: Charts (bound value "charts")
        // TODO_FIGMA_KEY: 'ChartsTypes.DateFormats', // ReScript: DateFormats (bound value "dateFormats")
        // TODO_FIGMA_KEY: 'ChartsTypes.DefaultOptions', // ReScript: DefaultOptions (bound value "defaultOptions")
        // TODO_FIGMA_KEY: 'ChartsTypes.Theme', // ReScript: Theme (bound value "theme")
        // TODO_FIGMA_KEY: 'ChartsTypes.AnchorX', // ReScript: AnchorX (bound value "anchorX")
        // TODO_FIGMA_KEY: 'ChartsTypes.AnchorY', // ReScript: AnchorY (bound value "anchorY")
        // TODO_FIGMA_KEY: 'ChartsTypes.Clockwise', // ReScript: Clockwise (bound value "clockwise")
        // TODO_FIGMA_KEY: 'ChartsTypes.Context', // ReScript: Context (bound value "context")
        // TODO_FIGMA_KEY: 'ChartsTypes.InnerR', // ReScript: InnerR (bound value "innerR")
        // TODO_FIGMA_KEY: 'ChartsTypes.LongArc', // ReScript: LongArc (bound value "longArc")
        // TODO_FIGMA_KEY: 'ChartsTypes.R', // ReScript: R (bound value "r")
      },
    },
    // TODO (unsupported): containerProps -- Dict.t<'a> -- not confidently classifiable
    // TODO (unsupported): highcharts -- InstanceTypes.highchartsModule -- variant has payload(s) or is a record, not a simple enum
    immutable: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): options -- HighchartsSharedTypes.options<'b> -- not confidently classifiable
    // TODO (unsupported): updateArgs -- array<bool> -- not confidently classifiable
    // TODO (unsupported): callback -- HighchartsSharedTypes.chart<'b> => unit -- event handler, code-only
    // TODO (unsupported): skeleton -- ChartsV2Types.chartV2SkeletonProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): noData -- ChartsV2Types.chartV2NoDataProps -- variant has payload(s) or is a record, not a simple enum
  },
}
