// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartV2Skeleton.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartV2Skeleton',
  id: 'chartV2Skeleton',
  imports: ['open RescriptBlend'],
  props: {
    skeletonVariant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Pulse', // ReScript: Pulse (bound value "pulse")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Wave', // ReScript: Wave (bound value "wave")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Shimmer', // ReScript: Shimmer (bound value "shimmer")
      },
    },
    // TODO (unsupported): height -- float -- not confidently classifiable
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
