// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartHeader.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartHeader',
  id: 'chartHeader',
  imports: ['open JuspayRescriptBlend'],
  props: {
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slot1 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): slot2 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): slot3 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): chartHeaderSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onFullscreen -- unit => unit -- event handler, code-only
    // TODO (unsupported): onExitFullscreen -- unit => unit -- event handler, code-only
    isFullscreen: { figmaProp: null /* TODO */, kind: 'bool' },
    isSmallScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): setIsExpanded -- bool => unit -- event handler, code-only
    showCollapseIcon: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
