// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Charts.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Charts',
  id: 'charts',
  imports: ['open RescriptBlend'],
  props: {
    chartType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ChartsTypes.Line', // ReScript: Line (bound value "line")
        // TODO_FIGMA_KEY: 'ChartsTypes.Bar', // ReScript: Bar (bound value "bar")
        // TODO_FIGMA_KEY: 'ChartsTypes.LineBar', // ReScript: LineBar (bound value "lineBar")
        // TODO_FIGMA_KEY: 'ChartsTypes.Pie', // ReScript: Pie (bound value "pie")
        // TODO_FIGMA_KEY: 'ChartsTypes.Scatter', // ReScript: Scatter (bound value "scatter")
        // TODO_FIGMA_KEY: 'ChartsTypes.Area', // ReScript: Area (bound value "area")
        // TODO_FIGMA_KEY: 'ChartsTypes.Sankey', // ReScript: Sankey (bound value "sankey")
      },
    },
    // TODO (unsupported): data -- Nullable.t<array<ChartsTypes.newNestedDataPoint>> -- not confidently classifiable
    // TODO (unsupported): colors -- array<ChartsTypes.chartsColorsConfig> -- not confidently classifiable
    // TODO (unsupported): slot1 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): slot2 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): slot3 -- React.element (slot/children) -- needs manual handling
    legendPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ChartsTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'ChartsTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): chartHeaderSlot -- React.element (slot/children) -- needs manual handling
    stackedLegends: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): stackedLegendsData -- array<ChartsTypes.stackedLegendsDataPoint> -- not confidently classifiable
    // TODO (unsupported): barsize -- float -- not confidently classifiable
    // TODO (unsupported): xAxis -- ChartsTypes.axisConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): yAxis -- ChartsTypes.axisConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): tooltip -- ChartsTypes.tooltipConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): noData -- ChartsTypes.noDataProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): height -- float -- not confidently classifiable
    showHeader: { figmaProp: null /* TODO */, kind: 'bool' },
    showCollapseIcon: { figmaProp: null /* TODO */, kind: 'bool' },
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onExpandedChange -- bool => unit -- event handler, code-only
    chartName: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): skeleton -- ChartsTypes.chartsSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): legends -- array<ChartsTypes.chartsLegendsConfig> -- not confidently classifiable
    // TODO (unsupported): lineSeriesKeys -- array<string> -- not confidently classifiable
  },
}
