// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChartV2Fullscreen.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChartV2Fullscreen',
  id: 'chartV2Fullscreen',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): children -- ChartsV2Types.chartV2FullscreenControls => React.element -- event handler, code-only
  },
}
