// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ChatInput.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ChatInput',
  id: 'chatInput',
  imports: ['open RescriptBlend'],
  props: {
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): maxLength -- int -- not confidently classifiable
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slot1 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): slot2 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    // TODO (unsupported): onSend -- (string, array<ChatInputTypes.attachedFile>) => unit -- event handler, code-only
    // TODO (unsupported): onAttachFiles -- array<Webapi.File.t> => unit -- event handler, code-only
    // TODO (unsupported): onVoiceRecord -- unit => unit -- event handler, code-only
    // TODO (unsupported): onFileRemove -- string => unit -- event handler, code-only
    // TODO (unsupported): onFileClick -- ChatInputTypes.attachedFile => unit -- event handler, code-only
    autoResize: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): attachedFiles -- array<ChatInputTypes.attachedFile> -- not confidently classifiable
    // TODO (unsupported): topQueries -- array<ChatInputTypes.topQuery> -- not confidently classifiable
    // TODO (unsupported): onTopQuerySelect -- ChatInputTypes.topQuery => unit -- event handler, code-only
    // TODO (unsupported): topQueriesMaxHeight -- float -- not confidently classifiable
    attachButtonIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    voiceButtonIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    sendButtonIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    // TODO (unsupported): overflowMenuProps -- MenuTypes.menuOverflowMenuPropsConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
