// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/CodeEditor.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'CodeEditor',
  id: 'codeEditor',
  imports: ['open JuspayRescriptBlend'],
  props: {
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.NoGutter', // ReScript: NoGutter (bound value "no-gutter")
      },
    },
    showLineNumbers: { figmaProp: null /* TODO */, kind: 'bool' },
    showHeader: { figmaProp: null /* TODO */, kind: 'bool' },
    header: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): headerLeftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerRightSlot -- React.element (slot/children) -- needs manual handling
    showLeftIcon: { figmaProp: null /* TODO */, kind: 'bool' },
    showCopyButton: { figmaProp: null /* TODO */, kind: 'bool' },
    language: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Ruby', // ReScript: Ruby (bound value "ruby")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Plaintext', // ReScript: Plaintext (bound value "plaintext")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Css', // ReScript: Css (bound value "css")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.C', // ReScript: C (bound value "c")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Javascript', // ReScript: Javascript (bound value "javascript")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Typescript', // ReScript: Typescript (bound value "typescript")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Json', // ReScript: Json (bound value "json")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Html', // ReScript: Html (bound value "html")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Markdown', // ReScript: Markdown (bound value "markdown")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Yaml', // ReScript: Yaml (bound value "yaml")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Python', // ReScript: Python (bound value "python")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Rust', // ReScript: Rust (bound value "rust")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Scss', // ReScript: Scss (bound value "scss")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Less', // ReScript: Less (bound value "less")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Xml', // ReScript: Xml (bound value "xml")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Ini', // ReScript: Ini (bound value "ini")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Graphql', // ReScript: Graphql (bound value "graphql")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Sql', // ReScript: Sql (bound value "sql")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Go', // ReScript: Go (bound value "go")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Java', // ReScript: Java (bound value "java")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Kotlin', // ReScript: Kotlin (bound value "kotlin")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Swift', // ReScript: Swift (bound value "swift")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Cpp', // ReScript: Cpp (bound value "cpp")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Csharp', // ReScript: Csharp (bound value "csharp")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Php', // ReScript: Php (bound value "php")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Shell', // ReScript: Shell (bound value "shell")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Powershell', // ReScript: Powershell (bound value "powershell")
        // TODO_FIGMA_KEY: 'CodeEditorTypes.Dockerfile', // ReScript: Dockerfile (bound value "dockerfile")
      },
    },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    readOnly: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): minHeight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxHeight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): height -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    className: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onBlur -- unit => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- unit => unit -- event handler, code-only
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
