// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/CodeBlock.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'CodeBlock',
  id: 'codeBlock',
  imports: ['open RescriptBlend'],
  props: {
    code: { figmaProp: null /* TODO */, kind: 'string' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.NoGutter', // ReScript: NoGutter (bound value "no-gutter")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Diff', // ReScript: Diff (bound value "diff")
      },
    },
    showLineNumbers: { figmaProp: null /* TODO */, kind: 'bool' },
    showHeader: { figmaProp: null /* TODO */, kind: 'bool' },
    header: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): headerLeftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerRightSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): diffLines -- array<CodeBlockTypes.diffLine> -- not confidently classifiable
    showCopyButton: { figmaProp: null /* TODO */, kind: 'bool' },
    autoFormat: { figmaProp: null /* TODO */, kind: 'bool' },
    language: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Css', // ReScript: Css (bound value "css")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Javascript', // ReScript: Javascript (bound value "javascript")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Typescript', // ReScript: Typescript (bound value "typescript")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Jsx', // ReScript: Jsx (bound value "jsx")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Tsx', // ReScript: Tsx (bound value "tsx")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Json', // ReScript: Json (bound value "json")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Html', // ReScript: Html (bound value "html")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Markdown', // ReScript: Markdown (bound value "markdown")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Yaml', // ReScript: Yaml (bound value "yaml")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Python', // ReScript: Python (bound value "python")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Rust', // ReScript: Rust (bound value "rust")
        // TODO_FIGMA_KEY: 'CodeBlockTypes.Haskell', // ReScript: Haskell (bound value "haskell")
      },
    },
    isDiffUnchangedCollapsed: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): diffContextLines -- float -- not confidently classifiable
    // TODO (unsupported): diffExpandChunk -- float -- not confidently classifiable
    maxHeight: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
