// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/CodeEditorV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'CodeEditorV2',
  id: 'codeEditorV2',
  imports: ['open RescriptBlend'],
  props: {
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.NoGutter', // ReScript: NoGutter (bound value "no-gutter")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Diff', // ReScript: Diff (bound value "diff")
      },
    },
    showLineNumbers: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): header -- EditorSharedTypes.codeEditorV2HeaderConfig -- variant has payload(s) or is a record, not a simple enum
    language: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Ruby', // ReScript: Ruby (bound value "ruby")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Plaintext', // ReScript: Plaintext (bound value "plaintext")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Css', // ReScript: Css (bound value "css")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.C', // ReScript: C (bound value "c")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Javascript', // ReScript: Javascript (bound value "javascript")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Typescript', // ReScript: Typescript (bound value "typescript")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Json', // ReScript: Json (bound value "json")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Html', // ReScript: Html (bound value "html")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Markdown', // ReScript: Markdown (bound value "markdown")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Yaml', // ReScript: Yaml (bound value "yaml")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Python', // ReScript: Python (bound value "python")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Rust', // ReScript: Rust (bound value "rust")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Scss', // ReScript: Scss (bound value "scss")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Less', // ReScript: Less (bound value "less")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Xml', // ReScript: Xml (bound value "xml")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Ini', // ReScript: Ini (bound value "ini")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Graphql', // ReScript: Graphql (bound value "graphql")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Sql', // ReScript: Sql (bound value "sql")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Go', // ReScript: Go (bound value "go")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Java', // ReScript: Java (bound value "java")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Kotlin', // ReScript: Kotlin (bound value "kotlin")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Swift', // ReScript: Swift (bound value "swift")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Cpp', // ReScript: Cpp (bound value "cpp")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Csharp', // ReScript: Csharp (bound value "csharp")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Php', // ReScript: Php (bound value "php")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Shell', // ReScript: Shell (bound value "shell")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Powershell', // ReScript: Powershell (bound value "powershell")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Dockerfile', // ReScript: Dockerfile (bound value "dockerfile")
      },
    },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    readOnly: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onBlur -- unit => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- unit => unit -- event handler, code-only
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    diff: { figmaProp: null /* TODO */, kind: 'bool' },
    originalValue: { figmaProp: null /* TODO */, kind: 'string' },
    renderSideBySide: { figmaProp: null /* TODO */, kind: 'bool' },
    isDiffUnchangedCollapsed: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): diffContextLines -- float -- not confidently classifiable
    // TODO (unsupported): diffExpandChunk -- float -- not confidently classifiable
    width: { figmaProp: null /* TODO */, kind: 'string' },
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
    height: { figmaProp: null /* TODO */, kind: 'string' },
    maxHeight: { figmaProp: null /* TODO */, kind: 'string' },
    minHeight: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
