// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/CoreChart.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'CoreChart',
  id: 'coreChart',
  imports: ['open RescriptBlend'],
  props: {
    chartType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ChartsTypes.Line', // ReScript: Line (bound value "line")
        // TODO_FIGMA_KEY: 'ChartsTypes.Bar', // ReScript: Bar (bound value "bar")
        // TODO_FIGMA_KEY: 'ChartsTypes.LineBar', // ReScript: LineBar (bound value "lineBar")
        // TODO_FIGMA_KEY: 'ChartsTypes.Pie', // ReScript: Pie (bound value "pie")
        // TODO_FIGMA_KEY: 'ChartsTypes.Scatter', // ReScript: Scatter (bound value "scatter")
        // TODO_FIGMA_KEY: 'ChartsTypes.Area', // ReScript: Area (bound value "area")
        // TODO_FIGMA_KEY: 'ChartsTypes.Sankey', // ReScript: Sankey (bound value "sankey")
      },
    },
    // TODO (unsupported): data -- Nullable.t<array<ChartsTypes.newNestedDataPoint>> -- not confidently classifiable
    // TODO (unsupported): colors -- array<ChartsTypes.chartsColorsConfig> -- not confidently classifiable
    // TODO (unsupported): barsize -- float -- not confidently classifiable
    // TODO (unsupported): xAxis -- ChartsTypes.axisConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): yAxis -- ChartsTypes.axisConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): tooltip -- ChartsTypes.tooltipConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): height -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): width -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    isSmallScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): hoveredKey -- Nullable.t<string> -- not confidently classifiable
    // TODO (unsupported): onHoveredKeyChange -- Nullable.t<string> => unit -- event handler, code-only
    // TODO (unsupported): selectedKeys -- array<string> -- not confidently classifiable
    // TODO (unsupported): lineSeriesKeys -- array<string> -- not confidently classifiable
    enableHover: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
