// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DataTable.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DataTable',
  id: 'dataTable',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): data -- array<'a> -- not confidently classifiable
    // TODO (unsupported): columns -- array<DataTableTypes.ColumnDefinition.t>, // ⓘ was `ColumnDefinition<T>` — opaque; build with ColumnDefinition.fromDataTableColumnsTextConfig / ColumnDefinition.fromDataTableColumnsNumberConfig / ColumnDefinition.fromDataTableColumnsAvatarConfig / ColumnDefinition.fromDataTableColumnsTagConfig / ColumnDefinition.fromDataTableColumnsProgressConfig / ColumnDefinition.fromDataTableColumnsDropdownConfig / ColumnDefinition.fromDataTableColumnsDateConfig / ColumnDefinition.fromDataTableColumnsSliderConfig / ColumnDefinition.fromDataTableColumnsReactElementConfig / ColumnDefinition.fromDataTableColumnsFilterTypeConfig -- not confidently classifiable
    idField: { figmaProp: null /* TODO */, kind: 'string' },
    title: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): descriptionTooltipProps -- DataTableTypes.dataTableDescriptionTooltipPropsConfig -- variant has payload(s) or is a record, not a simple enum
    className: { figmaProp: null /* TODO */, kind: 'string' },
    isHoverable: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultSort -- DataTableTypes.sortConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onSortChange -- DataTableTypes.sortConfig => unit -- event handler, code-only
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    serverSideSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onSearchChange -- DataTableTypes.searchConfig => unit -- event handler, code-only
    enableFiltering: { figmaProp: null /* TODO */, kind: 'bool' },
    enableAdvancedFilter: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): advancedFilterComponent -- React.component<DataTableTypes.advancedFilterProps> -- not confidently classifiable
    // TODO (unsupported): advancedFilters -- array<JSON.t> -- not confidently classifiable
    serverSideFiltering: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onFilterChange -- array<DataTableTypes.columnFilter> => unit -- event handler, code-only
    // TODO (unsupported): onAdvancedFiltersChange -- array<JSON.t> => unit -- event handler, code-only
    // TODO (unsupported): columnFreeze -- float -- not confidently classifiable
    // TODO (unsupported): columnFreezeRight -- float -- not confidently classifiable
    enableColumnManager: { figmaProp: null /* TODO */, kind: 'bool' },
    enableColumnReordering: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onColumnReorder -- array<DataTableTypes.ColumnDefinition.t> => unit=?, // ⓘ was `ColumnDefinition<T>` — opaque; build with ColumnDefinition.fromDataTableColumnsTextConfig / ColumnDefinition.fromDataTableColumnsNumberConfig / ColumnDefinition.fromDataTableColumnsAvatarConfig / ColumnDefinition.fromDataTableColumnsTagConfig / ColumnDefinition.fromDataTableColumnsProgressConfig / ColumnDefinition.fromDataTableColumnsDropdownConfig / ColumnDefinition.fromDataTableColumnsDateConfig / ColumnDefinition.fromDataTableColumnsSliderConfig / ColumnDefinition.fromDataTableColumnsReactElementConfig / ColumnDefinition.fromDataTableColumnsFilterTypeConfig -- event handler, code-only
    // TODO (unsupported): columnManagerMaxSelections -- float -- not confidently classifiable
    // TODO (unsupported): columnManagerAlwaysSelected -- array<string> -- not confidently classifiable
    // TODO (unsupported): columnManagerPrimaryAction -- DataTableTypes.dataTableColumnManagerPrimaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): columnManagerSecondaryAction -- DataTableTypes.dataTableColumnManagerSecondaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): columnManagerWidth -- float -- not confidently classifiable
    // TODO (unsupported): pagination -- DataTableTypes.paginationConfig -- variant has payload(s) or is a record, not a simple enum
    serverSidePagination: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onPageChange -- float => unit -- event handler, code-only
    // TODO (unsupported): onPageSizeChange -- float => unit -- event handler, code-only
    isLoading: { figmaProp: null /* TODO */, kind: 'bool' },
    showSkeleton: { figmaProp: null /* TODO */, kind: 'bool' },
    skeletonVariant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Pulse', // ReScript: Pulse (bound value "pulse")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Wave', // ReScript: Wave (bound value "wave")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Shimmer', // ReScript: Shimmer (bound value "shimmer")
      },
    },
    // TODO (unsupported): isRowLoading -- ('a, float) => bool -- event handler, code-only
    showHeader: { figmaProp: null /* TODO */, kind: 'bool' },
    showToolbar: { figmaProp: null /* TODO */, kind: 'bool' },
    showSettings: { figmaProp: null /* TODO */, kind: 'bool' },
    showFooter: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): headerSlot1 -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerSlot2 -- React.element (slot/children) -- needs manual handling
    enableInlineEdit: { figmaProp: null /* TODO */, kind: 'bool' },
    showActionsColumn: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onRowSave -- (JSON.t, 'a) => unit -- event handler, code-only
    // TODO (unsupported): onRowCancel -- JSON.t => unit -- event handler, code-only
    // TODO (unsupported): onRowClick -- ('a, float) => unit -- event handler, code-only
    // TODO (unsupported): onFieldChange -- (JSON.t, string, JSON.t) => unit -- event handler, code-only
    // TODO (unsupported): onHeaderChange -- (string, string) => unit -- event handler, code-only
    enableRowExpansion: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): renderExpandedRow -- DataTableTypes.dataTableRenderExpandedRowConfig<'a> => React.element -- event handler, code-only
    // TODO (unsupported): isRowExpandable -- ('a, float) => bool -- event handler, code-only
    // TODO (unsupported): onRowExpansionChange -- (JSON.t, bool, 'a) => unit -- event handler, code-only
    enableRowSelection: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): rowSelectionConfig -- DataTableTypes.rowSelectionConfig<'a> -- not confidently classifiable
    showBulkActionBar: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onRowSelectionChange -- (array<string>, bool, string, 'a) => unit -- event handler, code-only
    // TODO (unsupported): bulkActions -- DataTableTypes.bulkActionsConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rowActions -- DataTableTypes.rowActionsConfig<'a> -- not confidently classifiable
    // TODO (unsupported): onOperations -- string => unit -- event handler, code-only
    // TODO (unsupported): onInsertLeft -- string => unit -- event handler, code-only
    // TODO (unsupported): onInsertRight -- string => unit -- event handler, code-only
    // TODO (unsupported): onDeleteColumn -- string => unit -- event handler, code-only
    // TODO (unsupported): getRowStyle -- ('a, float) => JsxDOM.style -- event handler, code-only
    // TODO (unsupported): tableBodyHeight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): mobileColumnsToShow -- float -- not confidently classifiable
    dateLabel: { figmaProp: null /* TODO */, kind: 'string' },
    enablePivotTable: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): pivotTableConfig -- DataTableTypes.dataTablePivotTableConfigConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
