// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DateRangePicker.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DateRangePicker',
  id: 'dateRangePicker',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): value -- DateRangePickerTypes.dateRange -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onChange -- DateRangePickerTypes.dateRange => unit -- event handler, code-only
    // TODO (unsupported): onPresetSelection -- DateRangePickerTypes.presetSelectionData => unit -- event handler, code-only
    showDateTimePicker: { figmaProp: null /* TODO */, kind: 'bool' },
    showDateInput: { figmaProp: null /* TODO */, kind: 'bool' },
    showPresets: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): customPresets -- array<DateRangePickerTypes.PresetsConfig.t>=?, // ⓘ was `DateRangePreset | CustomPresetConfig | CustomPresetDefinition` — opaque; build with PresetsConfig.fromDateRangePreset / PresetsConfig.fromCustomPresetConfig / PresetsConfig.fromCustomPresetDefinition -- not confidently classifiable
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    isDisabled: { figmaProp: null /* TODO */, kind: 'bool' },
    icon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    // TODO (unsupported): minDate -- Date.t -- not confidently classifiable
    // TODO (unsupported): maxDate -- Date.t -- not confidently classifiable
    dateFormat: { figmaProp: null /* TODO */, kind: 'string' },
    allowSingleDateSelection: { figmaProp: null /* TODO */, kind: 'bool' },
    isSingleDatePicker: { figmaProp: null /* TODO */, kind: 'bool' },
    disableFutureDates: { figmaProp: null /* TODO */, kind: 'bool' },
    disablePastDates: { figmaProp: null /* TODO */, kind: 'bool' },
    hideFutureDates: { figmaProp: null /* TODO */, kind: 'bool' },
    hidePastDates: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): customDisableDates -- Date.t => bool -- event handler, code-only
    // TODO (unsupported): customRangeConfig -- DateRangePickerTypes.customRangeConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): triggerElement -- React.element (slot/children) -- needs manual handling
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    skipQuickFiltersOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): formatConfig -- DateRangePickerTypes.dateFormatConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): triggerConfig -- DateRangePickerTypes.triggerConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): popoverConfig -- DateRangePickerTypes.dateRangePickerPopoverConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxMenuHeight -- float -- not confidently classifiable
    showPreset: { figmaProp: null /* TODO */, kind: 'bool' },
    timezone: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): maxYearOffset -- float -- not confidently classifiable
  },
}
