// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Directory.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Directory',
  id: 'directory',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): directoryData -- Nullable.t<array<DirectoryTypes.directoryData>> -- not confidently classifiable
    idPrefix: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): activeItem -- Nullable.t<string> -- not confidently classifiable
    // TODO (unsupported): onActiveItemChange -- Nullable.t<string> => unit -- event handler, code-only
    // TODO (unsupported): defaultActiveItem -- Nullable.t<string> -- not confidently classifiable
    iconOnlyMode: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
