// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DrawerFooter.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DrawerFooter',
  id: 'drawerFooter',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    className: { figmaProp: null /* TODO */, kind: 'string' },
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
  },
}
