// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DrawerContent.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DrawerContent',
  id: 'drawerContent',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    className: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
    fullScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    showHandle: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): handle -- React.element (slot/children) -- needs manual handling
    hasSnapPoints: { figmaProp: null /* TODO */, kind: 'bool' },
    contentDriven: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): width -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): offSet -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): mobileOffset -- DrawerTypes.drawerMobileOffsetConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
