// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DrawerV2NestedRoot.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DrawerV2NestedRoot',
  id: 'drawerV2NestedRoot',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): activeSnapPoint -- Nullable.t<CommonTypes.stringOrNumber> -- not confidently classifiable
    // TODO (unsupported): setActiveSnapPoint -- Nullable.t<CommonTypes.stringOrNumber> => unit -- event handler, code-only
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): closeThreshold -- float -- not confidently classifiable
    noBodyStyles: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    shouldScaleBackground: { figmaProp: null /* TODO */, kind: 'bool' },
    setBackgroundColorOnScale: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): scrollLockTimeout -- float -- not confidently classifiable
    fixed: { figmaProp: null /* TODO */, kind: 'bool' },
    handleOnly: { figmaProp: null /* TODO */, kind: 'bool' },
    dismissible: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onDrag -- ('a, float) => unit=?, // ⓘ a parameter type could not be modelled — received as a type variable; annotate at the call site -- event handler, code-only
    // TODO (unsupported): onRelease -- ('b, bool) => unit=?, // ⓘ a parameter type could not be modelled — received as a type variable; annotate at the call site -- event handler, code-only
    modal: { figmaProp: null /* TODO */, kind: 'bool' },
    nested: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    defaultOpen: { figmaProp: null /* TODO */, kind: 'bool' },
    disablePreventScroll: { figmaProp: null /* TODO */, kind: 'bool' },
    repositionInputs: { figmaProp: null /* TODO */, kind: 'bool' },
    snapToSequentialPoint: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): container -- Nullable.t<Dom.element> -- not confidently classifiable
    // TODO (unsupported): onAnimationEnd -- bool => unit -- event handler, code-only
    preventScrollRestoration: { figmaProp: null /* TODO */, kind: 'bool' },
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): snapPoints -- array<CommonTypes.stringOrNumber> -- not confidently classifiable
    // TODO (unsupported): fadeFromIndex -- float -- not confidently classifiable
  },
}
