// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Drawer.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Drawer',
  id: 'drawer',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DrawerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DrawerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DrawerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DrawerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    modal: { figmaProp: null /* TODO */, kind: 'bool' },
    dismissible: { figmaProp: null /* TODO */, kind: 'bool' },
    showHandle: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): handle -- React.element (slot/children) -- needs manual handling
    nested: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): snapPoints -- array<CommonTypes.stringOrNumber> -- not confidently classifiable
    // TODO (unsupported): activeSnapPoint -- Nullable.t<CommonTypes.stringOrNumber> -- not confidently classifiable
    // TODO (unsupported): onSnapPointChange -- Nullable.t<CommonTypes.stringOrNumber> => unit -- event handler, code-only
    // TODO (unsupported): fadeFromIndex -- float -- not confidently classifiable
    snapToSequentialPoint: { figmaProp: null /* TODO */, kind: 'bool' },
    disableDrag: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): mobileOffset -- DrawerTypes.drawerMobileOffsetConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
  },
}
