// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/DropdownInput.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'DropdownInput',
  id: 'dropdownInput',
  imports: ['open RescriptBlend'],
  props: {
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'InputsTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'InputsTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    dropDownValue: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onDropDownChange -- string => unit -- event handler, code-only
    // TODO (unsupported): dropDownItems -- array<SelectTypes.selectMenuGroupType> -- not confidently classifiable
    dropdownName: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onDropdownOpen -- unit => unit -- event handler, code-only
    // TODO (unsupported): onDropdownClose -- unit => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    dropdownPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'InputsTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): maxMenuHeight -- float -- not confidently classifiable
    // TODO (unsupported): minMenuWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxMenuWidth -- float -- not confidently classifiable
  },
}
