// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/IconButton.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'IconButton',
  id: 'iconButton',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): width -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): minWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    hidden: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    icon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultValue -- CommonTypes.stringOrNumberOrStringArray -- variant has payload(s) or is a record, not a simple enum
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): tabIndex -- int -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    rel: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): ariaCurrent -- [#page | #step | #location | #date | #time | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): ariaHaspopup -- [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): onCopy -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onCut -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onPaste -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onInput -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSubmit -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyPress -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyUp -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onContextMenu -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDoubleClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrag -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrop -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseDown -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseEnter -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseMove -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOut -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOver -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseUp -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onScroll -- ReactEvent.UI.t => unit -- event handler, code-only
    // TODO (unsupported): onWheel -- ReactEvent.Wheel.t => unit -- event handler, code-only
    // TODO (unsupported): skeleton -- ButtonV2Types.buttonSkeleton -- variant has payload(s) or is a record, not a simple enum
    form: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): formAction -- CommonTypes.buttonV2FormAction<'a> -- not confidently classifiable
    formEncType: { figmaProp: null /* TODO */, kind: 'string' },
    formMethod: { figmaProp: null /* TODO */, kind: 'string' },
    formNoValidate: { figmaProp: null /* TODO */, kind: 'bool' },
    formTarget: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): value -- CommonTypes.stringOrNumberOrStringArray -- variant has payload(s) or is a record, not a simple enum
    buttonGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'ButtonTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'ButtonTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    buttonType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Secondary', // ReScript: Secondary (bound value "secondary")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Danger', // ReScript: Danger (bound value "danger")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Success', // ReScript: Success (bound value "success")
      },
    },
    loading: { figmaProp: null /* TODO */, kind: 'bool' },
    state: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Hover', // ReScript: Hover (bound value "hover")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Active', // ReScript: Active (bound value "active")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Disabled', // ReScript: Disabled (bound value "disabled")
      },
    },
  },
}
