// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/KeyValuePairLayout.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'KeyValuePairLayout',
  id: 'keyValuePairLayout',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): containerStyle -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): keyContainerStyle -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): valueContainerStyle -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): keySlotStyle -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): keyContent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): valueContent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): keySlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): valueLeftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): valueRightSlot -- React.element (slot/children) -- needs manual handling
    dataKeyValuePair: { figmaProp: null /* TODO */, kind: 'string' },
    ariaLabel: { figmaProp: null /* TODO */, kind: 'string' },
    keyDataElement: { figmaProp: null /* TODO */, kind: 'string' },
    keyDataId: { figmaProp: null /* TODO */, kind: 'string' },
    valueDataElement: { figmaProp: null /* TODO */, kind: 'string' },
    valueDataId: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
