// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/KeyValuePairV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'KeyValuePairV2',
  id: 'keyValuePairV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    keyString: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slots -- KeyValuePairV2Types.keyValuePairV2SlotsConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): keyValuePairState -- KeyValuePairV2Types.keyValuePairV2StateType -- variant has payload(s) or is a record, not a simple enum
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    textOverflow: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Wrap', // ReScript: Wrap (bound value "wrap")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Truncate', // ReScript: Truncate (bound value "truncate")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.WrapClamp', // ReScript: WrapClamp (bound value "wrap-clamp")
      },
    },
    // TODO (unsupported): maxLines -- float -- not confidently classifiable
    showTooltipOnTruncate: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
