// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/LinearProgressBarV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'LinearProgressBarV2',
  id: 'linearProgressBarV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): value -- float -- not confidently classifiable
    // TODO (unsupported): min -- float -- not confidently classifiable
    // TODO (unsupported): max -- float -- not confidently classifiable
    ariaLabel: { figmaProp: null /* TODO */, kind: 'string' },
    ariaLabelledby: { figmaProp: null /* TODO */, kind: 'string' },
    showLabel: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): tokens -- ProgressBarV2Types.progressBarV2TokenType -- variant has payload(s) or is a record, not a simple enum
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ProgressBarV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'ProgressBarV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'ProgressBarV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    appearance: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ProgressBarV2Types.Solid', // ReScript: Solid (bound value "solid")
        // TODO_FIGMA_KEY: 'ProgressBarV2Types.Segmented', // ReScript: Segmented (bound value "segmented")
      },
    },
  },
}
