// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MenuV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MenuV2',
  id: 'menuV2',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): items -- array<MenuV2Types.menuV2GroupType> -- not confidently classifiable
    // TODO (unsupported): dimensions -- MenuV2Types.menuV2Dimensions -- variant has payload(s) or is a record, not a simple enum
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): searchSortFn -- (array<MenuV2Types.menuV2ItemType>, string) => array<MenuV2Types.menuV2ItemType> -- event handler, code-only
    // TODO (unsupported): onEnter -- (string, array<MenuV2Types.menuV2GroupType>) => unit -- event handler, code-only
    enableVirtualScrolling: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualScrolling -- MenuV2Types.menuV2VirtualScrollingConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    asModal: { figmaProp: null /* TODO */, kind: 'bool' },
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MenuV2Types.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'MenuV2Types.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'MenuV2Types.End', // ReScript: End (bound value "end")
      },
    },
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MenuV2Types.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'MenuV2Types.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'MenuV2Types.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'MenuV2Types.Bottom', // ReScript: Bottom (bound value "bottom")
      },
    },
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    // TODO (unsupported): collisionBoundaryRef -- MenuV2Types.MenuV2CollisionBoundaryRef.t=?, // ⓘ was `HTMLElement | HTMLElement[]` — opaque; build with MenuV2CollisionBoundaryRef.fromHTMLElement / MenuV2CollisionBoundaryRef.fromHTMLElements -- not confidently classifiable
    // TODO (unsupported): triggerProps -- ReactTypes.reactPrimaryActionButtonPropsConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
