// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MenuV2Content.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MenuV2Content',
  id: 'menuV2Content',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): filteredItems -- array<MenuV2Types.menuV2GroupType> -- not confidently classifiable
    // TODO (unsupported): menuTokens -- MenuV2Types.menuV2TokensType -- variant has payload(s) or is a record, not a simple enum
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    searchText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onSearchTextChange -- string => unit -- event handler, code-only
    // TODO (unsupported): onEnter -- unit => unit -- event handler, code-only
    maxHeight: { figmaProp: null /* TODO */, kind: 'string' },
    minHeight: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    enableVirtualScrolling: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualScrolling -- MenuV2Types.menuV2VirtualScrollingConfig -- variant has payload(s) or is a record, not a simple enum
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.End', // ReScript: End (bound value "end")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Start', // ReScript: Start (bound value "start")
      },
    },
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    // TODO (unsupported): collisionBoundaryRef -- MenuV2Types.MenuV2CollisionBoundaryRef.t=?, // ⓘ was `HTMLElement | HTMLElement[]` — opaque; build with MenuV2CollisionBoundaryRef.fromHTMLElement / MenuV2CollisionBoundaryRef.fromHTMLElements -- not confidently classifiable
    // TODO (unsupported): onInteractOutside -- JSON.t => unit -- event handler, code-only
    // TODO (unsupported): onPointerDownOutside -- JSON.t => unit -- event handler, code-only
    // TODO (unsupported): onFocusCapture -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
  },
}
