// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Menu.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Menu',
  id: 'menu',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): items -- array<MenuTypes.menuGroupType> -- not confidently classifiable
    // TODO (unsupported): maxHeight -- float -- not confidently classifiable
    // TODO (unsupported): minHeight -- float -- not confidently classifiable
    // TODO (unsupported): maxWidth -- float -- not confidently classifiable
    // TODO (unsupported): minWidth -- float -- not confidently classifiable
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    enableVirtualScrolling: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualItemHeight -- MenuTypes.menuItemTypeVirtualItemHeight -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): virtualOverscan -- float -- not confidently classifiable
    // TODO (unsupported): virtualScrollThreshold -- float -- not confidently classifiable
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    asModal: { figmaProp: null /* TODO */, kind: 'bool' },
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MenuTypes.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'MenuTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'MenuTypes.End', // ReScript: End (bound value "end")
      },
    },
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MenuTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'MenuTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'MenuTypes.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'MenuTypes.Bottom', // ReScript: Bottom (bound value "bottom")
      },
    },
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    // TODO (unsupported): collisonBoundaryRef -- ChatInputTypes.ChatInputOverflowMenuPropsCollisonBoundaryRef.t, // ⓘ was `Element | Element[]` — opaque; build with ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElement / ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElements -- not confidently classifiable
    // TODO (unsupported): skeleton -- MenuTypes.menuSkeletonProps -- variant has payload(s) or is a record, not a simple enum
  },
}
