// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MobileChatInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MobileChatInputV2',
  id: 'mobileChatInputV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    // TODO (unsupported): topContent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): secondaryAction -- React.element (slot/children) -- needs manual handling
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): attachedFiles -- array<EditorSharedTypes.chatInputV2AttachedFile> -- not confidently classifiable
    // TODO (unsupported): handleAttachClick -- unit => unit -- event handler, code-only
    // TODO (unsupported): onFileRemove -- string => unit -- event handler, code-only
    // TODO (unsupported): onFileClick -- EditorSharedTypes.chatInputV2AttachedFile => unit -- event handler, code-only
    // TODO (unsupported): onSecondaryActionClick -- unit => unit -- event handler, code-only
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): webTokens -- EditorSharedTypes.chatInputV2TokensType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onEnter -- unit => unit -- event handler, code-only
  },
}
