// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MobileDrawerPresets.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MobileDrawerPresets',
  id: 'mobileDrawerPresets',
  imports: ['open RescriptBlend'],
  props: {
    drawerOpen: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): setDrawerOpen -- bool => unit -- event handler, code-only
    // TODO (unsupported): renderTrigger -- unit => React.element -- event handler, code-only
    showPresets: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): availablePresets -- array<DateRangePickerTypes.dateRangePreset> -- not confidently classifiable
    activePreset: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Custom', // ReScript: Custom (bound value "custom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Today', // ReScript: Today (bound value "today")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Yesterday', // ReScript: Yesterday (bound value "yesterday")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Tomorrow', // ReScript: Tomorrow (bound value "tomorrow")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last30Minutes', // ReScript: Last30Minutes (bound value "last30Minutes")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last1Hour', // ReScript: Last1Hour (bound value "last1Hour")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last6Hours', // ReScript: Last6Hours (bound value "last6Hours")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last24Hours', // ReScript: Last24Hours (bound value "last24Hours")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last7Days', // ReScript: Last7Days (bound value "last7Days")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last30Days', // ReScript: Last30Days (bound value "last30Days")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.ThisMonth', // ReScript: ThisMonth (bound value "thisMonth")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.LastMonth', // ReScript: LastMonth (bound value "lastMonth")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last3Months', // ReScript: Last3Months (bound value "last3Months")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Last12Months', // ReScript: Last12Months (bound value "last12Months")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Next7Days', // ReScript: Next7Days (bound value "next7Days")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Next30Days', // ReScript: Next30Days (bound value "next30Days")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Next3Months', // ReScript: Next3Months (bound value "next3Months")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Next12Months', // ReScript: Next12Months (bound value "next12Months")
      },
    },
    // TODO (unsupported): selectedRange -- DateRangePickerTypes.dateRange -- variant has payload(s) or is a record, not a simple enum
    startTime: { figmaProp: null /* TODO */, kind: 'string' },
    endTime: { figmaProp: null /* TODO */, kind: 'string' },
    dateFormat: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): handlePresetSelect -- DateRangePickerTypes.dateRangePreset => unit -- event handler, code-only
    // TODO (unsupported): handleStartTimeChange -- string => unit -- event handler, code-only
    // TODO (unsupported): handleEndTimeChange -- string => unit -- event handler, code-only
    // TODO (unsupported): setSelectedRange -- DateRangePickerTypes.dateRange => unit -- event handler, code-only
    // TODO (unsupported): setStartDate -- string => unit -- event handler, code-only
    // TODO (unsupported): setEndDate -- string => unit -- event handler, code-only
    // TODO (unsupported): handleCancel -- unit => unit -- event handler, code-only
    // TODO (unsupported): handleApply -- unit => unit -- event handler, code-only
    showCustomDropdownOnly: { figmaProp: null /* TODO */, kind: 'bool' },
    isDisabled: { figmaProp: null /* TODO */, kind: 'bool' },
    isApplyDisabled: { figmaProp: null /* TODO */, kind: 'bool' },
    applyDisabledMessage: { figmaProp: null /* TODO */, kind: 'string' },
    disableFutureDates: { figmaProp: null /* TODO */, kind: 'bool' },
    disablePastDates: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): maxYearOffset -- float -- not confidently classifiable
  },
}
