// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Modal.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Modal',
  id: 'modal',
  imports: ['open RescriptBlend'],
  props: {
    isOpen: { figmaProp: null /* TODO */, kind: 'bool' },
    isCustom: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    title: { figmaProp: null /* TODO */, kind: 'string' },
    subtitle: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): primaryAction -- ModalTypes.modalButtonAction -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- ModalTypes.modalButtonAction -- variant has payload(s) or is a record, not a simple enum
    showCloseButton: { figmaProp: null /* TODO */, kind: 'bool' },
    showHeader: { figmaProp: null /* TODO */, kind: 'bool' },
    showFooter: { figmaProp: null /* TODO */, kind: 'bool' },
    closeOnBackdropClick: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): customHeader -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): customFooter -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerRightSlot -- React.element (slot/children) -- needs manual handling
    showDivider: { figmaProp: null /* TODO */, kind: 'bool' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): skeleton -- ModalTypes.modalSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    maxHeight: { figmaProp: null /* TODO */, kind: 'string' },
    minHeight: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
