// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiValueInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiValueInputV2',
  id: 'multiValueInputV2',
  imports: ['open RescriptBlend'],
  props: {
    value: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): tags -- EditorSharedTypes.inputsV2TagsConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    // TODO (unsupported): onTagAdd -- string => unit -- event handler, code-only
    // TODO (unsupported): onTagRemove -- string => unit -- event handler, code-only
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
  },
}
