// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2SelectAllItem.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2SelectAllItem',
  id: 'multiSelectV2SelectAllItem',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): selected -- array<string> -- not confidently classifiable
    // TODO (unsupported): availableValues -- array<string> -- not confidently classifiable
    // TODO (unsupported): onSelectAll -- bool => unit -- event handler, code-only
    selectAllText: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
