// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2MenuHeader.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2MenuHeader',
  id: 'multiSelectV2MenuHeader',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): tokens -- EditorSharedTypes.multiSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    showSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): itemsCount -- float -- not confidently classifiable
    searchValue: { figmaProp: null /* TODO */, kind: 'string' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onSearchChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSearchArrowKeyToFirst -- unit => unit -- event handler, code-only
    showSelectAll: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): selected -- array<string> -- not confidently classifiable
    // TODO (unsupported): availableValues -- array<string> -- not confidently classifiable
    // TODO (unsupported): filteredItems -- array<EditorSharedTypes.multiSelectV2GroupType> -- not confidently classifiable
    // TODO (unsupported): onSelectAll -- (bool, array<EditorSharedTypes.multiSelectV2GroupType>) => unit -- event handler, code-only
    selectAllText: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
