// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelect.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelect',
  id: 'multiSelect',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): height -- float -- not confidently classifiable
    // TODO (unsupported): selectedValues -- array<string> -- not confidently classifiable
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    // TODO (unsupported): items -- array<MultiSelectTypes.multiSelectMenuGroupType> -- not confidently classifiable
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    selectionTagType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Count', // ReScript: Count (bound value "count")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Text', // ReScript: Text (bound value "text")
      },
    },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    enableSelectAll: { figmaProp: null /* TODO */, kind: 'bool' },
    selectAllText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): maxSelections -- float -- not confidently classifiable
    // TODO (unsupported): customTrigger -- React.element (slot/children) -- needs manual handling
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): maxTriggerWidth -- float -- not confidently classifiable
    // TODO (unsupported): minTriggerWidth -- float -- not confidently classifiable
    // TODO (unsupported): minMenuWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxMenuWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxMenuHeight -- float -- not confidently classifiable
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.End', // ReScript: End (bound value "end")
      },
    },
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Bottom', // ReScript: Bottom (bound value "bottom")
      },
    },
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    inline: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    showActionButtons: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): primaryAction -- MultiSelectTypes.multiSelectPrimaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- MultiSelectTypes.multiSelectSecondaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    showItemDividers: { figmaProp: null /* TODO */, kind: 'bool' },
    showHeaderBorder: { figmaProp: null /* TODO */, kind: 'bool' },
    fullWidth: { figmaProp: null /* TODO */, kind: 'bool' },
    enableVirtualization: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualListItemHeight -- float -- not confidently classifiable
    // TODO (unsupported): virtualListOverscan -- float -- not confidently classifiable
    // TODO (unsupported): itemsToRender -- float -- not confidently classifiable
    // TODO (unsupported): onEndReached -- unit => unit -- event handler, code-only
    // TODO (unsupported): endReachedThreshold -- float -- not confidently classifiable
    hasMore: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): loadingComponent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): skeleton -- MultiSelectTypes.multiSelectSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    allowCustomValue: { figmaProp: null /* TODO */, kind: 'bool' },
    customValueLabel: { figmaProp: null /* TODO */, kind: 'string' },
    showClearButton: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClearAllClick -- unit => unit -- event handler, code-only
    multiSelectGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'ButtonTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'ButtonTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): menuFooter -- React.element (slot/children) -- needs manual handling
  },
}
