// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2MenuItems.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2MenuItems',
  id: 'multiSelectV2MenuItems',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): filteredItems -- array<EditorSharedTypes.multiSelectV2GroupType> -- not confidently classifiable
    // TODO (unsupported): allItemsFlat -- array<EditorSharedTypes.multiSelectV2ItemType> -- not confidently classifiable
    // TODO (unsupported): selected -- array<string> -- not confidently classifiable
    // TODO (unsupported): onSelect -- string => unit -- event handler, code-only
    // TODO (unsupported): maxSelections -- float -- not confidently classifiable
    // TODO (unsupported): tokens -- EditorSharedTypes.multiSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SelectV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SelectV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'SelectV2Types.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
  },
}
