// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectTrigger.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectTrigger',
  id: 'multiSelectTrigger',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): selectedValues -- array<string> -- not confidently classifiable
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    isSmallScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    name: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    selectionTagType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Count', // ReScript: Count (bound value "count")
        // TODO_FIGMA_KEY: 'MultiSelectTypes.Text', // ReScript: Text (bound value "text")
      },
    },
    // TODO (unsupported): valueLabelMap -- Dict.t<string> -- not confidently classifiable
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): multiSelectTokens -- MultiSelectTypes.multiSelectTokensType -- variant has payload(s) or is a record, not a simple enum
    inline: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): maxTriggerWidth -- float -- not confidently classifiable
    // TODO (unsupported): minTriggerWidth -- float -- not confidently classifiable
  },
}
