// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2Trigger.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2Trigger',
  id: 'multiSelectV2Trigger',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): selectedValues -- array<string> -- not confidently classifiable
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'SelectV2Types.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SelectV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SelectV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    isSmallScreen: { figmaProp: null /* TODO */, kind: 'bool' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    selectionTagType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Count', // ReScript: Count (bound value "count")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Text', // ReScript: Text (bound value "text")
      },
    },
    // TODO (unsupported): valueLabelMap -- Dict.t<string> -- not confidently classifiable
    // TODO (unsupported): multiSelectTokens -- EditorSharedTypes.multiSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    inline: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): triggerDimensions -- EditorSharedTypes.selectV2TriggerDimensions -- variant has payload(s) or is a record, not a simple enum
    borderRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderRight: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
