// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2MenuActions.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2MenuActions',
  id: 'multiSelectV2MenuActions',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): tokens -- EditorSharedTypes.multiSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): primaryAction -- EditorSharedTypes.multiSelectV2PrimaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- EditorSharedTypes.multiSelectV2SecondaryActionConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): selected -- array<string> -- not confidently classifiable
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
  },
}
