// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/MultiSelectV2MenuVirtualList.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'MultiSelectV2MenuVirtualList',
  id: 'multiSelectV2MenuVirtualList',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): flattenedItems -- array<EditorSharedTypes.flattenedMultiSelectV2Item> -- not confidently classifiable
    // TODO (unsupported): itemIndexMap -- Map.t<string, float> -- not confidently classifiable
    // TODO (unsupported): allItemsFlat -- array<EditorSharedTypes.multiSelectV2ItemType> -- not confidently classifiable
    // TODO (unsupported): selected -- array<string> -- not confidently classifiable
    // TODO (unsupported): onSelect -- string => unit -- event handler, code-only
    // TODO (unsupported): maxSelections -- float -- not confidently classifiable
    // TODO (unsupported): tokens -- EditorSharedTypes.multiSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): height -- float -- not confidently classifiable
    // TODO (unsupported): itemHeight -- float -- not confidently classifiable
    // TODO (unsupported): overscan -- float -- not confidently classifiable
    // TODO (unsupported): onEndReached -- unit => unit -- event handler, code-only
    // TODO (unsupported): endReachedThreshold -- float -- not confidently classifiable
    hasMore: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
