// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/NestedSingleSelectDrawer.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'NestedSingleSelectDrawer',
  id: 'nestedSingleSelectDrawer',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    heading: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): items -- array<DrawerTypes.drawerItemsConfig> -- not confidently classifiable
    selectedValue: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onValueChange -- string => unit -- event handler, code-only
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    cancelText: { figmaProp: null /* TODO */, kind: 'string' },
    confirmText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onCancel -- unit => unit -- event handler, code-only
    // TODO (unsupported): onConfirm -- unit => unit -- event handler, code-only
    showCancelButton: { figmaProp: null /* TODO */, kind: 'bool' },
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    modal: { figmaProp: null /* TODO */, kind: 'bool' },
    dismissible: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): mobileOffset -- DrawerTypes.drawerMobileOffsetConfig -- variant has payload(s) or is a record, not a simple enum
    className: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
  },
}
