// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/NumberInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'NumberInputV2',
  id: 'numberInputV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): slot -- EditorSharedTypes.inputsV2SlotConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): value -- Nullable.t<float> -- not confidently classifiable
    unit: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): min -- float -- not confidently classifiable
    // TODO (unsupported): max -- float -- not confidently classifiable
    // TODO (unsupported): step -- float -- not confidently classifiable
    // TODO (unsupported): error -- EditorSharedTypes.inputsV2ErrorConfig -- variant has payload(s) or is a record, not a simple enum
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): label -- EditorSharedTypes.inputsV2LabelConfig -- variant has payload(s) or is a record, not a simple enum
    unitDirection: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    helpIconText: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    preventNegative: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
  },
}
