// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/NumberInput.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'NumberInput',
  id: 'numberInput',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): value -- Nullable.t<float> -- not confidently classifiable
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): step -- float -- not confidently classifiable
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'InputsTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    preventNegative: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
  },
}
