// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/OTPInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'OTPInputV2',
  id: 'oTPInputV2',
  imports: ['open RescriptBlend'],
  props: {
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): length -- float -- not confidently classifiable
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    form: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
