// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/PivotTableModal.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'PivotTableModal',
  id: 'pivotTableModal',
  imports: ['open JuspayRescriptBlend'],
  props: {
    isOpen: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    // TODO (unsupported): data -- array<'a> -- not confidently classifiable
    // TODO (unsupported): columns -- array<DataTableTypes.ColumnDefinition2.t>, // ⓘ was `ColumnDefinition<T>` — opaque; build with ColumnDefinition2.fromDataTableColumnsTextConfig / ColumnDefinition2.fromDataTableColumnsNumberConfig / ColumnDefinition2.fromDataTableColumnsAvatarConfig / ColumnDefinition2.fromDataTableColumnsTagConfig / ColumnDefinition2.fromDataTableColumnsProgressConfig / ColumnDefinition2.fromDataTableColumnsDropdownConfig / ColumnDefinition2.fromDataTableColumnsDateConfig / ColumnDefinition2.fromDataTableColumnsSliderConfig / ColumnDefinition2.fromDataTableColumnsReactElementConfig / ColumnDefinition2.fromDataTableColumnsFilterTypeConfig -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    showExport: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): initialConfig -- DataTableTypes.dataTablePivotTableConfigInitialConfigConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): previewColumns -- array<DataTableTypes.dataTablePivotTableConfigPreviewColumnsConfig> -- not confidently classifiable
    // TODO (unsupported): previewRows -- array<DataTableTypes.pivotPreviewRow> -- not confidently classifiable
    // TODO (unsupported): onConfigChange -- DataTableTypes.dataTablePivotTableConfigOnConfigChangeConfig => unit -- event handler, code-only
    // TODO (unsupported): onExport -- DataTableTypes.dataTablePivotTableConfigOnConfigChangeConfig => unit -- event handler, code-only
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onTriggerClick -- unit => unit -- event handler, code-only
    // TODO (unsupported): availableAggregations -- array<DataTableTypes.pivotAggregationType> -- not confidently classifiable
  },
}
