// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/PopoverV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'PopoverV2',
  id: 'popoverV2',
  imports: ['open RescriptBlend'],
  props: {
    heading: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    showCloseButton: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    asModal: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): primaryAction -- PopoverV2Types.popoverV2ActionType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- PopoverV2Types.popoverV2ActionType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'PopoverV2Types.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Left', // ReScript: Left (bound value "left")
      },
    },
    align: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'PopoverV2Types.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'PopoverV2Types.End', // ReScript: End (bound value "end")
      },
    },
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'PopoverV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'PopoverV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    avoidCollisions: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): skeleton -- PopoverV2Types.popoverV2SkeletonProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): width -- float -- not confidently classifiable
    // TODO (unsupported): maxWidth -- float -- not confidently classifiable
    // TODO (unsupported): minWidth -- float -- not confidently classifiable
    // TODO (unsupported): height -- float -- not confidently classifiable
    // TODO (unsupported): minHeight -- float -- not confidently classifiable
    // TODO (unsupported): maxHeight -- float -- not confidently classifiable
  },
}
