// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Popover.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Popover',
  id: 'popover',
  imports: ['open RescriptBlend'],
  props: {
    heading: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    showCloseButton: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    asModal: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): primaryAction -- PopoverTypes.popoverActionType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryAction -- PopoverTypes.popoverActionType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    align: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.End', // ReScript: End (bound value "end")
        // TODO_FIGMA_KEY: 'DateRangePickerTypes.Start', // ReScript: Start (bound value "start")
      },
    },
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    // TODO (unsupported): width -- float -- not confidently classifiable
    // TODO (unsupported): minWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxWidth -- float -- not confidently classifiable
    // TODO (unsupported): height -- float -- not confidently classifiable
    // TODO (unsupported): minHeight -- float -- not confidently classifiable
    // TODO (unsupported): maxHeight -- float -- not confidently classifiable
    // TODO (unsupported): zIndex -- int -- not confidently classifiable
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'PopoverTypes.Small', // ReScript: Small (bound value "small")
        // TODO_FIGMA_KEY: 'PopoverTypes.Medium', // ReScript: Medium (bound value "medium")
      },
    },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    shadow: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'PopoverTypes.Xs', // ReScript: Xs (bound value "xs")
        // TODO_FIGMA_KEY: 'PopoverTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'PopoverTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'PopoverTypes.Lg', // ReScript: Lg (bound value "lg")
        // TODO_FIGMA_KEY: 'PopoverTypes.Xl', // ReScript: Xl (bound value "xl")
        // TODO_FIGMA_KEY: 'PopoverTypes.V2xl', // ReScript: V2xl (bound value "2xl")
        // TODO_FIGMA_KEY: 'PopoverTypes.Full', // ReScript: Full (bound value "full")
      },
    },
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    avoidCollisions: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): skeleton -- PopoverTypes.popoverSkeletonProps -- variant has payload(s) or is a record, not a simple enum
  },
}
