// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ProgressBar.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ProgressBar',
  id: 'progressBar',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): value -- float -- not confidently classifiable
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Solid', // ReScript: Solid (bound value "solid")
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Segmented', // ReScript: Segmented (bound value "segmented")
        // TODO_FIGMA_KEY: 'ProgressBarTypes.Circular', // ReScript: Circular (bound value "circular")
      },
    },
    showLabel: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): min -- float -- not confidently classifiable
    // TODO (unsupported): max -- float -- not confidently classifiable
  },
}
