// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/RadioGroup.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'RadioGroup',
  id: 'radioGroup',
  imports: ['open RescriptBlend'],
  props: {
    id: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    defaultValue: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onChange -- string => unit -- event handler, code-only
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
