// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/renderButtonContent.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'renderButtonContent',
  id: 'renderButtonContent',
  imports: ['open RescriptBlend'],
  props: {
    isLoading: { figmaProp: null /* TODO */, kind: 'bool' },
    isSkeleton: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    state: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Hover', // ReScript: Hover (bound value "hover")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Active', // ReScript: Active (bound value "active")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Disabled', // ReScript: Disabled (bound value "disabled")
      },
    },
    buttonType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Secondary', // ReScript: Secondary (bound value "secondary")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Danger', // ReScript: Danger (bound value "danger")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Success', // ReScript: Success (bound value "success")
      },
    },
    subType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'ButtonV2Types.IconOnly', // ReScript: IconOnly (bound value "iconOnly")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Inline', // ReScript: Inline (bound value "inline")
      },
    },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'ButtonV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    text: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): leftSlot -- ButtonV2Types.buttonSlot -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rightSlot -- ButtonV2Types.buttonSlot -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): tokens -- ButtonV2Types.buttonV2ResponsiveButtonV2TokensSmConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
