// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/ResponsiveText.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'ResponsiveText',
  id: 'responsiveText',
  imports: ['open JuspayRescriptBlend'],
  props: {
    children: { figmaProp: null /* TODO */, kind: 'string' },
    fontSize: { figmaProp: null /* TODO */, kind: 'string' },
    color: { figmaProp: null /* TODO */, kind: 'string' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    fontWeight: { figmaProp: null /* TODO */, kind: 'string' },
    textOverflow: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Wrap', // ReScript: Wrap (bound value "wrap")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.Truncate', // ReScript: Truncate (bound value "truncate")
        // TODO_FIGMA_KEY: 'KeyValuePairV2Types.WrapClamp', // ReScript: WrapClamp (bound value "wrap-clamp")
      },
    },
    // TODO (unsupported): maxLines -- float -- not confidently classifiable
    showTooltipOnTruncate: { figmaProp: null /* TODO */, kind: 'bool' },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    slotPresent: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
