// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SankeyLink.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SankeyLink',
  id: 'sankeyLink',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): sourceX -- float -- not confidently classifiable
    // TODO (unsupported): targetX -- float -- not confidently classifiable
    // TODO (unsupported): sourceY -- float -- not confidently classifiable
    // TODO (unsupported): targetY -- float -- not confidently classifiable
    // TODO (unsupported): sourceControlX -- float -- not confidently classifiable
    // TODO (unsupported): targetControlX -- float -- not confidently classifiable
    // TODO (unsupported): linkWidth -- float -- not confidently classifiable
    // TODO (unsupported): index -- int -- not confidently classifiable
    // TODO (unsupported): payload -- ChartsTypes.sankeyLink -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): linkColors -- array<ChartsTypes.stringOrChartsColorsConfig> -- not confidently classifiable
    // TODO (unsupported): onMouseEnter -- (ChartsTypes.sankeyTooltipData, ReactEvent.Mouse.t) => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- unit => unit -- event handler, code-only
  },
}
