// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SankeyNode.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SankeyNode',
  id: 'sankeyNode',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): x -- float -- not confidently classifiable
    // TODO (unsupported): y -- float -- not confidently classifiable
    // TODO (unsupported): width -- float -- not confidently classifiable
    // TODO (unsupported): height -- float -- not confidently classifiable
    // TODO (unsupported): index -- int -- not confidently classifiable
    // TODO (unsupported): payload -- ChartsTypes.chartsPayloadConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): containerWidth -- float -- not confidently classifiable
    // TODO (unsupported): nodeColors -- array<ChartsTypes.stringOrChartsColorsConfig> -- not confidently classifiable
    // TODO (unsupported): onMouseEnter -- (ChartsTypes.sankeyTooltipData, ReactEvent.Mouse.t) => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- unit => unit -- event handler, code-only
  },
}
