// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SearchInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SearchInputV2',
  id: 'searchInputV2',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    allowClear: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClear -- unit => unit -- event handler, code-only
    clearIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
  },
}
