// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SelectItemV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SelectItemV2',
  id: 'selectItemV2',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): item -- SelectV2Types.selectV2ItemType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): onSelect -- string => unit -- event handler, code-only
    // TODO (unsupported): itemTokens -- SelectV2Types.selectV2MenuItemTokensBase -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): index -- int -- not confidently classifiable
    selectedPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.None', // ReScript: None (bound value "none")
        // TODO_FIGMA_KEY: 'SelectV2Types.Middle', // ReScript: Middle (bound value "middle")
        // TODO_FIGMA_KEY: 'SelectV2Types.First', // ReScript: First (bound value "first")
        // TODO_FIGMA_KEY: 'SelectV2Types.Last', // ReScript: Last (bound value "last")
        // TODO_FIGMA_KEY: 'SelectV2Types.Only', // ReScript: Only (bound value "only")
      },
    },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    mode: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Single', // ReScript: Single (bound value "single")
        // TODO_FIGMA_KEY: 'SelectV2Types.Multi', // ReScript: Multi (bound value "multi")
      },
    },
    selected: { figmaProp: null /* TODO */, kind: 'string' },
    showCheckmark: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): selectedValues -- array<string> -- not confidently classifiable
  },
}
