// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SidebarV2Footer.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SidebarV2Footer',
  id: 'sidebarV2Footer',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): footer -- React.element (slot/children) -- needs manual handling
    sidebarState: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SidebarV2Types.Expanded', // ReScript: Expanded (bound value "expanded")
        // TODO_FIGMA_KEY: 'SidebarV2Types.Collapsed', // ReScript: Collapsed (bound value "collapsed")
        // TODO_FIGMA_KEY: 'SidebarV2Types.Intermediate', // ReScript: Intermediate (bound value "intermediate")
      },
    },
    // TODO (unsupported): tokens -- SidebarV2Types.sidebarV2TokensType -- variant has payload(s) or is a record, not a simple enum
  },
}
