// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SidebarV2Header.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SidebarV2Header',
  id: 'sidebarV2Header',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): sidebarTopSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): merchantInfo -- SidebarV2Types.sidebarV2MerchantInfoConfig -- variant has payload(s) or is a record, not a simple enum
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    isScrolled: { figmaProp: null /* TODO */, kind: 'bool' },
    sidebarCollapseKey: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onToggle -- unit => unit -- event handler, code-only
    sidebarNavId: { figmaProp: null /* TODO */, kind: 'string' },
    hideToggleButton: { figmaProp: null /* TODO */, kind: 'bool' },
    iconOnlyMode: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): tokens -- SidebarV2Types.sidebarV2TokensType -- variant has payload(s) or is a record, not a simple enum
  },
}
