// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SidebarV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SidebarV2',
  id: 'sidebarV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    height: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): data -- Nullable.t<array<DirectoryTypes.directoryData>> -- not confidently classifiable
    // TODO (unsupported): secondarySidebar -- SidebarV2Types.secondarySidebarInfo -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): topbar -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): footer -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): sidebarTopSlot -- React.element (slot/children) -- needs manual handling
    sidebarCollapseKey: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): merchantInfo -- SharedTypes.merchantInfo -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rightActions -- React.element (slot/children) -- needs manual handling
    enableTopbarAutoHide: { figmaProp: null /* TODO */, kind: 'bool' },
    isTopbarVisible: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onTopbarVisibilityChange -- bool => unit -- event handler, code-only
    defaultIsTopbarVisible: { figmaProp: null /* TODO */, kind: 'bool' },
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onExpandedChange -- bool => unit -- event handler, code-only
    // TODO (unsupported): onSidebarStateChange -- SidebarV2Types.sidebarV2OnSidebarStateChange => unit -- event handler, code-only
    defaultIsExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    showMobilePrimaryActionButton: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): mobilePrimaryActionButtonProps -- ReactTypes.reactPrimaryActionButtonPropsConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): activeItem -- Nullable.t<string> -- not confidently classifiable
    // TODO (unsupported): onActiveItemChange -- Nullable.t<string> => unit -- event handler, code-only
    // TODO (unsupported): defaultActiveItem -- Nullable.t<string> -- not confidently classifiable
  },
}
