// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SingleSelectV2Menu.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SingleSelectV2Menu',
  id: 'singleSelectV2Menu',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): items -- array<EditorSharedTypes.singleSelectV2GroupType> -- not confidently classifiable
    selected: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onSelect -- string => unit -- event handler, code-only
    // TODO (unsupported): trigger -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): menuDimensions -- EditorSharedTypes.selectV2MenuDimensions -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): search -- EditorSharedTypes.selectV2SearchConfig -- variant has payload(s) or is a record, not a simple enum
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): menuPosition -- EditorSharedTypes.selectV2MenuPosition -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): collisionBoundary -- ChatInputTypes.ChatInputOverflowMenuPropsCollisonBoundaryRef.t=?, // ⓘ was `Element | Element[]` — opaque; build with ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElement / ChatInputOverflowMenuPropsCollisonBoundaryRef.fromElements -- not confidently classifiable
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SelectV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SelectV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'SelectV2Types.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    enableVirtualization: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualListItemHeight -- float -- not confidently classifiable
    // TODO (unsupported): virtualListOverscan -- float -- not confidently classifiable
    // TODO (unsupported): onEndReached -- unit => unit -- event handler, code-only
    // TODO (unsupported): endReachedThreshold -- float -- not confidently classifiable
    hasMore: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): loadingComponent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): skeleton -- SelectV2Types.selectV2SkeletonProps -- variant has payload(s) or is a record, not a simple enum
    allowCustomValue: { figmaProp: null /* TODO */, kind: 'bool' },
    customValueLabel: { figmaProp: null /* TODO */, kind: 'string' },
    menuId: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): menuFooter -- React.element (slot/children) -- needs manual handling
  },
}
