// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SingleSelect.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SingleSelect',
  id: 'singleSelect',
  imports: ['open JuspayRescriptBlend'],
  props: {
    label: { figmaProp: null /* TODO */, kind: 'string' },
    subLabel: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    helpIconText: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): items -- array<SingleSelectTypes.selectMenuGroupTypeSingleSelect> -- not confidently classifiable
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    selected: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onSelect -- string => unit -- event handler, code-only
    enableSearch: { figmaProp: null /* TODO */, kind: 'bool' },
    searchPlaceholder: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): customTrigger -- React.element (slot/children) -- needs manual handling
    useDrawerOnMobile: { figmaProp: null /* TODO */, kind: 'bool' },
    alignment: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.End', // ReScript: End (bound value "end")
      },
    },
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'SingleSelectTypes.Bottom', // ReScript: Bottom (bound value "bottom")
      },
    },
    // TODO (unsupported): sideOffset -- float -- not confidently classifiable
    // TODO (unsupported): alignOffset -- float -- not confidently classifiable
    // TODO (unsupported): minMenuWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxMenuWidth -- float -- not confidently classifiable
    // TODO (unsupported): maxMenuHeight -- float -- not confidently classifiable
    inline: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    fullWidth: { figmaProp: null /* TODO */, kind: 'bool' },
    enableVirtualization: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): virtualListItemHeight -- float -- not confidently classifiable
    // TODO (unsupported): virtualListOverscan -- float -- not confidently classifiable
    // TODO (unsupported): onEndReached -- unit => unit -- event handler, code-only
    // TODO (unsupported): endReachedThreshold -- float -- not confidently classifiable
    hasMore: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): loadingComponent -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): skeleton -- SingleSelectTypes.singleSelectSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxTriggerWidth -- float -- not confidently classifiable
    // TODO (unsupported): minTriggerWidth -- float -- not confidently classifiable
    allowCustomValue: { figmaProp: null /* TODO */, kind: 'bool' },
    customValueLabel: { figmaProp: null /* TODO */, kind: 'string' },
    singleSelectGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'ButtonTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'ButtonTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    allowDeselect: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): menuFooter -- React.element (slot/children) -- needs manual handling
  },
}
