// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SingleSelectV2Trigger.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SingleSelectV2Trigger',
  id: 'singleSelectV2Trigger',
  imports: ['open RescriptBlend'],
  props: {
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SelectV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SelectV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    selected: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): valueLabelMap -- Dict.t<string> -- not confidently classifiable
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectV2Types.Container', // ReScript: Container (bound value "container")
        // TODO_FIGMA_KEY: 'SelectV2Types.NoContainer', // ReScript: NoContainer (bound value "no-container")
      },
    },
    isSmallScreenWithLargeSize: { figmaProp: null /* TODO */, kind: 'bool' },
    isItemSelected: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): singleSelectTokens -- EditorSharedTypes.singleSelectV2TokensType -- variant has payload(s) or is a record, not a simple enum
    inline: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): triggerDimensions -- EditorSharedTypes.selectV2TriggerDimensions -- variant has payload(s) or is a record, not a simple enum
    singleSelectGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'ButtonTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'ButtonTypes.Right', // ReScript: Right (bound value "right")
      },
    },
    borderRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderRight: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
