// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Skeleton.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Skeleton',
  id: 'skeleton',
  imports: ['open JuspayRescriptBlend'],
  props: {
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Pulse', // ReScript: Pulse (bound value "pulse")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Wave', // ReScript: Wave (bound value "wave")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Shimmer', // ReScript: Shimmer (bound value "shimmer")
      },
    },
    loading: { figmaProp: null /* TODO */, kind: 'bool' },
    boxShadow: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): width -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    borderRadius: { figmaProp: null /* TODO */, kind: 'string' },
    letterSpacing: { figmaProp: null /* TODO */, kind: 'string' },
    fontSize: { figmaProp: null /* TODO */, kind: 'string' },
    lineHeight: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): size -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    display: { figmaProp: null /* TODO */, kind: 'string' },
    fontWeight: { figmaProp: null /* TODO */, kind: 'string' },
    opacity: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): height -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    gap: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): padding -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): margin -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    color: { figmaProp: null /* TODO */, kind: 'string' },
    zIndex: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): minWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    backgroundColor: { figmaProp: null /* TODO */, kind: 'string' },
    border: { figmaProp: null /* TODO */, kind: 'string' },
    hidden: { figmaProp: null /* TODO */, kind: 'bool' },
    inset: { figmaProp: null /* TODO */, kind: 'string' },
    borderBottom: { figmaProp: null /* TODO */, kind: 'string' },
    outline: { figmaProp: null /* TODO */, kind: 'string' },
    transition: { figmaProp: null /* TODO */, kind: 'string' },
    top: { figmaProp: null /* TODO */, kind: 'string' },
    left: { figmaProp: null /* TODO */, kind: 'string' },
    outlineOffset: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): marginLeft -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingTop -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingRight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingBottom -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingLeft -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxHeight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    bottom: { figmaProp: null /* TODO */, kind: 'string' },
    right: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): marginTop -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): marginRight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): marginBottom -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    flexDirection: { figmaProp: null /* TODO */, kind: 'string' },
    position: { figmaProp: null /* TODO */, kind: 'string' },
    justifyContent: { figmaProp: null /* TODO */, kind: 'string' },
    alignItems: { figmaProp: null /* TODO */, kind: 'string' },
    overflowX: { figmaProp: null /* TODO */, kind: 'string' },
    overflowY: { figmaProp: null /* TODO */, kind: 'string' },
    flexShrink: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): minHeight -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    transform: { figmaProp: null /* TODO */, kind: 'string' },
    textAlign: { figmaProp: null /* TODO */, kind: 'string' },
    cursor: { figmaProp: null /* TODO */, kind: 'string' },
    userSelect: { figmaProp: null /* TODO */, kind: 'string' },
    textTransform: { figmaProp: null /* TODO */, kind: 'string' },
    borderTop: { figmaProp: null /* TODO */, kind: 'string' },
    borderTopLeftRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderTopRightRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderBottomLeftRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderBottomRightRadius: { figmaProp: null /* TODO */, kind: 'string' },
    borderLeft: { figmaProp: null /* TODO */, kind: 'string' },
    borderRight: { figmaProp: null /* TODO */, kind: 'string' },
    backgroundSize: { figmaProp: null /* TODO */, kind: 'string' },
    backgroundImage: { figmaProp: null /* TODO */, kind: 'string' },
    overflow: { figmaProp: null /* TODO */, kind: 'string' },
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultValue -- CommonTypes.stringOrNumberOrStringArray -- variant has payload(s) or is a record, not a simple enum
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): tabIndex -- int -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    rel: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): ariaCurrent -- [#page | #step | #location | #date | #time | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): ariaHaspopup -- [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): onCopy -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onCut -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onPaste -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onInput -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSubmit -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyPress -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyUp -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onContextMenu -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDoubleClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrag -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrop -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseDown -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseEnter -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseMove -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOut -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOver -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseUp -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onScroll -- ReactEvent.UI.t => unit -- event handler, code-only
    // TODO (unsupported): onWheel -- ReactEvent.Wheel.t => unit -- event handler, code-only
    pointerEvents: { figmaProp: null /* TODO */, kind: 'string' },
    textOverflow: { figmaProp: null /* TODO */, kind: 'string' },
    whiteSpace: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): _hover -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): _focus -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): _active -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): _disabled -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): _visited -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): _focusVisible -- PrimitivesTypes.styledBlockProps -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingX -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): paddingY -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): marginX -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): marginY -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    flexWrap: { figmaProp: null /* TODO */, kind: 'string' },
    flexGrow: { figmaProp: null /* TODO */, kind: 'string' },
    flexBasis: { figmaProp: null /* TODO */, kind: 'string' },
    rowGap: { figmaProp: null /* TODO */, kind: 'string' },
    columnGap: { figmaProp: null /* TODO */, kind: 'string' },
    alignContent: { figmaProp: null /* TODO */, kind: 'string' },
    alignSelf: { figmaProp: null /* TODO */, kind: 'string' },
    justifySelf: { figmaProp: null /* TODO */, kind: 'string' },
    outlineColor: { figmaProp: null /* TODO */, kind: 'string' },
    outlineWidth: { figmaProp: null /* TODO */, kind: 'string' },
    outlineStyle: { figmaProp: null /* TODO */, kind: 'string' },
    contentCentered: { figmaProp: null /* TODO */, kind: 'bool' },
    willChange: { figmaProp: null /* TODO */, kind: 'string' },
    transformOrigin: { figmaProp: null /* TODO */, kind: 'string' },
    backfaceVisibility: { figmaProp: null /* TODO */, kind: 'string' },
    transitionDuration: { figmaProp: null /* TODO */, kind: 'string' },
    transitionTimingFunction: { figmaProp: null /* TODO */, kind: 'string' },
    transitionDelay: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    animate: { figmaProp: null /* TODO */, kind: 'bool' },
    shape: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Circle', // ReScript: Circle (bound value "circle")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Rectangle', // ReScript: Rectangle (bound value "rectangle")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Rounded', // ReScript: Rounded (bound value "rounded")
      },
    },
  },
}
