// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Slider.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Slider',
  id: 'slider',
  imports: ['open RescriptBlend'],
  props: {
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SliderTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SliderTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SliderTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    hidden: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultValue -- array<float> -- not confidently classifiable
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    dir: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'DistTypes.Ltr', // ReScript: Ltr (bound value "ltr")
        // TODO_FIGMA_KEY: 'DistTypes.Rtl', // ReScript: Rtl (bound value "rtl")
      },
    },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): tabIndex -- int -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    rel: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): ariaCurrent -- [#page | #step | #location | #date | #time | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): ariaHaspopup -- [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): onCopy -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onCut -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onPaste -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onInput -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSubmit -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyPress -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyUp -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onContextMenu -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDoubleClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrag -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrop -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseDown -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseEnter -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseMove -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOut -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOver -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseUp -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onScroll -- ReactEvent.UI.t => unit -- event handler, code-only
    // TODO (unsupported): onWheel -- ReactEvent.Wheel.t => unit -- event handler, code-only
    form: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): step -- float -- not confidently classifiable
    name: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): value -- array<float> -- not confidently classifiable
    inverted: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): max -- float -- not confidently classifiable
    // TODO (unsupported): min -- float -- not confidently classifiable
    asChild: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onValueChange -- array<float> => unit -- event handler, code-only
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SliderTypes.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'SliderTypes.Secondary', // ReScript: Secondary (bound value "secondary")
      },
    },
    // TODO (unsupported): valueFormat -- SliderTypes.sliderValueFormatConfig -- variant has payload(s) or is a record, not a simple enum
    showValueLabels: { figmaProp: null /* TODO */, kind: 'bool' },
    labelPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SliderTypes.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'SliderTypes.Bottom', // ReScript: Bottom (bound value "bottom")
        // TODO_FIGMA_KEY: 'SliderTypes.Inline', // ReScript: Inline (bound value "inline")
      },
    },
    orientation: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SliderTypes.Horizontal', // ReScript: Horizontal (bound value "horizontal")
        // TODO_FIGMA_KEY: 'SliderTypes.Vertical', // ReScript: Vertical (bound value "vertical")
      },
    },
    // TODO (unsupported): minStepsBetweenThumbs -- float -- not confidently classifiable
    // TODO (unsupported): onValueCommit -- array<float> => unit -- event handler, code-only
  },
}
