// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SnackbarV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SnackbarV2',
  id: 'snackbarV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    position: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SnackbarV2Types.TopLeft', // ReScript: TopLeft (bound value "top-left")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.TopRight', // ReScript: TopRight (bound value "top-right")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.BottomLeft', // ReScript: BottomLeft (bound value "bottom-left")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.BottomRight', // ReScript: BottomRight (bound value "bottom-right")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.TopCenter', // ReScript: TopCenter (bound value "top-center")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.BottomCenter', // ReScript: BottomCenter (bound value "bottom-center")
      },
    },
    dismissOnClickAway: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): maxWidth -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
  },
}
