// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SplitTag.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SplitTag',
  id: 'splitTag',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): primaryTag -- TagsTypes.tagsPrimaryTagConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): secondaryTag -- TagsTypes.tagsPrimaryTagConfig -- variant has payload(s) or is a record, not a simple enum
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagsTypes.Xs', // ReScript: Xs (bound value "xs")
        // TODO_FIGMA_KEY: 'TagsTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'TagsTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'TagsTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    shape: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagsTypes.Rounded', // ReScript: Rounded (bound value "rounded")
        // TODO_FIGMA_KEY: 'TagsTypes.Squarical', // ReScript: Squarical (bound value "squarical")
      },
    },
  },
}
