// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/StatCardV2Change.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'StatCardV2Change',
  id: 'statCardV2Change',
  imports: ['open RescriptBlend'],
  props: {
    changeValueText: { figmaProp: null /* TODO */, kind: 'string' },
    leftSymbol: { figmaProp: null /* TODO */, kind: 'string' },
    rightSymbol: { figmaProp: null /* TODO */, kind: 'string' },
    arrowDirection: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'StatCardV2Types.Up', // ReScript: Up (bound value "up")
        // TODO_FIGMA_KEY: 'StatCardV2Types.Down', // ReScript: Down (bound value "down")
      },
    },
    changeType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'StatCardV2Types.Increase', // ReScript: Increase (bound value "increase")
        // TODO_FIGMA_KEY: 'StatCardV2Types.Decrease', // ReScript: Decrease (bound value "decrease")
      },
    },
    // TODO (unsupported): tokens -- StatCardV2Types.statCardV2TokensType -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): tooltip -- React.element (slot/children) -- needs manual handling
    id: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
