// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/StatCard.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'StatCard',
  id: 'statCard',
  imports: ['open RescriptBlend'],
  props: {
    title: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): value -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): valueTooltip -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): change -- Nullable.t<StatCardTypes.statCardChange> -- not confidently classifiable
    subtitle: { figmaProp: null /* TODO */, kind: 'string' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'StatCardTypes.Line', // ReScript: Line (bound value "line")
        // TODO_FIGMA_KEY: 'StatCardTypes.Progress', // ReScript: Progress (bound value "progress")
        // TODO_FIGMA_KEY: 'StatCardTypes.Bar', // ReScript: Bar (bound value "bar")
        // TODO_FIGMA_KEY: 'StatCardTypes.Number', // ReScript: Number (bound value "number")
      },
    },
    // TODO (unsupported): chartData -- array<StatCardTypes.chartDataPoint> -- not confidently classifiable
    // TODO (unsupported): progressValue -- float -- not confidently classifiable
    titleIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    actionIcon: { figmaProp: null /* TODO */, kind: 'instanceSwap' },
    helpIconText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): dropdownProps -- SingleSelectTypes.singleSelectProps -- variant has payload(s) or is a record, not a simple enum
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): xAxis -- StatCardTypes.statCardAxisConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): yAxis -- StatCardTypes.statCardAxisConfig -- variant has payload(s) or is a record, not a simple enum
    valueFormatter: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ChartsTypes.DateTime', // ReScript: DateTime (bound value "dateTime")
        // TODO_FIGMA_KEY: 'ChartsTypes.Currency', // ReScript: Currency (bound value "currency")
        // TODO_FIGMA_KEY: 'ChartsTypes.Percentage', // ReScript: Percentage (bound value "percentage")
        // TODO_FIGMA_KEY: 'ChartsTypes.Number', // ReScript: Number (bound value "number")
      },
    },
    height: { figmaProp: null /* TODO */, kind: 'string' },
    direction: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'StatCardTypes.Vertical', // ReScript: Vertical (bound value "vertical")
        // TODO_FIGMA_KEY: 'StatCardTypes.Horizontal', // ReScript: Horizontal (bound value "horizontal")
      },
    },
    // TODO (unsupported): skeleton -- StatCardTypes.statCardSkeletonProps -- variant has payload(s) or is a record, not a simple enum
    dataDisplay: { figmaProp: null /* TODO */, kind: 'bool' },
    showBorder: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
