// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Stepper.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Stepper',
  id: 'stepper',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): steps -- array<StepperTypes.step> -- not confidently classifiable
    // TODO (unsupported): onStepClick -- float => unit -- event handler, code-only
    // TODO (unsupported): onSubstepClick -- (float, float) => unit -- event handler, code-only
    clickable: { figmaProp: null /* TODO */, kind: 'bool' },
    stepperType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'StepperTypes.Horizontal', // ReScript: Horizontal (bound value "horizontal")
        // TODO_FIGMA_KEY: 'StepperTypes.Vertical', // ReScript: Vertical (bound value "vertical")
      },
    },
  },
}
