// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/StyledToast.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'StyledToast',
  id: 'styledToast',
  imports: ['open JuspayRescriptBlend'],
  props: {
    header: { figmaProp: null /* TODO */, kind: 'string' },
    description: { figmaProp: null /* TODO */, kind: 'string' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SnackbarV2Types.Info', // ReScript: Info (bound value "info")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'SnackbarV2Types.Error', // ReScript: Error (bound value "error")
      },
    },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    // TODO (unsupported): actionButton -- SnackbarV2Types.snackbarV2Action -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): toastId -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    width: { figmaProp: null /* TODO */, kind: 'string' },
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    minWidth: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
