// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Switch.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Switch',
  id: 'switch',
  imports: ['open RescriptBlend'],
  props: {
    id: { figmaProp: null /* TODO */, kind: 'string' },
    checked: { figmaProp: null /* TODO */, kind: 'bool' },
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onChange -- bool => unit -- event handler, code-only
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SwitchTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SwitchTypes.Md', // ReScript: Md (bound value "md")
      },
    },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    subtext: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    name: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): maxLength -- SwitchTypes.switch_MaxLengthConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
