// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/SwitchV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'SwitchV2',
  id: 'switchV2',
  imports: ['open RescriptBlend'],
  props: {
    checked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onCheckedChange -- bool => unit -- event handler, code-only
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    subLabel: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SelectorV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'SelectorV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'SelectorV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): slot -- SelectorV2Types.selectorV2SlotConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): maxLength -- SelectorV2Types.selectorV2MaxLengthConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
