// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TabsTrigger.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TabsTrigger',
  id: 'tabsTrigger',
  imports: ['open RescriptBlend'],
  props: {
    hidden: { figmaProp: null /* TODO */, kind: 'bool' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
    // TODO (unsupported): children -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    defaultChecked: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): defaultValue -- CommonTypes.stringOrNumberOrStringArray -- variant has payload(s) or is a record, not a simple enum
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    id: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): tabIndex -- int -- not confidently classifiable
    title: { figmaProp: null /* TODO */, kind: 'string' },
    role: { figmaProp: null /* TODO */, kind: 'string' },
    rel: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): ariaCurrent -- [#page | #step | #location | #date | #time | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): ariaHaspopup -- [#menu | #listbox | #tree | #grid | #dialog | #"true" | #"false"] -- not confidently classifiable
    // TODO (unsupported): onCopy -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onCut -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onPaste -- ReactEvent.Clipboard.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onInput -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onSubmit -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyDown -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyPress -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onKeyUp -- ReactEvent.Keyboard.t => unit -- event handler, code-only
    // TODO (unsupported): onClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onContextMenu -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDoubleClick -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrag -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onDrop -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseDown -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseEnter -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseLeave -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseMove -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOut -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseOver -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onMouseUp -- ReactEvent.Mouse.t => unit -- event handler, code-only
    // TODO (unsupported): onScroll -- ReactEvent.UI.t => unit -- event handler, code-only
    // TODO (unsupported): onWheel -- ReactEvent.Wheel.t => unit -- event handler, code-only
    form: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): formAction -- CommonTypes.tabsFormAction<'a> -- not confidently classifiable
    formEncType: { figmaProp: null /* TODO */, kind: 'string' },
    formMethod: { figmaProp: null /* TODO */, kind: 'string' },
    formNoValidate: { figmaProp: null /* TODO */, kind: 'bool' },
    formTarget: { figmaProp: null /* TODO */, kind: 'string' },
    name: { figmaProp: null /* TODO */, kind: 'string' },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    asChild: { figmaProp: null /* TODO */, kind: 'bool' },
    variant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TabsTypes.Boxed', // ReScript: Boxed (bound value "boxed")
        // TODO_FIGMA_KEY: 'TabsTypes.Floating', // ReScript: Floating (bound value "floating")
        // TODO_FIGMA_KEY: 'TabsTypes.Underline', // ReScript: Underline (bound value "underline")
        // TODO_FIGMA_KEY: 'TabsTypes.Pills', // ReScript: Pills (bound value "pills")
      },
    },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TabsTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'TabsTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'TabsTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    closable: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onClose -- unit => unit -- event handler, code-only
    disable: { figmaProp: null /* TODO */, kind: 'bool' },
    isActive: { figmaProp: null /* TODO */, kind: 'bool' },
    isOverlay: { figmaProp: null /* TODO */, kind: 'bool' },
    tabsGroupId: { figmaProp: null /* TODO */, kind: 'string' },
    showSkeleton: { figmaProp: null /* TODO */, kind: 'bool' },
    skeletonVariant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Pulse', // ReScript: Pulse (bound value "pulse")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Wave', // ReScript: Wave (bound value "wave")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Shimmer', // ReScript: Shimmer (bound value "shimmer")
      },
    },
  },
}
