// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TagSkeleton.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TagSkeleton',
  id: 'tagSkeleton',
  imports: ['open JuspayRescriptBlend'],
  props: {
    showSkeleton: { figmaProp: null /* TODO */, kind: 'bool' },
    skeletonVariant: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'SkeletonTypes.Pulse', // ReScript: Pulse (bound value "pulse")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Wave', // ReScript: Wave (bound value "wave")
        // TODO_FIGMA_KEY: 'SkeletonTypes.Shimmer', // ReScript: Shimmer (bound value "shimmer")
      },
    },
    text: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Xs', // ReScript: Xs (bound value "xs")
        // TODO_FIGMA_KEY: 'TagV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'TagV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'TagV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    subType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Rounded', // ReScript: Rounded (bound value "rounded")
        // TODO_FIGMA_KEY: 'TagV2Types.Squarical', // ReScript: Squarical (bound value "squarical")
      },
    },
    color: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Neutral', // ReScript: Neutral (bound value "neutral")
        // TODO_FIGMA_KEY: 'TagV2Types.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'TagV2Types.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'TagV2Types.Error', // ReScript: Error (bound value "error")
        // TODO_FIGMA_KEY: 'TagV2Types.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'TagV2Types.Purple', // ReScript: Purple (bound value "purple")
      },
    },
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
  },
}
