// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TagV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TagV2',
  id: 'tagV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    text: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Xs', // ReScript: Xs (bound value "xs")
        // TODO_FIGMA_KEY: 'TagV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'TagV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'TagV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    subType: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Rounded', // ReScript: Rounded (bound value "rounded")
        // TODO_FIGMA_KEY: 'TagV2Types.Squarical', // ReScript: Squarical (bound value "squarical")
      },
    },
    color: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TagV2Types.Neutral', // ReScript: Neutral (bound value "neutral")
        // TODO_FIGMA_KEY: 'TagV2Types.Primary', // ReScript: Primary (bound value "primary")
        // TODO_FIGMA_KEY: 'TagV2Types.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'TagV2Types.Error', // ReScript: Error (bound value "error")
        // TODO_FIGMA_KEY: 'TagV2Types.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'TagV2Types.Purple', // ReScript: Purple (bound value "purple")
      },
    },
    // TODO (unsupported): leftSlot -- TagV2Types.tagV2LeftSlotConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rightSlot -- TagV2Types.tagV2LeftSlotConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): skeleton -- TagV2Types.tagV2SkeletonConfig -- variant has payload(s) or is a record, not a simple enum
    tagGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'ButtonTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'ButtonTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'ButtonTypes.Right', // ReScript: Right (bound value "right")
      },
    },
  },
}
