// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TextInput.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TextInput',
  id: 'textInput',
  imports: ['open RescriptBlend'],
  props: {
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    error: { figmaProp: null /* TODO */, kind: 'bool' },
    errorMessage: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'InputsTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'InputsTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightSlot -- React.element (slot/children) -- needs manual handling
    value: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    cursor: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Text', // ReScript: Text (bound value "text")
        // TODO_FIGMA_KEY: 'InputsTypes.Default', // ReScript: Default (bound value "default")
        // TODO_FIGMA_KEY: 'InputsTypes.NotAllowed', // ReScript: NotAllowed (bound value "not-allowed")
        // TODO_FIGMA_KEY: 'InputsTypes.Pointer', // ReScript: Pointer (bound value "pointer")
      },
    },
    passwordToggle: { figmaProp: null /* TODO */, kind: 'bool' },
    textInputGroupPosition: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.Center', // ReScript: Center (bound value "center")
        // TODO_FIGMA_KEY: 'InputsTypes.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'InputsTypes.Right', // ReScript: Right (bound value "right")
      },
    },
  },
}
