// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TextAreaV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TextAreaV2',
  id: 'textAreaV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    value: { figmaProp: null /* TODO */, kind: 'string' },
    placeholder: { figmaProp: null /* TODO */, kind: 'string' },
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    autoFocus: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onChange -- ReactEvent.Form.t => unit -- event handler, code-only
    // TODO (unsupported): onFocus -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): onBlur -- ReactEvent.Focus.t => unit -- event handler, code-only
    // TODO (unsupported): rows -- int -- not confidently classifiable
    label: { figmaProp: null /* TODO */, kind: 'string' },
    sublabel: { figmaProp: null /* TODO */, kind: 'string' },
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconText: { figmaProp: null /* TODO */, kind: 'string' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): error -- EditorSharedTypes.inputsV2ErrorConfig -- variant has payload(s) or is a record, not a simple enum
    resize: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'InputsTypes.None', // ReScript: None (bound value "none")
        // TODO_FIGMA_KEY: 'InputsTypes.Block', // ReScript: Block (bound value "block")
        // TODO_FIGMA_KEY: 'InputsTypes.Inline', // ReScript: Inline (bound value "inline")
        // TODO_FIGMA_KEY: 'InputsTypes.Both', // ReScript: Both (bound value "both")
        // TODO_FIGMA_KEY: 'InputsTypes.Horizontal', // ReScript: Horizontal (bound value "horizontal")
        // TODO_FIGMA_KEY: 'InputsTypes.Vertical', // ReScript: Vertical (bound value "vertical")
      },
    },
  },
}
