// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TextInputV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TextInputV2',
  id: 'textInputV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    value: { figmaProp: null /* TODO */, kind: 'string' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    subLabel: { figmaProp: null /* TODO */, kind: 'string' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'EditorSharedTypes.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): error -- EditorSharedTypes.inputsV2ErrorConfig -- variant has payload(s) or is a record, not a simple enum
    hintText: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): dropdown -- EditorSharedTypes.InputsV2Dropdown.t, // ⓘ was `TextInputV2Dropdown | TextInputV2Dropdown[]` — opaque; build with InputsV2Dropdown.fromTextInputV2Dropdown / InputsV2Dropdown.fromTextInputV2Dropdowns -- not confidently classifiable
    // TODO (unsupported): leftSlot -- EditorSharedTypes.inputsV2LeftSlotConfig -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): rightSlot -- EditorSharedTypes.inputsV2LeftSlotConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
