// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TimelineShowMore.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TimelineShowMore',
  id: 'timelineShowMore',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): count -- int -- not confidently classifiable
    label: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): onShowMore -- unit => unit -- event handler, code-only
    // TODO (unsupported): buttonProps -- ButtonV2Types.buttonV2ButtonPropsConfig -- variant has payload(s) or is a record, not a simple enum
  },
}
