// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TimelineNode.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TimelineNode',
  id: 'timelineNode',
  imports: ['open JuspayRescriptBlend'],
  props: {
    title: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): leftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): headerRightSlot -- React.element (slot/children) -- needs manual handling
    datetime: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): datetimeLeftSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): datetimeRightSlot -- React.element (slot/children) -- needs manual handling
    text: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): maxLines -- float -- not confidently classifiable
    // TODO (unsupported): user -- TimelineTypes.timelineUser -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): avatarProps -- AvatarV2Types.avatarV2AvatarPropsConfig -- variant has payload(s) or is a record, not a simple enum
    time: { figmaProp: null /* TODO */, kind: 'string' },
    status: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TimelineTypes.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'TimelineTypes.Warning', // ReScript: Warning (bound value "warning")
        // TODO_FIGMA_KEY: 'TimelineTypes.Error', // ReScript: Error (bound value "error")
        // TODO_FIGMA_KEY: 'TimelineTypes.Neutral', // ReScript: Neutral (bound value "neutral")
      },
    },
  },
}
