// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TooltipV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TooltipV2',
  id: 'tooltipV2',
  imports: ['open RescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): content -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): onOpenChange -- bool => unit -- event handler, code-only
    side: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TooltipV2Types.Top', // ReScript: Top (bound value "top")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Right', // ReScript: Right (bound value "right")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Bottom', // ReScript: Bottom (bound value "bottom")
      },
    },
    align: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TooltipV2Types.Start', // ReScript: Start (bound value "start")
        // TODO_FIGMA_KEY: 'TooltipV2Types.End', // ReScript: End (bound value "end")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Center', // ReScript: Center (bound value "center")
      },
    },
    showArrow: { figmaProp: null /* TODO */, kind: 'bool' },
    size: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TooltipV2Types.Sm', // ReScript: Sm (bound value "sm")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Md', // ReScript: Md (bound value "md")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Lg', // ReScript: Lg (bound value "lg")
      },
    },
    // TODO (unsupported): slot -- React.element (slot/children) -- needs manual handling
    slotDirection: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'TooltipV2Types.Left', // ReScript: Left (bound value "left")
        // TODO_FIGMA_KEY: 'TooltipV2Types.Right', // ReScript: Right (bound value "right")
      },
    },
    // TODO (unsupported): delayDuration -- float -- not confidently classifiable
    // TODO (unsupported): offset -- float -- not confidently classifiable
    maxWidth: { figmaProp: null /* TODO */, kind: 'string' },
    fullWidth: { figmaProp: null /* TODO */, kind: 'bool' },
    disableInteractive: { figmaProp: null /* TODO */, kind: 'bool' },
  },
}
