// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/TopbarV2.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'TopbarV2',
  id: 'topbarV2',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    isExpanded: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onToggleExpansion -- unit => unit -- event handler, code-only
    showToggleButton: { figmaProp: null /* TODO */, kind: 'bool' },
    panelOnlyMode: { figmaProp: null /* TODO */, kind: 'bool' },
    isVisible: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onVisibilityChange -- bool => unit -- event handler, code-only
    defaultIsVisible: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): sidebarTopSlot -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): topbar -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): leftAction -- React.element (slot/children) -- needs manual handling
    // TODO (unsupported): rightActions -- React.element (slot/children) -- needs manual handling
    showBackButton: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): onBackClick -- unit => unit -- event handler, code-only
    // TODO (unsupported): secondarySidebar -- SidebarV2Types.secondarySidebarInfo -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): merchantInfo -- TopbarV2Types.merchantInfoV2 -- variant has payload(s) or is a record, not a simple enum
    ariaControls: { figmaProp: null /* TODO */, kind: 'string' },
  },
}
