// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/Upload.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'Upload',
  id: 'upload',
  imports: ['open RescriptBlend'],
  props: {
    multiple: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): accept -- array<string> -- not confidently classifiable
    // TODO (unsupported): maxSize -- float -- not confidently classifiable
    // TODO (unsupported): maxFiles -- float -- not confidently classifiable
    disabled: { figmaProp: null /* TODO */, kind: 'bool' },
    required: { figmaProp: null /* TODO */, kind: 'bool' },
    label: { figmaProp: null /* TODO */, kind: 'string' },
    subLabel: { figmaProp: null /* TODO */, kind: 'string' },
    helpIconHintText: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): children -- React.element (slot/children) -- needs manual handling
    description: { figmaProp: null /* TODO */, kind: 'string' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    errorText: { figmaProp: null /* TODO */, kind: 'string' },
    state: {
      figmaProp: null, // TODO: Figma property name
      kind: 'enum',
      values: {
        // TODO_FIGMA_KEY: 'UploadTypes.Idle', // ReScript: Idle (bound value "idle")
        // TODO_FIGMA_KEY: 'UploadTypes.Uploading', // ReScript: Uploading (bound value "uploading")
        // TODO_FIGMA_KEY: 'UploadTypes.Success', // ReScript: Success (bound value "success")
        // TODO_FIGMA_KEY: 'UploadTypes.Error', // ReScript: Error (bound value "error")
      },
    },
    // TODO (unsupported): uploadingFiles -- array<UploadTypes.uploadFile> -- not confidently classifiable
    // TODO (unsupported): uploadedFiles -- array<UploadTypes.uploadedFileWithStatus> -- not confidently classifiable
    // TODO (unsupported): failedFiles -- array<UploadTypes.uploadedFileWithStatus> -- not confidently classifiable
    enforceFileTypeConsistency: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): progressSpeed -- float -- not confidently classifiable
    // TODO (unsupported): value -- UploadTypes.UploadFormValue.t, // ⓘ was `UploadFormValue` — opaque; build with UploadFormValue.fromFile / UploadFormValue.fromFiles -- not confidently classifiable
    // TODO (unsupported): onChange -- UploadTypes.UploadFormValue.t => unit, // ⓘ was `UploadFormValue` — opaque; build with UploadFormValue.fromFile / UploadFormValue.fromFiles -- event handler, code-only
    // TODO (unsupported): onDrop -- (array<Webapi.File.t>, array<UploadTypes.fileRejection>) => unit -- event handler, code-only
    // TODO (unsupported): onDropAccepted -- array<Webapi.File.t> => unit -- event handler, code-only
    // TODO (unsupported): onDropRejected -- array<UploadTypes.fileRejection> => unit -- event handler, code-only
    // TODO (unsupported): onFileRemove -- string => unit -- event handler, code-only
    // TODO (unsupported): onReplaceFile -- unit => unit -- event handler, code-only
    // TODO (unsupported): onStateChange -- UploadTypes.uploadOnStateChangeConfig => unit -- event handler, code-only
    isDragActive: { figmaProp: null /* TODO */, kind: 'bool' },
    isDragAccept: { figmaProp: null /* TODO */, kind: 'bool' },
    isDragReject: { figmaProp: null /* TODO */, kind: 'bool' },
    // TODO (unsupported): validator -- Webapi.File.t => Nullable.t<UploadTypes.uploadFileRejectionErrorsConfig> -- event handler, code-only
    // TODO (unsupported): actionSlot -- React.element (slot/children) -- needs manual handling
  },
}
