// SCAFFOLD generated by scripts/scaffold-figma-component-maps.mjs from src/VirtualList.res.
// ReScript-side prop names/kinds (and, for simple enums, code-side constructor
// names) are derived from our own bindings -- safe, no Figma guessing.
// Figma-side property names and enum KEYS are UNKNOWN and must be filled in
// by checking the real component in Figma Desktop. This file is NOT ready
// for figma:generate until every 'null'/'TODO_FIGMA_KEY' below is resolved
// (unresolved entries are skipped by the codegen script, not guessed).

export default {
  figmaComponentName: null, // TODO: confirm the Figma component/component-set name
  codeComponent: 'VirtualList',
  id: 'virtualList',
  imports: ['open JuspayRescriptBlend'],
  props: {
    // TODO (unsupported): items -- array<'a> -- not confidently classifiable
    // TODO (unsupported): renderItem -- VirtualListTypes.virtualListRenderParams<'a> => React.element -- event handler, code-only
    // TODO (unsupported): height -- CommonTypes.stringOrNumber -- variant has payload(s) or is a record, not a simple enum
    // TODO (unsupported): itemHeight -- float -- not confidently classifiable
    // TODO (unsupported): overscan -- float -- not confidently classifiable
    // TODO (unsupported): onScroll -- float => unit -- event handler, code-only
    // TODO (unsupported): onEndReached -- unit => unit -- event handler, code-only
    // TODO (unsupported): endReachedThreshold -- float -- not confidently classifiable
    isLoading: { figmaProp: null /* TODO */, kind: 'bool' },
    hasMore: { figmaProp: null /* TODO */, kind: 'bool' },
    className: { figmaProp: null /* TODO */, kind: 'string' },
    // TODO (unsupported): style -- JsxDOM.style -- not confidently classifiable
  },
}
